### ISSUE TITLE
feature request: mkvmerge should be able to present the cores which are embedded into HD audio codecs

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1107]
**Original reporter**: *remuxer32*

There are three audio codecs which contain the embedded core: DTS-HD Master Audio & DTS-HD High Resolution Audio (DTS core) and Dolby TrueHD (AC3 core). So far mkvmerge doesn't present the cores therefore the users cannot choose if they want to mux — for example — TrueHD with AC3 core (in one .mkv file, but separately of course) or only one of them. The same situation applies the core of DTS which can't be chosen as a single to mux; it is important to note that many people don't need lossless DTS-HD MA (which size is often very large) ===> that's why the single DTS core (+/- 1GB) is absolutely sufficient and rewarding.

Currently when someone wants to add the core to mmg, previously has to extract it using tsMuxeR (wasting time, but necessary) or use MakeMKV [which shows, and allows to select (or not), the core] instead of mkvmerge GUI. For me and other people (who really like and appreciate mkvmerge GUI) that situation is definitely unacceptable. Our life would be much easier and faster if we could decide which »hidden« audio track to select and mux.

Summarizing: I know that this feature is very difficult to implement because it would require massive re-writes of a lot of code, but I'm convinced that it will be possible in the far future.
***We will find a way. We always have*.** ☺

**Comment by mbunkus** [comment]
For TrueHD read from raw TrueHD files and from MPEG transport streams this has been implemented by presenting the embedded AC3 core as a separate track.

It hasn't been implemented for TrueHD read from EVOBs yet because I couldn't find a sample file for that.

For DTS tracks a new command line option, `--reduce-to-core`, has been implemented.

mmg has not been updated, and I don't plan on doing so. You can add the option `--reduce-to-core <TID>` manually on the »extra options« sub-tab in the »user defined options« input box.

**Comment by remuxer32** [comment]
Oh man, you did it! I'm really impressed. I didn't expect it so fast :). Thank you very much Mosu for your time and work. I'm truly grateful for this feature. Now mkvmerge is more friendly and useful tool. A lot of people will be satisfied and happy because of you :). Our work will be certainly much easier now. You are a good man.

> „It hasn't been implemented for TrueHD read from EVOBs yet because I couldn't find a sample file for that”.

To be more precise: do you mean EVOBs files (HD-DVDs) which contain TrueHD audio track(s) WITH the embedded (AC3) core, right? If so: that's impossible because all TrueHD tracks, which are included in EVOBs (HD-DVDs), don't contain the embedded (AC3) core — of course there is an AC3 data, but as a separate audio track only. The different situation is on BDs where all TrueHD tracks must contain the embedded (AC3) core ====> this is due to with the Blu-ray's specification that states about it. 

Summarizing: If you want, I can try to find an EVOB file which contains TrueHD track (but without the embedded core of course) and then upload it to your FTP server. But I suspect that you are not interested to implement support for such an obsolete format unless your point of view has changed? :). Also, especially for you, I may try to find EVOBs files that contain (L)PCM audio tracks! =====> then you could add a support for that, but it will be very difficult to find those files (they are really rare).

Thank you again and regards!

**Comment by mbunkus** [comment]
You're quite welcome. I still have a bit of work left – I may have made certain situations worse (TrueHD audio tracks not starting at timecode 0) that I won't to investigate. And right before falling asleep I realized one more error that I have to fix. Afterwards I will compile and upload new pre-builds for Windows for you to play with.

About EVOBs. I do have EVOBs with TrueHD inside, but I wasn't aware that HD-DVDs weren't allowed to have TrueHD with AC3 in the same track. As this is the case I don't think we should spend any time trying to find samples with EVOBs and TrueHD+AC3.

LPCM is already supported in EVOBs. It has been since release 7.3.0; see the [ChangeLog entry](https://github.com/mbunkus/mkvtoolnix/blob/master/ChangeLog#253) from 2014-09-17.

**Comment by remuxer32** [comment]
Thank you for heads-up. I will test with pleasure your new pre-builds for Windows :).

**Comment by mbunkus** [comment]
New builds [are up](https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/) (build numbers 657 and 658).

**Comment by mbunkus** [comment]
…and I've just noticed that the file name lacks the version numbers. I'll fix that and create new builds.

**Comment by mbunkus** [comment]
New builds [are up again](https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/) (build numbers 659, 660).

**Comment by remuxer32** [comment]
Thank you for new builds. I will be testing new features intensively and, of course, I will inform you if I find any bugs.

**Comment by remuxer32** [comment]
All right. All tests were successfully finished; I haven't found any bugs. New features work perfectly, but I've got two suggestions to you: 

1) Could you add a new command line option, »--reduce-to-core«, to the box of the »Add command line options«, please? I mean: »muxing« ---------> »Add command line options«. Yes, I would like to choose that option »permanently«. It would be very useful for me and other people. Currently I have to add that feature manually; well, it's not difficult of course, but takes some time.

2) I think you should update this entry ========> https://github.com/mbunkus/mkvtoolnix/wiki/TrueHD-and-AC3 because (as mkvmerge recognizes the embedded core now) the third paragraph is out-of-date at the moment. 

Thank you.

**Comment by mbunkus** [comment]
About 1): I'll see to it.

About 2): Thanks for the hint. I've updated the FAQ entry accordingly.

**Comment by mbunkus** [comment]
Ah wait. Implementing 1) is not possible because that option is a track-specific option. It has to be used on the track's extra options tab with the track's ID. The »add command line options« dialog can only be used for global options.

**Comment by remuxer32** [comment]
Thank you for clarification. Now I understand precisely. By the way: when you will release 7.7.0 version then I suspect that you will be obligated to explain many users of how to use a new command line option (you will receive a lot of questions — e.g. where and how to write that command :D). Some people may be really nerve-wracking. »Sigh!«.

**Comment by mbunkus** [comment]
You can always check the planned dates for the next release on the [milestones page](/mbunkus/mkvtoolnix/milestones) of the issues section. I will be very busy in March (pretty much every weekend is full already), and therefore I'm planning on early April. I might change my mind and do the release this weekend, but the probability is not that high.

I will also probably add a checkbox corresponding to the new `--reduce-to-core` option in the old GUI after all.

**Comment by remuxer32** [comment]
Thank you for a new decision to add a checkbox.. About the milestones page: I know about it; I always check that site when I'm interested in the next releases ☺.

**Comment by mbunkus** [comment]
I've implemented that checkbox in 5322dcf3befd2a752c55c361852bb35d147fd424. New [pre-builds including the checkbox](https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/) will be available in a couple of minutes (build numbers 672 and 673).

**Comment by remuxer32** [comment]
**@Mosu**

About reducing to its core: recently I was analyzing that option very carefully; ipso facto I've got two very important tips for you:

**1)** In the new GUI, on the right side, in »Audio properties«, you can see the following check box: **»Reduce to core«**. Fine, but what kind of core do we mean exactly? AC3 core, DTS core or maybe something else? Don't you think that such a sentence is very, very vague (unclear) and leaves a lot of possibilities for interpretation? Of course you and I know very well what kind of core it is, but there are users who are not advanced and don't have a sufficient knowledge to understand that matter. Yes, we can read a tool tip, but most people are lazy and don't read any tips at all. That's why I've got a nice proposition: **»Reduce to the DTS core«** <==== Such a description is much better and clearer for most people. These are just two words (»the DTS«), but thanks to them we are absolutely »enlightened« and know »what's going on«. I'll be very grateful if you accept my minor change.

**2)** And now something more serious. Let's analyze the following sentences from the tool tip:

**a)** »Drops **the lossless extensions** from an audio track and keeps only its lossy core«.

First of all: this is a half-truth. Why? Let me specify. There are only TWO audio codecs that contain the DTS core:

► DTS-HD Master Audio
► DTS-HD High Resolution Audio

Both of them contain the HD extension, but what is the main difference between them? It's easy: Master Audio is LOSSLESS, but High Resolution is LOSSY. Look here: http://m.pioneer-india.in/wp-content/uploads/2012/08/phase_control_23.jpg 
Hence: **»the lossless extensions«** is RIGHT for Master Audio = 1, but WRONG for High Resolution = 0. The final conclusion is: the whole sentence is FALSE.

**b)** »This only works with **DTS audio tracks**«.

Such a sentence is a generalization of course. Why? Again: what kind of DTS tracks do we mean exactly? Do we mean: plain DTS, DTS-HD, DTS-ES or maybe DTS Express? The right answer is DTS-HD audio tracks obviously, but most users have no idea about it. And also: such a description is very unclear, of course.
_______________________________________________________________________________

Summarizing: therefore what should we do? Here's my proposition:

About **a)**: »Drops **the HD extension(s)** from an audio track and keeps only its lossy core«.

About **b)**: »This only works with **DTS-HD audio tracks that contain the embedded DTS core**«.

The full sentence: **»Drops the HD extension(s) from an audio track and keeps only its lossy core. This only works with DTS-HD audio tracks that contain the embedded DTS core«.**

In my opinion it looks gorgeous, doesn't it? ☺. So: could you implement my changes in the .po files in free time, please? I'll be truly very grateful for that. I think my proposition is the most accurate. I'm sure that users shouldn't have any doubts with a proper interpretation of such a tip. 
Don't get me wrong: I'm not a conceited man, just I'm trying to help you and other users. Thank you very much for considering my idea. 

BTW: minor nitpick: mkvmerge shows DTS-HD HR audio tracks as DTS-HD Hight Resolution. Well, it's almost good because the full name is DTS-HD High Resolution **Audio** ☺. (Yeah, I know, I'm a purist :D). Maybe you could........ one rainy day ;).

**Comment by mbunkus** [comment]
Renaming the check box's text is out of the question because that option is supposed to be useful for other audio codecs in the future, too. At the moment it only applies to DTS, yes, but that might be extended one day.

Changing the tool tip sounds useful, but not to what you've suggested – for the same reasons stated above.

Note that in MKVToolNix TrueHD+AC3 audio tracks are presented as two separate audio tracks. Therefore I don't think there's a high probability a user will think »oh this will reduce an AC3 track to… well… something«.

**Comment by remuxer32** [comment]
>That option is supposed to be useful for other audio codecs in the future, too. At the moment it only applies to DTS, yes, but that might be extended one day.

Hmmm, at the moment there are only two possibilities: AC3 core from TrueHD or DTS core from DTS-HD MA & HRA. There is no the third way. There are no concrete plans from BDA to implement a »new core« for backward compatibility. Indeed, maybe someday somebody will invent a new codec with the new core, but it's very unlikely. Maybe you mean some audio codecs which I don't know?

>Note that in MKVToolNix TrueHD+AC3 audio tracks are presented as two separate audio tracks. Therefore I don't think there's a high probability a user will think »oh this will reduce an AC3 track to… well… something«.

Right, a probability is very low, but.... who knows :)

A little digression (nothing to do with the topic) : unless you are going to implement something like this: **»extract the DTS core only«** (from DTS-HD MA & DTS-HD HRA). That's my original idea (I told you about it someday; you said: »no, definitely«. Well, my point of view is that it makes sense because there are many people who don't need a full HD audio track (which size is very large), therefore just the DTS core is absolutely sufficient (+/- 1GB). Then they can put it into another container (e.g. MP4) and play very well using many players. Of course such a feature would have to be implemented in the »extract tool« (in the far future). Yes, I know that there are tools that I can use (e.g. tsMuxeR GUI), but first: tsMuxeR is not supported anymore, and second: has tons of bugs, surely. Think about it please, thanks.

**Comment by mbunkus** [comment]
Yes, currently that option only applies to DTS tracks. However, I've named the option `--reduce-audio-to-core` and not `--reduce-dts-to-core` in order to be able to re-use that option for a future audio track that might get invented that does have some similar concept.

I don't understand your last paragraph, to be honest. I don't have a particular interest in discussing this topic at the moment either. Sorry.

**Comment by remuxer32** [comment]
>However, I've named the option --reduce-audio-to-core and not --reduce-dts-to-core in order to be able to re-use that option for a future audio track that might get invented that does have some similar concept.

Ah, now I understand your intention very well. Indeed: a good idea for the unknown future. Thanks :)
