### ISSUE TITLE
feature request: accurate designations for audio codecs such as DTS-HD MA & DTS-HD HRA which are shown as »DTS«

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1109]
**Original reporter**: *remuxer32*

Currently mkvmerge is the only tool which shows/displays HD audio tracks, like DTS-HD MA/DTS-HD HRA, as »DTS«. With all due respect, but in my opinion that situation is really ridiculous. It is important to note that this behaviour may cause a lot of confusions among people who are not advanced and don't know which audio track to select if a file contains a lot of DTS tracks. That's why I propose you to implement more precise designations (terms). There are two solutions: short or long form:

1) Short form:
**DTS-HD MA / DTS-HD HRA**

2) Long form:
**DTS-HD Master Audio / DTS-HD High Resolution Audio**

Which one to choose? Personally I would like to implement long form, but it's your individual choice. If you want, you could also implement additional information such as: the number of channels (e.g. 5.1, 6.1, 7.1), information about the embedded core or even which audio codec is lossless or lossy ☺. All right, I know it's rather impossible, but would be really cool. Seriously: it's enough to implement correct designations instead of »DTS«.
Good luck!

**Comment by sub0ptimal** [comment]
I would guess that the reason this information is not already in the mkvmerge GUI is that it is not in the TrackEntry/Audio EBML element.  Wouldn't mkvmerge have to examine the stream to figure out these details?

**Comment by mbunkus** [comment]
Yes, that's right.

**Comment by mbunkus** [comment]
I've implemented this. It has been tested and works well with raw DTS files, DTS in MPEG transport streams (`.m2ts`) and MP4 files.

It's been implemented but not tested due to lack of sample files for DTS in MPEG program streams (`.vob`, `.evo`).

It has not been implemented for DTS in AVI for two reasons: 1. the AVI handling code would need a moderate re-write and 2. I lack a test file. As I don't feel confident that I can successfully implement this for AVIs without a test file I simply won't attempt it at the moment (maybe never). I may revisit this topic if I can get my hands on a test file.

**Comment by remuxer32** [comment]
Outstanding! Thank you very much Mosu. Now mkvmerge is absolutely brilliant and more firendly, but..... it's not the end yet* ☺.

But first:

1) About .VOBS & .EVOBS:

a) All DVDs (.vobs) do not contain any HD audio tracks; at most DTS-ES or plain DTS tracks.

b) Most of the HD-DVDs (.evobs) also do not contain any HD (MA or HR) audio tracks but, of course, there are several exceptions (e.g. »Alexander« or »Lucky Number Slevin«). Anyway: it's an obsolete format so we don't have to care about the .evobs: probably there will be no issues related to them.

2) About AVIs: you don't have to worry about them because there are no (probably) AVIs with HD audio tracks; at most plain DTS only. Personally, I have never seen anywhere AVIs with MA/HR audio codecs so far. I'm not sure, but probably AVIs are not compatible (they cannot cope?) with a huge variable bitrate of Master Audio (lossless audio codec) and with a constant bitrate (lower, but still huge) of High Resolution (lossy audio codec). Look here: http://en.wikipedia.org/wiki/Comparison_of_container_formats 

Apart from these two points, the most important thing is that your »mission« hasn't been completed yet (*like I wrote at the beginning). Why? The answer is: .SSIF files! Yes, .SSIF files = 3D Blu-ray Discs ☺ therefore I suspect that someday you will have to reopen this issue and implement a more detailed description for HD audio tracks which are included in .SSIF files. So far I have seen 3D BD releases with Master Audio tracks only (e.g. »Predator«, »The Hobbit« or »Man of Steel«, but no .SSIF files with High Resolution tracks — I think it's fine because DTS-HD HR is a crap; okay, maybe sound quality is high but we cannot forget that it is a LOSSY! codec). Sorry for my digression, but I had to mention about this. 
Summarizing: maybe you should reference the #1106 issue with this item or vice versa? In my opinion both issues are related together in a certain sense.

By the way: Can I count on a pre-build (32-bit) version, please? I would like to test this enhancement — I will be very grateful for that. Just I wouldn't like to wait until May 3. Thank you for your goodwill.

**Comment by mbunkus** [comment]
No need for special notifications for enhancement tickets. If I ever add support for those files I will think of DTS; I don't need a reminder.

A 32bit pre-build [has been uploaded](https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/).

**Comment by remuxer32** [comment]
Thank you for a pre-build version. I have been testing the new enhancement for a few hours; so far everything works great :).
