### ISSUE TITLE
mkvmerge gui v7.6 crash

### ISSUE THREAD

**Issue by philphil61** [mbunkus/mkvtoolnix#1115]
When right clicking Output filename to paste new name an error message appears - see image

http://i.imgur.com/W0xZNhs.png

The option to stop mkvmerge gui or ignore "warnings" is there!

**Comment by mbunkus** [comment]
Hey,

> When right clicking Output filename to paste new name an error message
> appears - see image

I don't have any special code for handling right-clicks in that input
box. So the error you see is coming from the underlying toolkit library
I use, wxWidgets. Unfortunately there's nothing I can do about issues
internal to said library.

Kind regards,
mosu

**Comment by mbunkus** [comment]
Another user did have the same problem, so it's definitely a thing. He also pointed out that it didn't happen with the previous release, 7.5.0.

I had updated the libraries between releases 7.5.0 and 7.6.0, among them wxWidgets. So yesterday I downgraded wxWidgets from 3.0.2 back to 3.0.0 and lo and behold, the issue is gone.

There are new pre-builds linked against the older version at http://www.bunkus.org/videotools/mkvtoolnix/win32/pre/
