### ISSUE TITLE
Consider using Biicode to manage dependencies

### ISSUE THREAD

**Issue by sschuberth** [mbunkus/mkvtoolnix#1118]
mkvtoolnix depends on quite a few libraries. If you're unlucky, these are not easily installable from pre-compiled binaries for your platform. So in order to lower the hurdle for contributors, consider using [Biicode](https://www.biicode.com/) to easily retrieve and set up required dependencies across platforms.

**Comment by mbunkus** [comment]
I know about Biicode, I've read the [article on OpenSource.com](http://opensource.com/business/15/1/biicode-open-source-dependency-manager). I definitely like the idea, but at the moment I don't have any intention of tackling this any time soon. I would definitely be open to patches, but I have other priorities for my own time.

I'll leave this open because, knowing myself, I will probably do something about this one rainy day.

**Comment by mbunkus** [comment]
After thinking some more about this I've decided to close the issue as wontfix. I simply have a lot more things that I'd prefer to work on, and so far no one has contributed anything in this direction either. Neither have there been requests to do something about this issues; therefore I judge the interest to be non-existent at this point.
