### ISSUE TITLE
cues.cpp fails to compile on OS X

### ISSUE THREAD

**Issue by Noctem** [mbunkus/mkvtoolnix#1132]
Compilation fails on the new [cues.cpp](https://github.com/mbunkus/mkvtoolnix/blob/fcb139a519151418cb9028f2ebbd80fa58f8c631/src/extract/cues.cpp#L84) file with the following error:
```
    LINK src/mkvinfo
     CXX src/extract/cues.cpp
     CXX src/extract/cuesheets.cpp
     CXX src/extract/extract_cli_parser.cpp
     CXX src/extract/options.cpp
src/extract/cues.cpp:84:12: fatal error: chosen constructor is explicit in copy-initialization
    return {};
           ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: constructor declared here
    explicit map(const key_compare& __comp = key_compare())
```

**OS:** OS X 10.10.2
**Compiler:** Clang 6.0 (LLVM)
**Version:** current git master (581f6241cb)

**Comment by mbunkus** [comment]
Try this patch: https://gist.github.com/mbunkus/726f3d8cb9b9f6fc950e

**Comment by Noctem** [comment]
Well that was fast. It compiles properly with that patch. Thanks!

**Comment by mbunkus** [comment]
Hmm, this seems to be due to `std::map` not having a constructor `map()` (one without arguments) before C++14 – and the only other constructor that doesn't take any arguments is indeed marked as explicit. Therefore using `return std::map<int64_t, int64_t>{}` would probably have worked, too.

Starting with C++14 we will have a argument-less constructor that's not marked as `explicit` which would solve this situation, too.

See [cppreference.com about std::map](http://en.cppreference.com/w/cpp/container/map/map) if you're interested.
