### ISSUE TITLE
possible bug - occurs not requested merging of mpg files in sequence.

### ISSUE THREAD

**Issue by adminio** [mbunkus/mkvtoolnix#1164]
This strange issue occurs sistematically with version 7.8.0 64 bit.

1- having two mpg video, for example video_1.mpg and video_2.mpg, in the same folder 
2- open video_1.mpg in toolnix for conversion to mkv container and apply conversion
to video_1.mkv
3- absolutely ignore video_2.mpg (i.e. do NOT use append method to merge the files in sequence)
because this file has nothing to do with the previous.

but:

the resulting video_1.mkv  not only contain data from video_1.mpg but also automatically contains the data from file video_2.mpg merged in sequence after the first file.

Note: 
a) renaming the second file PREVENT the bug to occurs.
b) this bug occurs to me only with .mpg files. Other file tipes are not affected.

ps: Sorry for my bad english.

**Comment by mbunkus** [comment]
This is not a bug, it's intentional behavior for supporting reading MPEG program streams (VOBs) from DVDs. They're named `VTS_01_1.VOB`, `VTS_01_2.VOB`.

You can prevent this behavior in two ways:

1. If you're using the command line then prefixing the file name with `=`, e.g. `mkvmerge -o out.mkv = video_1.mpg`.
2. If you're using mmg (the GUI) then add the file `video_1.mpg` normally, then select it and click on the `additional files` dialog. In this dialog remove all the entries. Now set the other options the way you want them to be and start muxing.

**Comment by mbunkus** [comment]
Hmm, while this is intentional I can probably improve this by only looking for the other files if the file name actually starts with `VTS_…`. Otherwise the source file is most likely not coming from a DVD, like in your case.

I'm therefore re-opening this again.

**Comment by adminio** [comment]
Ok. Usually i do not use mkvmerge to open vob files, so before this moment i'm not aware about this intentional behavior.
So this is not a bug, however i thik that your improving solution is useful to avoid confusion in non expert user (like me).
