### ISSUE TITLE
Problems with advapi32.dll

### ISSUE THREAD

**Issue by adshater** [mbunkus/mkvtoolnix#1187]
Hi, I'm getting this message right after I open any of the latest version's executable files:

"the procedure entry point regsetkeyvaluew could not be located in the dynamic link library advapi32.dll"

I'm using XP SP3, and previous 7.8 version is working rightly. Did you dropped support for Windows XP?

Regards.

**Comment by sneaker2** [comment]
Yes, Windows XP is not supported anymore.

The author wrote a comment about it here:
http://forum.doom9.org/showpost.php?p=1721161&postcount=3225

**Comment by filler56789** [comment]
IMHO, the actual problem is in insisting on using the Windows Registry. Those 'procedure entry points' which cannot be found in the old version of ADVAPI32.dll are all about dealing with the Registry, apparently. It would be interesting if *at least* the command-line applications themselves (mkvmerge, mkvinfo and mkvextract) could be compiled entirely without any references to the Registry, much like anything that can be »normally« compiled with MinGW-w64.

**Comment by mbunkus** [comment]
I would definitely welcome patches that fix this, but as I don't support Windows XP anymore I will not invest the time myself. Such a contribution would have to replace the use of those functions with equivalent code that works on XP, and it would have to be tested.
