### ISSUE TITLE
New GUI: improve lists of languages

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1200]
Two things to do here:

1. The common languages should not only be listed at the top but also within the full list. This should prove less surprising for users looking for the languages and not realizing that there's such a thing as common languages at the top of the list.
2. There are several entries that refer to dead languages and that will most likely never be used (e.g. »Dutch; Middle (1050-1350)«). These entries should be hidden by default, and there should be an option in the preferences for showing them all for those rare cases in which users actually want to select such a language.

**Comment by remuxer32** [comment]
BTW: I would like to mention that, in my opinion, the »**Undetermined (und)**« entry should be always located (implicitly) as first (with **no** option to change that!) on the list on the left (»**Available**«) and the right side (**»Selected«**); exactly the same like in the old GUI. Why? Well, I don't know like other users, but I always set a video track as »**Undetermined**« [it's logical because video streams do not contain any language (sound)]. So the »**Undetermined**« as first is very comfortable for me and also for other users. Currently I set only two languages on the right side so the »**Undetermined**« is as third on the list, but I'm not (still) satisfied fully because I cannot set the »**Undetermined**« entry as first (I would have to delete those two languages and leave the »**Undetermined**« only). 

Thank you for considering my hint.
