### ISSUE TITLE
Warning before closing modified tabs

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1211]
The chapter editor and merge tool tabs should ask for confirmation before closing them if they've been modified. This also applies to quitting the application.

**Comment by remuxer32** [comment]
Yes, I do agree with you. That's a good idea, definitely. But I would like to mention that, in my humble opinion, users should always have a choice if they want to see such warnings or not. Not everyone likes to see the same warnings every time (especially when quitting the application). In the long term such compulsive messages may be really frustrating for most people. That's why in the »preferences« dialog should be implemented several (or maybe one?) checkboxes with suitable sentences for disabling those warnings. It would be really nice and so »populist«, of course ☺. Note that in the most popular web browsers you can easily decide if you want to enable or disable proper warnings/messages (in particular: quitting the application).

Thanks.

**Comment by remuxer32** [comment]
Thanks for the quick implementation.
