### ISSUE TITLE
output file name not cleared when removing all input files

### ISSUE THREAD

**Issue by lgoncal** [mbunkus/mkvtoolnix#1265]
Using W7 64bit
MKVToolNix 8.0.0.0

When muxing first file auto naming works fine.
After a successful mux I remove files, add a different file, but MKVToolNix does not generate a new name, it uses the old one, overwriting it.

Same issue when adding to job queu, same name persists
Command line for two files in queu

^"C:/Program Files ^(x86^)\MKVToolNix\mkvmerge.exe^" ^"--output^" ^"W:/MKV/CHILDS PLAY 4 SEED OF CHUCKY.mkv^" ^"--language^" ^"0:und^" ^"--language^" ^"1:eng^" ^"--language^" ^"2:eng^" ^"--language^" ^"3:eng^" ^"--language^" ^"4:eng^" ( ^"D:/#/INDIANA JONES 4  THE KINGDOM OF THE CRYSTAL SKULL.mkv^" ) ^"--disable-track-statistics-tags^" ^"--engage^" ^"no_cue_duration^" ^"--engage^" ^"no_cue_relative_position^" ^"--track-order^" ^"0:0,0:1,0:2,0:3,0:4^"

**Comment by bastik-tor** [comment]
@mbunkus Users work in mysterious ways. This bug never occurred to me with the new GUI. #1266 is related.

Here is how to reproduce:

- Open MKVToolNix GUI
- Add source file (The output tab shows ```$filename.mkv```
- Remove the source file
- Add another source file (The output tab shows the same file name from the first input file)

Muxing is not required to trigger it. You have a job, process it, delete all files from it to start over, you end up with the same filename, thus overwriting it.

(I hadn't run into this, because I opened a new job for each file.)

**Comment by mbunkus** [comment]
Thanks for the feedback. I'll fix that in time for the new release.
