### ISSUE TITLE
output file name control always visible in merge settings

### ISSUE THREAD

**Issue by AlanHK** [mbunkus/mkvtoolnix#1266]
After briefly trying mkvtoolnix-gui, a few things seems less convenient than mmg:

*  mmg has an option to clear inputs after you click the "save to job queue" button. It seems I have to manually clear them in the gui

* Output filenames are less logical. mmg would always use the source file as the base name. mkvtoolnix-gui starts with one name and sticks to it for the session.
e.g. I have source "X.mkv", the default filename is "X (1).mkv". 
OK.
I add that to the queue. Then I have to manually remove the source file. 
I add "Y.mkv". The default filename is still "X (1).mkv". 
So now I always have to edit the filename.

* I would prefer to see the output filename on the first tab. I know that logically it's "Output", but I always need to check that (as above) and now I have to click to see it or change it. 

* Also I don't like that the "Properties" collection of options has to scroll (unless you have a gigantic screen, I suppose). I would prefer that it started with a list of headings, and a click on them opened the settings for that option. 
If all the "Properties" were initially collapsed, you could fit all the "Output" options here too. 
I guess most people use a small number of options repeatedly. I use "split" frequently, so I'd like that on the first page, for instance. So ideally the open/closed options would be remembered and be open/closed next time you used it. (If you opened everything, you'd be back to scrolling, of course.)

* "mkvtoolnix-gui" is much longer to type than mmg (!)

**Comment by uNiversaI** [comment]
The mkvtoolnix-gui is far more feature filled but I agree that the same task is unnecessarily long winded due to having to switch tabs for the output (for one).

It would also be nice to have a automatic new file created when using merge to queue several tasks,

Also it would be nice if there were a button to start queue and not have to select entries and right click to start the queue.

I love the new mkvtoolnix-gui but usability wise its not as straight forward as mmg, but ok the price of progress can always be encumbered by the amount of options and the window real estate available.
Im a great fan of K.I.S.S something that seems overlooked in the new mkvtoolnix-gui

**Comment by bastik-tor** [comment]
@AlanHK (I'm not the developer)

1) You were not expected to clear them. Instead you were expected to open a new job for the file you wanted to mux. At least I expect it to be the way it was intended.

2) This is something that is related to #1265 which I think is a bug, because those things can happen due to human error (like picking the wrong file at first) or because people using it in a different way.

3) I had the same feeling when I had the look at the new GUI, but as you say it is logical to have it where it is, so I didn't bring it up.

4) I like the idea of having collapsible elements, maybe with the option which are expanded by default or which aren't like ```Timecodes and default duration```. (I am happy to open another issue for that if it has to be split apart from this one.)

5) mmg has three characters, while the new name is indeed much longer. Removing mmg and renaming the new GUI to mmg could work for you. (just as a workaround)

**Comment by mbunkus** [comment]
Thanks for your feedback.

1. There's already an issue for it (#1254). That option will be implemented in the new GUI, too.
2. There's issue #1265 for this already.
3. I'm still thinking about this. No decision yet.
4. I'm not sure that would be such a big help, but I'll keep it in mind.
5. Seriously? `ln -s mkvtoolnix-gui m`. Or `alias m=mkvtoolnix-gui`. Now it's even two characters less than the old one. I'm sorry, but this kind of complaints don't have any priority for me.

I'll rename this issue to be about the output file name placement inside the GUI as there are other issues for your other points already.
