### ISSUE TITLE
New GUI 8.0.0 : error: "default track" & "forced track" reading parameters of the file

### ISSUE THREAD

**Issue by cirruswazza** [mbunkus/mkvtoolnix#1281]
In "Merge tools" "mkvtoolnix-gui.exe" 8.0.0 not reading parameters from openning file
-> default track
-> forced track
In "Header editor"mkvtoolnix-gui.exe" 8.0.0 not reading parameters from openning file
-> default track
-> forced track

These options works with old gui "mmg.exe"

**Comment by mbunkus** [comment]
Thanks for the report. Will be fixed for 8.1.0 or 8.2.0.

**Comment by mbunkus** [comment]
This is already working well for the »forced track« option in both the merge tool and the header editor:
![merge-forced-flag](https://cloud.githubusercontent.com/assets/414282/8316193/ae80846a-19f5-11e5-8abb-0ebd2bbc3caf.png)
![header-editor-forced-flag](https://cloud.githubusercontent.com/assets/414282/8316198/b4311f0a-19f5-11e5-9b04-e2e70de11e9e.png)

**Comment by mbunkus** [comment]
The »default track« flag is also working fine in the header editor. That the element is often not present in a file is due to Matroska's default values for certain elements. See [this FAQ entry](/mbunkus/mkvtoolnix/wiki/Elements-not-showing-up-in-output-file) for the explanation.

The one remaining point is indeed a bug: the »default track« flag not being read from added Matroska files.
