### ISSUE TITLE
add basic audio/video track properties to track list in merge tool

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1295]
It may help the user to have basic track properties (number of channels, sampling frequency for audio tracks; pixel resolution for video tracks) available in the track list.

**Comment by remuxer32** [comment]
**@Mosu**

Well, well, well...... what we have here! :) I'm really surprised that you've changed your mind and decided to implement one of my gorgeous ideas. Do you remember like I suggested you someday to implement a new column with information about tracks? You said: »MKVToolNix is not MediaInfo and never will be«. Now I'm really glad because of your good choice ☺. It will be absolutely fantastic feature and very helpful for most people. Thank you very much, Mosu.

Now I've got some tips for you that should be considered very deeply:

► What about FPS (Frame rate)? Are you going to add this information? I think you should because it's very, very important. People should know if a video track contains 23.976, 25.000 or 60 fps, and then type a proper value in the field. Please note that similar programs like tsMuxeR & MakeMKV contain such an information.
► What about DTS-HD audio tracks? Will MKVToolnix show only number of channels that belongs to the HD extension or also will show number of channels of the DTS core? Please note that there are movies on BD (e.g. »The Hobbit« trilogy, »Se7en«, etc.) where the HD extension contains eight (7.1) channels, but the DTS core contains six (5.1) channels only. Will MKVToolNix show both of them or only one? And also: »The Lord of the Rings« extended trilogy on BD contains **DTS-HD Master Audio 6.1 with DTS-ES(!) core 6.1** :).
► What about audio bitrate? Will MKVToolNix show it? For example: the constant bitrate for AC3 tracks: 448 or 640 (maximum) kbps or for DTS core: 1509 kbps. For audio tracks with variable bitrate: »unknown«, of course. I know it's not necessary info, but would be nice too see, I think.
► And the last one: compression mode. I mean: a little information if an audio track is **lossless** (DTS-HD MA, Dolby TrueHD, LPCM) or **lossy** (DTS-HD HR, AC3, E-AC3, AAC, plain DTS, DTS-ES, DTS Express etc.). Again: it's not necessary of course, but would be really cool, I think.

Summarizing: I think that the first two points are very important to consider them very thoroughly. 

In order to help you, I've made a screenshot for you, see:  

![track info](https://cloud.githubusercontent.com/assets/10992208/8399018/1c1fd332-1e05-11e5-9e7e-269028292183.png)

As you can see I have typed the most important information for three tracks: video (1) and audio (2). BTW: I had to erase the »Source file« column in order to accommodate my information :). I don't know like you, but I strongly think that the »Source file« column is completely redundant. Why? Because the same information is shown below the »File name« column. What is the sense to duplicate the same info? The only difference is in the name of those columns, but the content is the same, naturally. If I were you, I would remove that (»Source file«) column, but it's up to you, obviously.

BTW 2: maybe a new check box(es) in the »preferences« dialog in order to hide unwanted columns? :D

**Comment by mbunkus** [comment]
I will state it again: MKVToolNix is not MediaInfo and never will be. I won't implement any of your suggestions. Some are simply impossible (e.g. the FPS – there is no such information in Matroska!). I will expose at most that information that is written to the Matroska track headers anyway: number of channels and sampling frequency, pixel resolution.

The »source file« column is far from redundant. It's the only hint where tracks with the same properties actually come from! Especially after changing the track order.

**Comment by remuxer32** [comment]
Ok, now I understand precisely. Thank you for clarification, Mosu. About the »source file« column: personally I don't need to see where tracks with the same properties come from, but I'm able to  understand that there are users who may need such an information. For me: it's »hanger-on«. I mean a free space, of course.
