### ISSUE TITLE
Chapter Editor - Can't save file if Additional modifications screen makes a change

### ISSUE THREAD

**Issue by gsly** [mbunkus/mkvtoolnix#1325]
Seen in version 8.1.0 64-bit Windows 8.1.  To re-create bug:
1. Open MKV in Edit Chapters tab
2. Select "Edition Entry" and right-click, select "Additional modifications"
3. Select "Set chapter names' languages" and change from Und to English
4. "Save" on the Chapters Menu is greyed out and you can't save, but you've changed the attributes!
5. If you click any other tab and come back to Edit Chapters, Save is now enabled.

**Comment by mbunkus** [comment]
Thanks for the report. I'm pretty sure you're running into #1312 as the underlying cause. This has already been fixed. Please give [one of the latest pre-builds for Windows](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) a try; they contain the fix.

I'll close this issue for the time being. If your issue turns out not to be fixed by the pre-builds then please post here and I'll re-open it.
