### ISSUE TITLE
Character Set

### ISSUE THREAD

**Issue by pokeguru87** [mbunkus/mkvtoolnix#1331]
I'm not sure if this would be a bug or a feature request. When adding subtitle files or a chapter file to a video it would be nice if it took the encoding from the file that is added. For example, adding a Subtitle file with a UTF-8 encoding currently adds as whatever value is in the settings, when it would be more preferable to take on the encoding of the file. Since a default encoding is already a setting, this would be an extra option.

What prompted this, was a merged a video with a SSA subtitle file that contained Kanji. The subtitle file had an encoding of UTF-8, but the tool had it set to ISO-8859-15. When playing the file the Kanji did not show proper despite the font being attached. I checked the encoding of the subtitle file and then changed it in the GUI and re-merged the files. It then play properly. I then dug into the settings and noticed the Character Set setting. For me setting it to UTF-8 will work since all of mine is this, but I feel it would be more intuitive if it took on the source file's encoding.

**Comment by mbunkus** [comment]
Thanks for the feedback. First, there's a setting called »Default subtitle charset to set« in the preferences. When you add a subtitle track the GUI will set the track's character set to the one selected in the preferences if there is one selected. Unfortunately release 8.1.0 contains a bug that it's not possible NOT to select a character set in the preferences: an empty entry is missing. Therefore you're currently forced to have one selected. This is not intended and has already been fixed.

The intentional behavior is to be predictable. How mkvmerge and the GUIs treat character sets is described [here](https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvmerge.html#mkvmerge.text_files_and_charsets). Meaning that if you're running e.g. a German Windows then the character set mkvmerge expects by default is Windows-1252 etc.

The problem with automatic detection of a character set used by text files is that it's inherently impossible to get right 100% of the time. See e.g. the [Wikipedia entry for Windows-1252](https://en.wikipedia.org/wiki/Windows-1252), especially the problems mentioned in the section »Details«. I want my tools to act predictable and reliable – and automatic detection is neither. Therefore I will not implement such a feature.

Note that text files encoded in one of the UTF variants are detected automatically if they contain a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark).
