### ISSUE TITLE
Version 8.1.0.0 mkvpropedit "open file error"

### ISSUE THREAD

**Issue by BelowZeroLH** [mbunkus/mkvtoolnix#1341]
No matter where I put a file on my machine using Windows 8.1 x64 I get an "open file error". I tried putting it on a separate USB hard drive, various folders, and even setting the security for the folder that contains the exe/mkv file for EVERYONE to FULL ACCESS. I am at a loss. MKVMERGE does not seem to suffer this problem at all.

This is a sample of the command line:

mkvpropedit.exe z.mkv --delete-attachment "1" --delete-attachment "2" --delete-attachment "3" --delete-attachment "4" --delete-attachment "5" --delete-attachment "6"

and this is its full output:

The file is being analyzed.
Error: The file 'z.mkv' could not be opened for reading and writing, or a read/write operation on it failed: open file error.

I did the same thing on Windows 7 x64 and it worked flawlessly.

Help??

**Comment by mbunkus** [comment]
Thanks for the report. I cannot reproduce such an issue with two or three random files. It's likely due to something specific with the file you're using.

Did you actually test the very same file on Windows 7? Does the same action work on Windows 8 with another file, e.g. one newly created by mkvmerge?

Can you please upload the file you're having trouble with to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can take a look at it? Thanks.

**Comment by BelowZeroLH** [comment]
My bad. These files came from another computer and there was no reason for the ReadOnly bit to be set on the files, but it was! I can't believe I goofed like that! Sorry about the unnecessary report.

**Comment by mbunkus** [comment]
No problem at all. Glad you've figured it out.
