### ISSUE TITLE
Chapters not correct after append

### ISSUE THREAD

**Issue by tamorgen** [mbunkus/mkvtoolnix#1348]
I'm having issues merging/appending two mkv files, and I'm unsure what I am doing incorrectly.  I've extracted my Blu-Ray copies of LOTR Extended Edition to mkv using MakeMKV.  Unfortunatley, the movies are so long that WB split them onto two Blurays each for the extended edition.  I want to merge the two discs into one MKV file for viewing on my HTPC.

Process I'm using:

Latest mkvtoolnix 8.x (something, not in front of that computer at the moment)
Load the first MKV file
Right click on that file, select append.
Load the second MKV file
mux the two files

My end result is a file about 60 GB, but only about 20 chapters, and the subtitle tracks are gone.  It should have around 40 chapters or more, and multiple subtitle tracks.

Any assistance would be appreciated.

**Comment by mbunkus** [comment]
Can you please past the command line that the GUI reports right before you mux? Re-create the mux settings like you did but don't start yet, instead select »show command line« from the »merging« menu. Paste that here. Then mux the files again and check whether or not the result contains subtitle tracks.

A screenshot of the file and track lists right before muxing would also be nice; make sure to include as much  as possible by resizing the GUI, please.

**Comment by tamorgen** [comment]
^"C:/Program Files ^(x86^)\MKVToolNix\mkvmerge.exe^" ^"--output^" ^"//hda/Bluray/Lord of the Rings - The Return of the King Extended Edition/Lord of the Rings - Fellowship of the Ring Extended Edition Part 1.mkv^" ^"--language^" ^"0:eng^" ^"--language^" ^"1:eng^" ^"--track-name^" ^"1:Surround 6.1^" ^"--default-track^" ^"1:yes^" ^"--language^" ^"2:eng^" ^"--track-name^" ^"2:Surround 5.1^" ^"--language^" ^"3:eng^" ^"--track-name^" ^"3:Stereo^" ^"--language^" ^"4:eng^" ^"--track-name^" ^"4:Stereo^" ^"--language^" ^"5:eng^" ^"--track-name^" ^"5:Stereo^" ^"--language^" ^"6:eng^" ^"--track-name^" ^"6:Stereo^" ^"--language^" ^"7:eng^" ^"--language^" ^"8:eng^" ^"--language^" ^"9:eng^" ^"--language^" ^"10:eng^" ^"--language^" ^"11:eng^" ( ^"//hda/Bluray/Lord of the Rings - Fellowship of the Ring Extended Edition/Lord of the Rings - Fellowship of the Ring Extended Edition Part 1.mkv^" ) ^"+^" ( ^"//hda/Bluray/Lord of the Rings - Fellowship of the Ring Extended Edition/Lord of the Rings - Fellowship of the Ring Extended Edition Part 2.mkv^" ) ^"--title^" ^"THE LORD OF THE RINGS: THE FELLOWSHIP OF THE RING ^(EXT.^) PT. 1^" ^"--track-order^" ^"0:0,0:1,0:2,0:3,0:4,0:5,0:6,0:7,0:8,0:9,0:10,0:11^" ^"--append-to^" ^"1:0:0:0,1:1:0:1,1:2:0:2,1:3:0:7,1:4:0:8,1:5:0:9,1:6:0:10,1:7:0:11^"

**Comment by tamorgen** [comment]
Sorry, lots of options in that output.  Hope you can read it!

**Comment by mbunkus** [comment]
That's fine, thanks. What about a screenshot? And how did determine that the output file doesn't contain any subtitle tracks?

**Comment by tamorgen** [comment]
Screenshot attached.

In regards to the subtitle output, when I go to the drop down for subtitles in Total Media Theatre 6, which is what plays my files from WMC, no tracks appear.  Five tracks appear in the split files.

Also, for whatever reason, the combined file will not play in VLC.  It will in TMT6.  But only 20 chapters are appearing, when there should be 48.  All chapters appear in the split files, and again, individually they play in VLC.

Thanks for looking at this.  Let me know if you need anything else.

![merge screenshot](https://cloud.githubusercontent.com/assets/13274413/8628435/04afa3f6-2721-11e5-8579-6f78f8a46df2.png)

**Comment by mbunkus** [comment]
Thanks.

About the subtitles: I'm pretty sure that they're actually present in the output file. You can check by adding the muxed file (the 60 GB one) to new merge settings in the GUI and see whether or not there are subtitle tracks present (or you can open the file in the GUI's header editor). Just because your hardware device doesn't show them doesn't mean they're not present – a lot of hardware devices are known to have very rudimentary support for Matroska that can fail for a wide variety of reasons.

Adding the file to new merge settings will also show you how many chapter entries there are in that file.

About the chapters: My guess is that both chapter files use the same chapter/edition UIDs, and mkvmerge treats entries with the same UIDs as the same entries discarding the ones from the second file. This is in accordance to the specs and a well-known issue with MakeMKV which uses sequential numbering for chapters resulting in issues like the ones you're describing. The fault is MakeMKV, it should use unique chapter numbers (any random 64bit number would do as long as they're not simply sequential… using 1, 2, 3… in all chapters is just looking for trouble). See #1097 for the explanation.

About VLC: well, that's something that should be reported to the VLC developers.

**Comment by tamorgen** [comment]
Okay, you are correct on the subtitles.  They do appear to be there when I add merged file by itself.

In regards to the chapter/edition UIDs, they appear to be different.  At least the Edition IDs are different for each disk.  The ChapterUIDs seem pretty random as well.

Does the merge tool change the ChapterString and Start/End times for the second file when appending?  I don't have to do that manually, do I?

**Comment by tamorgen** [comment]
![screenshot 2015-07-10 17 08 05](https://cloud.githubusercontent.com/assets/13274413/8629107/69afe4f0-2726-11e5-89ab-9b5f0b2ac134.png)

**Comment by tamorgen** [comment]
Answered my own question... Does not reset it the chapter numbers

![screenshot 2015-07-10 17 09 55](https://cloud.githubusercontent.com/assets/13274413/8629136/b56e9724-2726-11e5-908b-eb9d7587d336.png)

**Comment by tamorgen** [comment]
So, I'm not sure if this has anything to do with my issue, but I'm getting a "File parsing failed" error when I try to edit the file headers....
![screenshot 2015-07-10 17 20 46](https://cloud.githubusercontent.com/assets/13274413/8629313/27c97edc-2728-11e5-9560-ecd2618c5b42.png)

**Comment by mbunkus** [comment]
Thanks for those screenshots. The UIDs are indeed unique, so that's not the issue here.

The chapters in a Matroska file are not really numbered. Instead of chapter entry has a textual description. This description is often auto-generated by numbering the chapters. However, when appending files mkvmerge does not touch those textual descriptions at all.

My guess is that your hardware player thinks that chapters with identical names are indeed identical chapters. This would be a bug in your player. You can try to change the descriptions in the GUI's chapter editor and save them back to huge file and see if that changes anything, but be aware that a lot of players have problems with Matroska files with a certain layout, and those can be triggered by writing chapters back to Matroska files. See [here](/mbunkus/mkvtoolnix/wiki/All-tracks-vanished-after-mkvpropedit,-the-header-or-chapter-editors) for details.

So what you should give a try is editing the chapters in the file you want to append and rename the entries to something that will be unique when you append them (mkvmerge doesn't have a problem with the aforementioned layout thingy). Then save the chapters back to the Matroska file to be appended. Next repeat your merging with the original first and the modified appended file. Afterwards the resulting file should contain 48 uniquely named chapter entries, and hopefully your player will display them all.

As for the subtitle tracks: I cannot really help you with that, I'm afraid. You should look over my general [troubleshooting advice for players with bad Matroska implementations](/mbunkus/mkvtoolnix/wiki/Improving-playback-compatibility-with-players).

About the file header parsing error: huh, that's interesting… I haven't been able to reproduce such a problem, unfortunately, and it's kind of hard to figure out what's wrong without having a file for which the issue happens. It's especially puzzling as the same file parsing routines used in the header editor are used in the chapter editor as well, and as your screenshot shows the chapter editor was able to load the chapters from the file just fine.

Did you have the file open in another application (e.g. a video player) at the time you tried to open it in the header editor?

**Comment by bastik-tor** [comment]
@mbunkus You write the cause, but fail to realize it.

> About the file header parsing error: huh, that's interesting… [...] It's especially puzzling as the same file parsing routines used in the header editor are used in the chapter editor as well, and as your screenshot shows the chapter editor was able to load the chapters from the file just fine.

The file is opened in the chapter editor (first), it doesn't get closed; then it is opened in the header editor, which leads to the parsing error because the file is already open.

I can reproduce this on Win7 64bit and 8.1.0

Please note that the order matters, first goes chapter editor, then header editor to trigger this message. (The other way around, header editor first, then chapter editor, works for me.)

**Comment by mbunkus** [comment]
Ah, thanks for the analysis. I'll look into it.

**Comment by mbunkus** [comment]
I've fixed that chapter/header editor »file could not be parsed« issue.

I'm still pretty sure that the other things reported by @tamorgen aren't really bugs in MKVToolNix as I've explained above. I'll await his/her feedback on muxing with renamed chapters, then I'll close as invalid if the player shows all chapters.

**Comment by mbunkus** [comment]
I've just implemented a function for renumbering existing chapter entries that could make cases such as this one much easier. See #1355. It'll be part of the upcoming release 8.2.0.

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
