### ISSUE TITLE
Qt not a requirement, but needed for the new GUI

### ISSUE THREAD

**Issue by Jiehong** [mbunkus/mkvtoolnix#1354]
Hello,

With version 8.1.0 on Archlinux, a warning telling me about a new gui, and the old is now deprecated, but I couldn't find any binary for the new gui.

I came over here, and looked at the code, just to find that the new GUI depends on QT instead of GTK, but:

- it is not in the requirement list in the README;
- it is not built by default.

A bug has been opened on Archlinux to follow this issue on our side (https://bugs.archlinux.org/task/45439), but it would have been wise to force the binary to be built if it's deprecated now.

**Comment by mbunkus** [comment]
Neither of the GUIs is build if the corresponding toolkit is not installed. Not requiring the toolkits to be present is actually intentional as that allows the tools to be built without requiring X. I will add Qt to the README's list of optional dependencies, though.

The new GUI is built by default if Qt can be found, no configure switches needed. See the explanation [in the release notes of 7.9.0](https://www.bunkus.org/blog/2015/05/mkvtoolnix-v7-9-0-released/) for more details on configure's switches regarding the GUIs.

**Comment by Jiehong** [comment]
Thanks
