### ISSUE TITLE
mkvpropedit v8.2.0 is broken (runtime error when adding attachments)

### ISSUE THREAD

**Issue by r0lZ** [mbunkus/mkvtoolnix#1371]
Mkvpropedit can't add attachments to a MKV file any more.  Bug with all attachments I've tried so far (jpeg and text files).

Example:
> mkvpropedit.exe "movie.mkv" --add-attachment "small_cover.jpg"
The file is being analyzed.
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

I've tried with old versions I had here (v7.4.0 and v7.6.0) and the same MKV file and attachments, and there is no problem.  Therefore, mkvpropedit is broken in recent versions only (perhaps since v8, I don't know).

**Comment by mbunkus** [comment]
Thanks for the report. I cannot reproduce such a problem here, neither with the 32bit nor the 64bit version, neither on Windows nor on Linux. It could be related to one of two things:

1. A magic file from a prior version of MKVToolNix. Please check the size of the file `…\mkvtoolnix\data\magic.mgc`. Its size should be 3865992 bytes big and have an SHA1 checksum of `c92c26ccfc50a3cdd56cd33d7d8d70a293c26ef1`.
2. The Matroska file you've tried to modify may be the trigger. In that case I'd need access to a file for which the crash happens. If you still have a file then please upload it together with the attachments you were trying to add to it to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can investigate further. Thanks.

**Comment by r0lZ** [comment]
Thanks for your quick reply.

My magic.mgc file is correct but I have used a copy of the mkvpropedit.exe
file that was not in the mkvtoolnix installation folder.  And my mkvtoolnix
directory has been extracted from the portable distrib, and not installed
by the installer.  Therefore, mkvpropedit.exe was probably unable to find
the data directory and the magic file and crashed.  Perhaps you should add
an error message if the magic file cannot be opened? Anyway, the problem is
solved.

However, I wonder why the old versions (v7+) worked perfectly without that
data directory, and why it is necessary to check the magic file now.

I need mkvpropedit and mkvmerge for my BD3D2MK3D
<http://forum.doom9.org/showthread.php?p=1685518> GUI, and that two exes
are distributed in the toolset directory with the main app.  All versions
have always worked fine so far, and as far as I know, it's still the case
of MkvMerge.  I have just made a quick test and it appears that the latest
mkvpropedit works also from that toolset dir if I include data/magic.mgc
too.  Can you tell me if it's sufficient to avoid all problems, or if there
are other files that must be included as well?

Oh, of course, I hope that I can freely distribute that two files (along
with the html pages of the English doc and a link to the mkvtoolnix site)
with my program.  It is totally free if that matters.

Sorry for the trouble.  You can mark the bug report as solved anyway.

Thanks again,
r0lZ

**Comment by mbunkus** [comment]
That the programs crash is due to the libmagic library. The reason this started to happen with newer releases is that I've updated my build environment for Windows a while ago, and libmagic seems to have been updated as well.

The bug itself is in libmagic, and I don't want to work around bugs in other libraries (it's a losing game). I do update libraries from time to time, of course.

Anyway. The `magic.mgc` file should be all you need. All other files (e.g. translations, documentation etc.) are optional, and I know for a fact that missing translation files don't crash gettext ;)

Re-distributing GPLed binaries is fine, of course, as long as you follow the GPLv2 rules. This usually means distributing the [source code as well](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#UnchangedJustBinary), but I (and a lot of other people) are usually satisfied if the original `README.md` file is included as the `README.md` states where to get the source code. It's fine to rename `README.md` slightly to make it obvious that it applies to mkvmerge.exe, e.g. `README.mkvmerge_and_mkvpropedit.md`. Another possibility is storing the parts taken from MKVToolNix (the two exes, the `README.md` and the magic file) in a sub-folder without renaming anything.

**Comment by r0lZ** [comment]
OK, thanks for the info.

I did not know the README.md requirement.  I have just added it in the
toolset directory of my GUI, and it will be distributed with the next
update.

Thanks!
