### ISSUE TITLE
TrueHD+AC3

### ISSUE THREAD

**Issue by bumblebritches57** [mbunkus/mkvtoolnix#1377]
According to this page: https://github.com/mbunkus/mkvtoolnix/wiki/TrueHD-and-AC3#how-does-mkvmerge-handle-truehd-tracks-with-embedded-ac3-data

You say you have to remove AC3 for non-technical reasons, but if that's the case you couldn't support DTS-HD either...

**Comment by mbunkus** [comment]
The situation with DTS-HD is fundamentally different. With AC3+TrueHD each of the two codecs contain all information needed for decoding. You do not need to keep the AC3 part in order to decode the TrueHD part and vice versa. Therefore both can be and are considered to be full tracks in the context of Matroska.

With DTS-HD you generally need the DTS core if you want to decode the HD extensions. Therefore they are only one logical track.
