### ISSUE TITLE
Merge tool feature request: create new merge settings for each dropped file

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1380]
According to the comment from Mosu's blog: https://www.bunkus.org/blog/2015/07/mkvtoolnix-v8-2-0-released/#comment-25029

I also agree that it would be great to allow users to open an each dropped file (e.g if someone adds 20 files at the same time) in separate (20) tabs. Such an option is definitely a time saver for me and other users. 

Thank you very much.

**Comment by elgonzo** [comment]
I would suggest to offer a command line option for this. MkvToolNix-GUI has a --merge option already. Right now the --merge option adds the files following that option to the currently active job (assuming a job already exists in MkvToolNix-GUI).

How about altering the operation of the --merge option -- or perhaps introduce a new command line option -- so that it enforces creating a new job? Some example of the behavior of the command line options :

`MkvToolNix-GUI 1.mkv 2.mkv`
Appends the files 1.mkv and 2.mkv to the current merge job (job is being created if none exists).

`MkvToolNix-GUI --merge 1.mkv 2.mkv`
Creates a new merge job with 1.mkv and 2.mkv.

`MkvToolNix-GUI --merge 1.mkv 2.mkv --merge 3.mkv 4.mkv`
Creates a new merge job with files 1.mkv and 2.mkv, and also creates another merge job with 3.mkv and 4.mkv.

I am not sure how you are going to address the issue with MkvToolNix-GUI popping into the foreground or staying in the background/minimized when command line arguments are provided.
From my perspective, i can see different user desires when a merge job (or a job in one of the other editors) is being created or updated.

Some users probably want to keep MkvToolNix-GUI staying in the background, as they intend to build their merge jobs successively, and whenever they drop a number of files onto the desktop shortcut or program icon of MkvToolNix-GUI they might find it annoying when MkvToolNix-GUI pops into the foreground.

Some other users would like to have MkvToolNix-GUI come to the foreground if they created or updated jobs through the command line, as they want to adjust some job settings and/or run the jobs immediately.

Hence, i would find it a good idea if there would also be a "--to-foreground" option added that lets the user choose the behavior according to his liking. (Let me know if you want this tracked as another feature request, and i will copy&paste it into a new issue.)

**Comment by mbunkus** [comment]
No, that's definitely not what I will do. There's a dialog already asking the user what to do with the dropped files. You may not be aware of that dialog as it is disabled by default (a lot of users disliked it), but it can be enabled in the preferences (»Merging« → uncheck »always add dropped files from external sources«). Then drag & drop files onto a job that already includes at least one file, and you'll see what I mean.

I will add a new option in said dialog. That way the user actually has a choice.

Command line options are nice and I'm all for them (mkvmerge is a cli-only application, after all, and the GUI just drives its execution), but not for the general Windows user.

**Comment by elgonzo** [comment]
Ah, okay. Sorry, i was not aware of this dialog. You are right, given this dialog my request is rather superfluous. :)

I did a quick test with this dialog, but i can't seem to make the choice "Create new merge settings and add to those" permanent, but MkvToolNix-GUI will nag me every time. Interestingly there is a "don't ask again" option for "Always add as new input files", but not for "Create new merge settings". Did i miss something or would this be a feature request?

**Comment by mbunkus** [comment]
The »always add as new input files« option is how the old GUI worked, and it is something that I consider useful for the general public.

However, are you sure you would actually want to have dropped files always be added to new settings? What if you forgot one file and would like to add it to the settings just created? I don't see the general usefulness of »always create new merge settings«, therefore I will most likely not implement such an option.

**Comment by elgonzo** [comment]
Ah, sorry. I was indeed not aware about that dialog. You are right, given this dialog my suggestion is rather superfluous. :)

With regard to the new dialog option i did assume you meant making a user choice permanent so the dialog doesn't ask again. I guess i will wait and see how it will turn out in an upcoming MkvToolNix release.

With regard to the usefulness of making "Always create new merge settings" permanent, well, that would cater to my preferred workflow. Essentially i work with Total Commander, collecting files jobs in a folder, select the files for a job and click on a toolbar button in TC (which i have configured to start the MkvToolNixGUI). Currently i have only these 3 choices: Either endure the dialog you mentioned every time, create manually a new job in MkvToolNix-GUI, or exit MkvToolNix-GUI before using the toolbar button in TC. On the other hand, i do not use MkvToolNix-GUI daily and this little inconvenience probably does not justify me pushing for such a feature, so i should not become a drama queen. :)

Anyway, a huge Thank You for your ultra-fast responses, and for the always excellent work you so with MkvToolNix. Much appreciated!

**Comment by mbunkus** [comment]
I see your point. Please open a new issue for it. I will likely implement that somehow, but not for the next release.

**Comment by elgonzo** [comment]
[https://github.com/mbunkus/mkvtoolnix/issues/1388](Feature request made)
