### ISSUE TITLE
Progress percent number shows halve value

### ISSUE THREAD

**Issue by rkolless** [mbunkus/mkvtoolnix#1385]
Hi,

the new version 8.2.0 of mkvmerge shows a progress number halve the value it really is.
The progress number goes from 0..50% and jumps after finish to 100%.

A side effect of this is that the MKVToolnixGui calculates a wrong remaining time until completion.

**Comment by mbunkus** [comment]
Thanks for the report. I haven't had such a report before, and I cannot reproduce it at the moment.

Just to make sure you're not confused by something that actually works as intended: the GUI has two progress indicators in its status bar, one for the currently running job and one for the whole job queue:

![progress-indicators](https://cloud.githubusercontent.com/assets/414282/9131809/2e988226-3cef-11e5-9a9f-2e90568686cb.png)

Which one of those two jumps like that?

The one for the whole job queue (the right one) takes all jobs into account that are either currently running (there can only be one of those at any given moment) and those »pending automatic start«. The total duration is estimated based on the queue's start time, the total percentage processed (number of completed jobs * 100 + current job's percentage).

If, for example, there is one long-running job and one job pending automatic start then the left progress indicator will reach 100% when the right one reaches 50%. If, though, the second one finishes almost immediately (e.g. due to an error or the files to be muxed being very short) then the second indicator may seem to jump from 50% directly to 100% without an obvious reason. This would be a design limitation, though, as there's no way to estimate how long a job will take until it's actually running.

**Comment by rkolless** [comment]
I work with the command line tool mkvmerge most of the time and the written percent number shows the halve value for one job. Using the Gui I can only see that the approx. time to finish the job is always doubled. Until now I did not even notice the progress bar :)

**Comment by mbunkus** [comment]
Uhm… interesting :) This is not a general issue. For me mkvmerge's progress increases smoothly from 0 to 100 through most of the numbers (for huge files, anyway), no big jumps.

So it looks like to depend on the file(s) in question. Can you please upload a set of files for which this happens to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server)? Thanks.

**Comment by rkolless** [comment]
I just made a cross check with some m2ts and on single m2ts files the progress bar shows the correct value 0..100.
Using a mpls where the first m2ts in the playlist is big (4 GB) and the second is very small (256 kb) the progress number seems to be halved but actually it is divided between the numbers of m2ts in the mpls. Using three m2ts in a mpls (4 GB, 256 KB, 256 KB) results into a "visual" count of the progress number from 0..33 and then suddenly to 100%.
Using two m2ts files with the same size gives a correct progress counting.
Should I upload you a mpls or do you need some m2ts? I created some blind m2ts files for it.

**Comment by mbunkus** [comment]
Ah, MPLS with a tiny last part. No need to upload. Unfortunately this is something that would take a considerable amount of effort to fix due to how mkvmerge works internally. I will not invest that time.

Thanks for the timely replies.
