### ISSUE TITLE
The GUI Chinese Simplified translation is not correct

### ISSUE THREAD

**Issue by Neroldy** [mbunkus/mkvtoolnix#1399]
In the 8.3.0, the GUI Chinese Simplified translation is not 'correct', it seems like just converted from Chinese Traditional translation. So that some words are strange. The 8.2.0 is correct.
mmg chs 8.3.0
http://www.imagebam.com/image/7bd966429329328
mmg cht 8.3.0
http://www.imagebam.com/image/75ad54429329334
mmg chs 8.2.0
http://www.imagebam.com/image/fdb4ae429329565

This issue is also occured in the new GUI.
mkvtoolnix-gui 8.3.0 chs
http://www.imagebam.com/image/363b33429330283

**Comment by mbunkus** [comment]
Thanks for the report. The only update to the Chinese Simplified translation since release 8.2.0 apart from me adding untranslated strings was this commit: 94e8d1412885cce64b51f6881f19eabd297d8411. Can you please take a look at the changes in the commit and tell me whether or not this is the cause of the breakage? If so I'll revert it.

As I don't speak Chinese myself I cannot judge the quality of the translation people send me. Therefore it's not surprising that something like this has happened.

**Comment by Neroldy** [comment]
Thanks for your reply!
I checked the commit `94e8d14`, and also compared the translation file `zh_CN.po` between the v8.2.0 and v8.3.0, the commit `94e8d14` is reason of this translation issue.

P.S: mkvtoolnix is a great tool, thank you, mbunkus !

**Comment by mbunkus** [comment]
Thanks for testing it. I'll revert the changes in a moment.

You can use corresponding translation file from the 8.2.0 release with 8.3.0 until 8.4.0 is out.
