### ISSUE TITLE
Make mkvmerge take a 'seed'

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1407]
There is the use-case of having byte-identical files and that is something that is not supported and won't be. There are ways to do that. Having those files seems relevant if they should be shared via a system that makes use of a file hash or if the file should be signed and the signature be valid for all those file even if others have created them.

The thing that seems to be relevant for playback would be the UIDs. For use-cases that rely on having the same UIDs while there can be differences at the byte-level it would be nice to have mkvmerge take a seed.

When the same seed is used mkvmerge calculates the same UIDs. The users would be responsible for ensuring that the seed is unique.

It seems a lot easier to agree on a seed than to agree on UIDs and apply them correctly to the file.

**Comment by mbunkus** [comment]
Thanks for the suggestion.

Of course there are ways to do that, but it wouldn't be limited to such a seed. More elements like e.g. the muxing date aren't changeable at the moment. I simply don't want to have to support such a use case, especially as distributing the files needed in order to create a Matroska file and the instructions how to do it exactly (which files, which order, options used, MKVToolNix version…) amounts to a lot more effort than simply distributing the Matroska file in the first place.

If you do want identical files I suggest using tools like rsync on top of mkvmerge.

= No, I won't implement such a feature. Sorry.

**Comment by bastik-tor** [comment]
The idea with the seed is older, back from when I also thought about having identical files. I dropped the idea of the seed back then. Now I thought it would be at least possible to have it apply to elements that are required for proper playback.

Indeed, it can be messy, so I understand that this is something that is not done.

To be honest it was just posted because I was asking for the other thing, which I thought could have a very high likelihood of being dismissed as well, because of probably having to consider return values as things could go wrong otherwise.
