### ISSUE TITLE
Merging multiple disc blurays into a single large file

### ISSUE THREAD

**Issue by mauerman** [mbunkus/mkvtoolnix#1428]
Hello

I wrote some time ago concerning The Lord of The Rings Extended editions, because they were very large, and on multiple discs, so you said I needed to use bdinfo and tsmuxer to identify the correct mpls file, and then remux that.

It worked on other discs, but as The Lord of The Rings is a special 2 disc edition, the movie is spread out over these 2 discs, and therefore when reading the mpls files, they pertain to the disc they come from, and only that one.

I have tried using append in mkvmerge, to make them become a single file, but it doesn't work.

How do I use the programs at my disposal to create one 70 gb movie file, instead of 2 35 gb movies files?

Regards,

Mauerman

**Comment by mbunkus** [comment]
The append feature is exactly what you need to use. However, appending has its limitations, first and foremost that the same encoding settings had to be used to each pair of appended tracks. Otherwise playing an appended track will work for the first half but will be garbled/impossible for the second half. This is often the case for h.264 tracks, especially if they come from different discs.

What is the actual error message you get when appending the second MPLS to the first one?

**Comment by mauerman** [comment]
Just to be sure, you're saying that I can remux with mkvmerge using the
mpls files?
I don't have to use tsmuxer to create m2ts files first?

2015-09-13 8:06 GMT+02:00 Moritz Bunkus <notifications@github.com>:

**Comment by mbunkus** [comment]
That's correct. That's supported and preferred since v6.1.0. Not using the MPLS is often wrong as many discs use MPLS to only play certain parts of M2TS files and that information is simply not contained in the M2TS files themselves.

Additionally the MPLS files can contain chapter information which is also read if present.

Just try adding one MPLS file to the GUI and see what happens.

**Comment by mauerman** [comment]
Hello

It works perfectly.

I added the first mpls file, and then appended the second one.

The file is not corrupted in any way, and the entire length of the movie is
there :)

Thank you!

2015-09-14 16:30 GMT+02:00 Moritz Bunkus <notifications@github.com>:

**Comment by mauerman** [comment]
I have another problem with some other discs.

There are some in-movie menus, that when you play the movies on a bluray
player, you can choose to make them pop up in the movie, while it is
playing, using the bluray remote, and make them go away again.
But now that I have remuxed them, the menus are there with no option of
removing them from the mkv file.
Is there a specific track that I need to remove, before I remux, to remove
this infomenu completely?

2015-09-14 23:54 GMT+02:00 Magnus Jønsson <magnusjoensson1308@gmail.com>:

**Comment by mbunkus** [comment]
Menus are not supported. If there are separate video tracks for such content then yes, you'll have to deselect them manually as mkvmerge has no way of recognizing them as such.
