### ISSUE TITLE
error when muxing: no translation available for ''

### ISSUE THREAD

**Issue by terve** [mbunkus/mkvtoolnix#1434]
I have the latest GUI 8.4 and try to change an mp4 file to mkv but get an error when I start muxing:

--- Errors emitted by job 'merging to file »Citizenfour.2014.1080p.BluRay.x264.YIFY.mkv« in directory »D:/Videos«' started on 2015-09-20 18:29:16 ---
There is no translation available for ''.

The old mkv merge GUI works well but isn't any more available with the 8.4.
So where is the problem?

**Comment by mbunkus** [comment]
Looks like the settings in mkvtoolnix-gui.ini regarding the interface language were somehow set to an empty string. I don't have an idea how that could happen.

In order to fix this you should have two options:

1. Open the preferences, select your desired translation and close the preferences again.
2. Alternatively quit the GUI, open the settings file [mkvtoolnix-gui.ini](/mbunkus/mkvtoolnix/wiki/Settings-location) and remove the line with `uiLocale=…` in the `[settings]` settings. Then start the GUI again.

Both methods should fix the issue.

**Comment by mbunkus** [comment]
I've uploaded [new pre-builds](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/). Build numbers 914, 915 contain the fix.
