### ISSUE TITLE
"Location is not available" error/prompt

### ISSUE THREAD

**Issue by EvanVanVan** [mbunkus/mkvtoolnix#1438]
I use MKVToolNix to clean up my files and remove unwanted tracks before storing them in a different location.  Therefore, every time I open up MKVToolNix and try to add a new file I get the attached "Location is not available" error.  It's particularly annoying because it doesn't "grab focus," so I can't just hit esc to close it.  I have to actually find my mouse, move it to the prompt, and hit OK.  (Although it is preferable to MKVMerge, which use to lock the entire screen until the prompt was closed.)

Is there a cleaner way of handling this?  It would be nicer if instead of throwing an error, it opened the next available folder "up" from that missing directory (like the way Windows handles it).  

Or another idea, a setting for a "Default file open location," which would be a top-level directory, but it would be separate from the save the output file in the "Same directory as the first input file" setting.

To reproduce (in the shortest number of steps, not an actual use case):
1. Open a file in MKVToolNix
2. Delete the file and entire containing folder.
3. Attempt to "Add files."
4. Receive error.

Thanks

**Comment by mbunkus** [comment]
To be honest I cannot reproduce this issue at the moment. I've tried the following:

1. Created a folder, e.g. `C:\temp\input`, and put an AVI into it
2. In the GUI chose »add files«, navigated to the newly created folder and selected the AVI.
3. Removed the folder `C:\temp\input` again in a file manager
4. In the GUI chose »add files«

At that point there's no error message at all. All that happens is that the initial location is my user's documents folder instead of `C:\temp`.

So two questions:

1. What's your Windows version?
2. Which version of MKVToolNix were you using?

**Comment by EvanVanVan** [comment]
"All that happens is that the initial location is my user's documents folder instead of C:\temp."

Following your example I got the same results (no error and it restarted in my user's documents folder).

Please try again but create the folder `temp\input` folder in 'C:\Users\user\Documents', that results in the error.

I'm using MKVToolnix 8.4.0 on Windows 7.

**Comment by mbunkus** [comment]
I still cannot reproduce it:

* Created `C:\Users\mosu\Documents\temp\input`
* Copied an AVI to that folder
* Started the GUI
* "Add files", click on the "Documents" link in the quick access panel thingy on the left so that the location shows "This PC > Documents", from there clicked through to `temp\input` and selected the AVI
* Removed the folder `C:\Users\mosu\Documents\temp` including all of its contents
* In the GUI: "Add files" again

No error message, the file dialog is initially set to my Documents folder.

Maybe it's a Windows 7 thing…

**Comment by mbunkus** [comment]
Yeah, I can reproduce it on Windows 7.

**Comment by EvanVanVan** [comment]
Awesome, thanks.

**Comment by EvanVanVan** [comment]
(For fixing it)

**Comment by mbunkus** [comment]
You're welcome. I've created [pre-build 968](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/32bit/) for you to test.

**Comment by EvanVanVan** [comment]
Just had a chance to try it, works great.  Thanks.  It should be rolled into a 64 bit version in the next few days?

**Comment by mbunkus** [comment]
It's just a matter of creating a new package; meaning the next time I create a 64bit pre-build it'll contain the fix. I often only build 32bit pre-builds for people to test with as those work for everyone no matter if their Windows is a 32bit or 64bit one and it's quicker than building both variants.

Anyway, I've just uploaded a new 64bit pre-build.
