### ISSUE TITLE
Error with locale in mkvtoolnix-gui

### ISSUE THREAD

**Issue by marillat** [mbunkus/mkvtoolnix#1460]
Hi,
If a locale is set to C, mkvtoolnix-gui fail to merge files with this error

--- Errors emitted by job 'merging to file »foo.mkv« in directory »/home/bar«' started on 2015-10-09 09:13:12 ---
There is no translation available for ''.

See Debian bug http://bugs.debian.org/801277

**Comment by mbunkus** [comment]
The actual problem is likely the automatic upgrade process of the configuration files after 8.2.0 which leaves the locale entry empty. This has been discussed in #1457, and in #1434 I've implemented a fix that should prevent the execution of mkvmerge without the translation. I'm therefore closing this again.

**Comment by marillat** [comment]
Sorry for the duplicate bug report, but I've only searched in opened bug report.

**Comment by mbunkus** [comment]
No problem at all.
