### ISSUE TITLE
Can't add attachments no more

### ISSUE THREAD

**Issue by Krzysiu** [mbunkus/mkvtoolnix#1464]
I can't add attachments in 8.4.0 (edit: I noticed the last working version is 8.1.0) - nor by drag'n'drop, nor by right click and add. I'm on Windows 7 64 bit and MKVToolnix is 64 bit as well. The error message is just "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information." in the windows with title "Microsoft Visual C++ Runtime Library". 

Steps to reproduce are very simple, at least in my case:
1) go to attachments tab (doesn't matter if after adding tracks or before)
2) drop any file (could be cover.jpg or anything)
3) crash

PS: I wanted to do it by command line and:
C:\>mkvpropedit.exe e:\time.mkv --add-attachment e:\cover.jpg
The file is being analyzed.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by mbunkus** [comment]
This is almost always due to you either removing the file `data/magic.mgc` or using one from a different release. The library that access this file requires it to be present, and the file's format must be the one the library expects – and this format may change with the releases I'm using.

So please make 100% sure that the `magic.mgc` file is present, is exactly 3.865.680 bytes long (for release 8.4.0).

**Comment by Krzysiu** [comment]
Sorry for... bugging :) you. You are right. I hadn't magic.mgc at all. It was working well for earlier versions, so I just copied exe files everytime. After adding that file, it works well. Thanks for quick reply, helping me fix my mistake and for your time!

**Comment by mbunkus** [comment]
You're welcome.
