### ISSUE TITLE
C++ Error - This Application has requested the Runtime to terminate it in an unusual way

### ISSUE THREAD

**Issue by crosjr** [mbunkus/mkvtoolnix#1481]
I am unable to open mkvtoolnix-gui as it stops on this error.  This happens with 8.3, 8.4 and 8.5 for sure.  I went back to 8.3 for now so I can still use mkvmerge.  I ran debugview and here are the results of that:

00000001	0.00000000	[4724] libpng warning: iCCP: known incorrect sRGB profile	
00000002	0.00017029	[4724] libpng warning: iCCP: known incorrect sRGB profile	
00000003	0.00038986	[4724] libpng warning: iCCP: known incorrect sRGB profile	
00000004	0.00068291	[4724] libpng warning: iCCP: known incorrect sRGB profile	
00000005	0.00141889	[4724] libpng warning: iCCP: known incorrect sRGB profile	
00000006	0.01872164	[4724] ASSERT failure in Job::loadJob: "Unknown job type encountered", file src/mkvtoolnix-gui/jobs/job.cpp, line 345	
00000007	0.01874381	[4724] Invalid parameter passed to C runtime function.	
00000008	0.01875518	[4724] Invalid parameter passed to C runtime function.	

I set it to run as administrator and from some older threads I found, I confirmed that I have full permissions to C:\, C:\Users and C:\Users\myuser.  I also turned off UAC completely with no difference.

Any help is appreciated!

Windows 7 Ultimate SP1 x64

**Comment by mbunkus** [comment]
This is due to an unexpected situation during the conversion of old job config files. After 8.5.0 I've implemented a fix that ignores such jobs instead of aborting on them.

A solution is to uninstall/remove any current installation (uninstall if you've used the installer, simply remove the folder if you're using the portable version), then remove all old MKVToolNix settings and then re-install 8.5.0.

Old settings are possibly stored in the following places:

1. The registry: `HKEY_CURRENT_USER\Software\bunkus.org` – remove this whole key and all of its children
2. The file system: `C:\Users\YourUsername\AppData\local\bunkus.org` – remove this directory and all of its contents
3. Again the file system: in the same folder that `mkvtoolnix-gui.exe` is located in (only for the portable version).

**Comment by mbunkus** [comment]
You can also get and run [newer pre-builds](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) which already include the aforementioned change and ignore such job files.

**Comment by crosjr** [comment]
Awesome thanks so much!  The bunkus.org folder in AppData did the trick.  I did not have the registry key.

**Comment by mbunkus** [comment]
The registry would only be present if you had ever used the installed version. So don't worry about it not being present.
