### ISSUE TITLE
Mkvmerge, mkvextract and others doesn't opening

### ISSUE THREAD

**Issue by Mari7** [mbunkus/mkvtoolnix#1491]
There is just cmd appears for a split second and then disappears. Nothing happening.
Except the MKVtoolnix gui - it's the only one that opening and working.
With portable version same thing. Opening with administrator privileges doesn't helping :(
Windows 10, 64-bit.
Sorry for my English.

**Comment by mbunkus** [comment]
mkvmerge, mkvpropedit, mkvextract are command-line applications, they don't have GUIs. That's what MKVToolNix GUI is there for.

Only mkvinfo is a hybrid with both a command-line portion and an integrated GUI. In order to start mkvinfo's GUI you have to start mkvinfo with the parameter `-g`.

The installer creates start menu entries for both GUIs.
