### ISSUE TITLE
Splitting: Dialogue line missed if start time equal to first split time

### ISSUE THREAD

**Issue by shinchiro** [mbunkus/mkvtoolnix#1510]
When splitting by parts based on frame/field number with value let say 50-100 (its keyframe), if a dialogue line in .ass subtitle start at frame 50, it will be missed. To solve this, I need to adjust the start time of dialogue line to frame 51 so the dialogue line appear in splitted file

Is there a workaround for this issue? I'm using v8.5.2

**Comment by mbunkus** [comment]
Thanks for the report. mkvmerge usually splits before the first key frame after the split point has been reached due to technical reasons (not for all types of split decisions, though). See [mkvmerge's documentation for `--split`](https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvmerge.html#mkvmerge.description.split) for details.

This has always been the case, and it is unlikely that I'll ever change it.

You can simply use a frame number one less than the one you've tried.
