### ISSUE TITLE
Cannot delete mkvtoolnix folder as long as browser launched from GUI is open

### ISSUE THREAD

**Issue by SumatraPeter** [mbunkus/mkvtoolnix#1518]
My default browser on Windows 7 is Mozilla Firefox. Steps to reproduce issue:

1. Ensure browser is completely closed
2. Start MKVToolnix GUI (I'm using the portable version)
3. Select any option from the Help menu to launch the browser
4. Close MKVToolnix GUI
5. MKVToolnix folder can no longer be deleted as long as the browser's open

Now if there's an open file or the app is running I can expect this sort of behavior, but why with a simple browser window launched from the app? Is this normal?

**Comment by mbunkus** [comment]
Thanks, I'll look into it.

**Comment by mbunkus** [comment]
This behavior (which I can reproduce with Firefox, BTW) is not intentional. It looks like the GUI starts the browser without setting the current directory (which means that the GUI's installation path is the current directory), and Firefox doesn't change the current directory when launching. Chrome on the other hand does change the current directory when launching, therefore I couldn't reproduce it with Chrome.

I'll change the GUI to make the user's home directory the current directory for the new process.
