### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by HEXYEBO** [mbunkus/mkvtoolnix#1528]
Hello,
I started having this issue a few builds back – my guess is about 3 months ago. mkvtoolnix-gui crashes when I attempt to start it via the menu shortcut or command line. CLI output is just what's in the title, no other info.

This issue only impacts my Ubuntu server, same build(s) are working just fine on my other Ubuntu and Mint client machines. A rather large crash file is created in /var/crash directory.

Linux server 3.13.0-70-generic Ubuntu  2015 x86_64

dpkg -l | grep mkvtoolnix
ii  mkvtoolnix                                                  8.6.1-0~bunkus01                                    amd64        Set of command-line tools to work with Matroska files
ii  mkvtoolnix-gui                                              8.6.1-0~bunkus01                                    amd64        Set of tools to work with Matroska files - GUI frontend

Thank you in advance for your help,

Walter.

**Comment by HEXYEBO** [comment]
Added .txt extension


[_usr_bin_mkvtoolnix-gui.1000.crash](https://github.com/mbunkus/mkvtoolnix/files/47914/_usr_bin_mkvtoolnix-gui.1000.crash.txt)

**Comment by mbunkus** [comment]
Thanks for the report. This is likely due to something unexpected either in the configuration file or the stored job queue files. Please do the following:

  * Rename the directory `~/.config/bunkus.org` to something else, e.g. `~/.config/bunkus.org-bak` (please don't remove it just yet)
  * Start the GUI

If it starts normally then please tar up the old directory `~/.config/bunkus.org-bak` and upload that tar to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can take a look at it. Thanks.

**Comment by HEXYEBO** [comment]
Hello and thank you for the quick reply. 
I am a little puzzled, because… my server does not have the said directory. `~/.config/bunkus.org`
 does not exist! I tried copying this directory from another Ubuntu (desktop) machine – same result. Disk space and permissions checked out as well. 

Found a `~/.config/mkvtoolnix` directory. Renaming it did not help. Contents uploaded.

Walter.

**Comment by mbunkus** [comment]
Hmm the crash happens inside Qt's startup functionality (`QPlatformIntegrationFactory::create()` called from `QApplication::QApplication()`). I don't think there's anything I can do about it; it's likely that this is a bug in Qt. Sorry.

I'm therefore closing this as invalid.
