### ISSUE TITLE
mkvextract: Unreadable character after remux

### ISSUE THREAD

**Issue by shinchiro** [mbunkus/mkvtoolnix#1530]
Here what I do:

Mux sub with the video
```mkvmerge -o output.mkv video.mkv sub.ass```

Extract sub
```mkvextract tracks output.mkv 1:sub_extracted.ass```

Remux with extracted sub
```mkvmerge -o output2.mkv video.mkv sub_extracted.ass```

When play ```output2.mkv```, the sub showed like this:
![bug](https://cloud.githubusercontent.com/assets/9623615/11529334/5fbf575a-9927-11e5-86c3-299cf2368051.png)

sample (contain video.mkv & sub.ass):
https://u.pomf.io/fdwmou.rar

**Comment by mbunkus** [comment]
This is due to the intentional change mentioned in [the release notes about not writing a BOM](https://www.bunkus.org/blog/2015/11/mkvtoolnix-v8-6-1-released/). mkvextract still writes UTF-8 (anything else like Windows-1252 would potentially cause data loss as not all of Unicode can be encoded in Windows-*) but without a BOM. mkvmerge on the other hand assumes that text files without a BOM use Windows' current encoding (often something like WIndows-1252 depending on your Windows' language and locale settings).

You have three options:

  - Tell mkvextract to write another encoding with its `-c` option
  - Tell mkvmerge that the text file is encoded in UTF-8 with the `--subtitle-charset` option
  - Don't extract in the first place and re-mux the subtitle track directly from `output.mkv`.

**Comment by mbunkus** [comment]
That being said: I do mean what I've written in the release message about being willing to revert this whole change. Your bug report does play a role in that decision and I will take it under consideration.

**Comment by shinchiro** [comment]
I see, I didnt read release note. As I know, aegisub always encode the ASS file as UTF-8 with BOM so it more sensible to write with BOM anyway. just my opinion.
