### ISSUE TITLE
Add an attachment editor to MKVToolNix GUI

### ISSUE THREAD

**Issue by ndjamena** [mbunkus/mkvtoolnix#1533]
^^^

I won't use this stuff myself, but other people seem to care.

**Comment by mbunkus** [comment]
Thanks, sounds useful as well. Not that high on my priority list, though.

**Comment by mbunkus** [comment]
New [pre-builds 1082, 1083](https://mkvtoolnix.download/windows/pre/) with this feature included are up. I'd appreciate some testing & some feedback. I've tried to cover everything in my tests but as we all know I users always find things I've overlooked :) Thanks.

**Comment by remuxer32** [comment]
Alright. I've started testing this feature. Unfortunately I've found many bugs: 

1) http://s10.postimg.org/qgtj0cjvd/0_bytes.png

As you can see, the GUI shows "**0 bytes (0 bytes)**" for all attachment types under the »Properties« column. But the most interesting is that this behaviour (0 bytes) does not always occur; sometimes the GUI does not show such "values" at all.

2) And now something really serious. Watch this film very carefully, please: https://www.youtube.com/watch?v=iIhqp4cmseM&feature=youtu.be

As you can see the GUI crashes when saving a file without the attachment (first you have to remove the attachment from the file, of course).

Here are my steps from beginning to the end:

1) Add an mkv file to the header editor (my mkv file is called: "Chappie").
2) Add an attachment (I've added a .png file).
3) Click on "Save attachment content to a file", choose a localization and save it (anyway: its size will be always 0 bytes as you can see watching my film). Finally click on "Save" entry from the "header editor" menu.
4) Go to the merge tool, add the mkv file ("Chappie") → you will see an error message: "The mkvmerge executable was not found". Well, it's very interesting behaviour as the mkvmerge executable is still in my installation directory :)
5) Add the mkv file ("Chappie") to the header editor again, and remove the attachment from the file via the "Remove selected attachment" entry, and click on "Save" entry → boom! APPCRASH.
6) Run the GUI after a crash, and open the mkv file ("Chappie") in the merge tool: this time you won't see any error message about the mkvmerge executable: the file is recognized correctly (I suspect it's due to removing the attachment from the file).

Other strange behaviours I've noticed: the "UID" column that I disabled appears sometimes when adding the mkv file to the header editor.

**Comment by mbunkus** [comment]
That's what I meant ;) Thanks for testing & the feedback.

1. Showing "0 bytes" upon adding: fixed. The file's content hadn't been added at all. That's why you were seeing 0 bytes big files after saving an attachment you had just added.
2. The crash when removing entries: fixed.
3. The error message "mkvmerge executable wasn't found": I cannot reproduce that at the moment, not even with the exact steps outlined above. I'm going to ignore this for the time being, though.
4. UID column reappearing: I cannot reproduce this either. If you can find a way to reliably provoke this I'd be curious about the steps required for it to happen.

New pre-builds are up.

**Comment by remuxer32** [comment]
Thanks for your fixes, Mosu. I've downloaded a new pre-build. Here are my observations:

► The error message "The mkvmerge executable was not found" does not appear now as the attachment has been saved successfully to an .mkv file so mkvmerge recognizes correctly this file.

Unfortunately, I've found more serious bugs. See:

1) http://s7.postimg.org/c8q4c52vf/0_bytes.png 

As you can see the GUI still shows "0 bytes" for some file types (e.g. .m2ts, .mkv, .mka). But some types are recognized correctly like .png or .dts.

2) http://s17.postimg.org/upbp7rsj3/AVI_file.png

Personally I've added an AVI file whose size is almost 1 GB. The result is as above.

3) There are more situations in which you can make a crash. For example: try to add many attachments to the header editor **at once** (it's very important). The best would be big files such as .mkv or .m2ts whose size is really huge. The result is that the GUI will be loading those files very long. The final result will be APPCRASH, of course.

4) Something minor to fix, I guess: http://s11.postimg.org/8wdsrx59f/Small_issue.png

**Comment by mbunkus** [comment]
Don't add such huge files. The GUI (as well as mkvmerge!) will have to read the whole file into memory at that point. That's nothing I'm going to change, sorry. If the files in question are too big (which happens quickly especially on 32bit platforms) then the memory cannot be allocated resulting in either "0 bytes" being shown or the application crashing depending on in which part the memory allocation fails: Qt, libEBML, MKVToolNix GUI. I cannot handle all those cases gracefully (meaning if the memory allocation fails inside e.g. libEBML I cannot detect and prevent that; the application will then simply fail to work properly).

On a 32bit Windows the maximum process size is 2 GB RAM. If MKVToolNix + the size of the attachments you're trying to handle exceeds that then *poof*. This is true for mkvmerge and mkvpropedit just as it is for the GUI.

Adding multiple files at once is most likely the same memory issue as above.

I'll fix that menu option, though.

**Comment by remuxer32** [comment]
Thank you for your explanation. I have to admit that I had no idea about it. It's good to know, then. Yes, you're right, the memory usage is almost 100% when adding such huge files. I'll remember not to add those files, then.

Also I have some additional questions to you:

1) I've discovered that I can remove the selected attachment via the Delete/Backspace key on the keyboard. It's very nice, but would be possible to implement selecting attachments via the left mouse button in order to select many attachments at once and then remove them quickly? Because currently I can remove them one by one only instead of all at once.

2) Are you planning to add a new column called "**Properties**" or "**File size**" in the "Attachments" tab in the merge tool? I mean the column that shows the attachment size → exactly the same way like now in the header editor. I thought it could be nice for users to see as it's shown in the header editor.

Thanks.

**Comment by remuxer32** [comment]
A small curiosity: I've just installed the latest pre-build (64-bit) on my Windows Server 2008 R2 64-bit with 4GB RAM. I've added a HUGE attachment (.m2ts file: 44.2 GB :D) to the header editor, and......... everything is fine! No crashes at all. The file has been loaded immediately. Just the file size is shown as 0 bytes: http://s3.postimg.org/z1p6gxccz/m2ts.png 
About the memory usage on my 64-bit platform: very, very low. Seems like only 32-bit versions have a problem with loading such big files.
So it looks like I have to start using the 64-bit version of Windows instead of 32-bit as it's very weak.

**Comment by mbunkus** [comment]
1. Selecting multiple at once: maybe. Removing multiple attachments is pretty quick with the keyboard already: delete, delete, delete, done. Or if you want to delete attachments 1, 2 and 4 but not 3: delete, delete, cursor down, delete.
2. A "size" column in the merge tool's "attachments": useful, will implement this.
3. Huge files on 64bit: hmm, I should be able to improve that a bit, I guess.

**Comment by remuxer32** [comment]
Breaking news: Program crashes when removing attachments via the Delete key (reproduced on 64-bit version). Watch this film, please, in order to see how to reproduce this issue: https://www.youtube.com/watch?v=ZkGAXAMjsb0

As you can see I've added several attachments (.m2ts) to the header editor. Then I've started removing them very fast via the Delete key. The result is APPCRASH of course. Please note: the total size of those attachments is NOT huge. Each of them is very small. This time I've used very "modest" files :-)

**Comment by mbunkus** [comment]
I've fixed the crash and added a "size" column to the merge tool's "attachments" tab.

**Comment by remuxer32** [comment]
Thanks a lot, Mosu. I'll check that when I catch a new pre-build :)

**Comment by remuxer32** [comment]
I've just downloaded the newest pre-build & made a "hardcore" test on my 64-bit server → added tons of .m2ts files (over 100) to the header editor, and then removed them extremely fast: no crashes at all :) Thanks again for the effective fix.

**Comment by remuxer32** [comment]
I've noticed you've implemented a warning that prevents adding files larger than 2 GB. That's a good idea, I think. But maybe you could add the same warning to the "Attachments" tab in the merge tool? Look: http://s4.postimg.org/3rghdnkjh/Huge_size.png I've added a huge file which is definitely not a good candidate as an attachment :) So I think that the same warning preventing adding such big files would be useful as well. What do you think?

**Comment by mbunkus** [comment]
Indeed. Done.

**Comment by remuxer32** [comment]
Great :) Thank you very much, Mosu.

**Comment by mbunkus** [comment]
…and for mkvmerge itself just now, too.

**Comment by remuxer32** [comment]
Very cool :)
