### ISSUE TITLE
relative file names interpreted relative to wrong directory

### ISSUE THREAD

**Issue by fgaurand** [mbunkus/mkvtoolnix#1534]
Hello,

I've got a strange issue since version 8.6.1.
When I try to open a mkv file inside a directory with spaces in its name, it fails with error:
"The file was not recognized as a supported format (exit code 2)"

cd /tmp
mkvtoolnix-gui ./test.mkv  # => it works fine
mkdir "test directory"
mv test.mkv test\ directory/
cd test\ directory/
mkvtoolnix-gui ./test.mkv  # => error !

Any idea what's going wrong?
I'm running Ubuntu 14.04.3 LTS 64bits with bunkus ppa...

**Comment by mbunkus** [comment]
Thanks for the report. I can reproduce it on Arch Linux as well and will look into it.

**Comment by mbunkus** [comment]
The issue is that the GUI now changes its working directory to `$HOME` upon startup in order not to block the removal of the directory it was started from. Unfortunately it still tries to open the relative file name you've passed instead of determining the absolute path before changing the working directory. I'll fix this, of course.

So this has nothing to do with spaces but whether or not your `$HOME` contains a file with such a name.

As a workaround you can specify an absolute file name, e.g. `mkvtoolnix-gui $PWD/test.mkv`.
