### ISSUE TITLE
Feature request: show tracks/data wheight (in Mb)

### ISSUE THREAD

**Issue by MttCastelli** [mbunkus/mkvtoolnix#1551]
...in detailed box, main window. Just that simple.

Regards, Moritz.

**Comment by mbunkus** [comment]
Thakns for the suggestion. I'm sorry, but that is not possible without a lot of effort. The problem is that very, very few container formats actually store a track's size somewhere, and the GUI would have to read the whole file just to determine the proper sizes.

I will therefore not do it, not even for the few formats that actually provide the information as users would be confused and (rightfully) ask why the size is shown in some situations but not in others.
