### ISSUE TITLE
MPEG-TS: video ES not recognized due to incomplete PES processing

### ISSUE THREAD

**Issue by basicmaster** [mbunkus/mkvtoolnix#1553]
Hi,

here comes a lot of text:

I spent half the day to (kind of) figure out a rather special bug regarding the MPEG-TS reader:
When I try to remux a certain TS file to MKV, all the (audio) tracks are recognized except the video track (please see `mkvmerge_pes_problem.ts` on your FTP). I used `mkvmerge -I file.ts` during my further tests, which leads to the same result.

As far as I can see, the reason is the PES processing in combination with the fact that within the video ES - in contrast to e.g. an audio ES - the `PES_packet_length` in every PES packet header is `0`. This leads to the fact that the content amount of all the PES packets of the video ES, which is actually processed, is the following:

    1st PES packet: complete
    2nd PES packet: PES payload of the first regarding TS packet only!
    3rd PES packet: complete
    4th PES packet: PES payload of the first regarding TS packet only!
    etc.

Regarding an ES which has a non-zero PES_packet_length, the end of a PES packet can (and currently is) easily detected by comparing the so-far size of the PES payload buffer with the expected size, until both are equal. So the content of each PES packet can be separated from the content of any adjacent PES packets.

With a zero PES_packet_length, this approach does not work. The code considers also this case as far as I can see, but unfortunately the following happens here:

When the first TS packet of the *first/third/etc.* PES packet is processed, the PES payload buffer is empty and the PES payload of the TS packet is appended to the buffer. Further appending takes place when the remaining TS packets of this PES packet are processed. So everything fine up to now.

When the first TS packet of the *second/fourth/etc.* PES packet is processed, the PES payload buffer is NOT empty (as the end of the previous PES packet is detected just now). The PES payload of the current TS packet is then appended to it! So now the PES payload buffer contains both the complete payload of the *previous* PES packet AND the payload of the the first TS packet of the *current* PES packet (all this alone does not necessarily cause any harm). As this time `track->data_ready` in `mpeg_ts_reader_c::parse_start_unit_packet` has been set to `true`, the content of the PES payload buffer is now flushed to the actual ES parser; the PES payload buffer gets empty.

But now the PES payload of all the remaining TS packets of the current PES packet gets discarded, as the regarding buffer size check in `mpeg_ts_reader_c::parse_packet` is not passed!

The two described behaviours alternate every packet, so that in the end only a little more than a half of the video ES is processed for ES recognition. Therefore sometimes the video ES will be recognized, sometimes not. While the file I uploaded does not work - I cut out the beginning of a longer recording -, a later portion of the same original recording does work.

In my opinion, the appending of the PES payload of a TS packet to the PES payload buffer should happen *after* the check for a finished PES packet. Thus in addition, the payload of adjacent PES packets is no longer mixed when flushed to the actual ES parser.

As I do not have a complete overview of the MPEG-TS parser and all of its features, I decided to write a bug report rather than to fix it myself. :-)

**Comment by mbunkus** [comment]
Thanks for the comprehensive report & for the sample file. I'll look into it.

**Comment by mbunkus** [comment]
I really don't like the TS reader. It's code contributed by someone else (for which I'm really grateful!), but it has always been a mess and I have to analyze big parts of it every time I want to fix something. This leads to big re-factoring. A lot of work…

Anyway.

I've fixed this issue. mkvmerge now recognizes and muxes your sample file. I know that the result is slightly out of sync. This is due to a combination of the video having been cut in the middle of a GOP (group of pictures, meaning not in front of a key frame) and mkvmerge's MPEG 1/2 video handling code not being up to keeping sync with provided timestamps in such a case. This is nothing that I'm going to work on, MPEG 1/2 video not having a high priority for me at all. It should be rather easy to work around with the `--sync` option, though.

I'm compiling new [pre-builds for WIndows](https://mkvtoolnix.download/windows/pre/) at the moment if you're using that OS. Build numbers 1080 (32bit) and 1081 (64bit) will contain the fix.

**Comment by basicmaster** [comment]
Thanks for fixing this.
It is absolutely fine that the result is not completely in sync as it was just a file for testing. I use Linux and was successfully able to try the fix with the latest Git version.

**Comment by mbunkus** [comment]
Thanks for the confirmation.
