### ISSUE TITLE
MKVPropEdit adds itself to its track statistics tags, thus invalidating them...

### ISSUE THREAD

**Issue by ndjamena** [mbunkus/mkvtoolnix#1557]
MakeMKV is putting the wrong BPS values in its tags, I'm testing re-encoding an episode with a few filters and thought I'd compare the bitrate of the new 1080p h.264 version with the original DVD rip... and...

```
General
Unique ID                                : 38270369438029482321786823043957254634 (0x1CCA9AE472CBE58D5444CFE83ECDE9EA)
Complete name                            : D:\Make\Jimmy Neutron.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 868 MiB
Duration                                 : 23mn 16s
Overall bit rate mode                    : Variable
Overall bit rate                         : 5 211 Kbps
Movie name                               : Jimmy Neutron
Encoded date                             : UTC 2016-01-01 08:12:50
Writing application                      : MakeMKV v1.9.8 win(x64-release)
Writing library                          : libmakemkv v1.9.8 (1.3.3/1.4.4) win(x64-release)

Video
ID                                       : 1
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Format settings, picture structure       : Frame
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 23mn 16s
Bit rate mode                            : Variable
Bit rate                                 : 4 915 Kbps
Maximum bit rate                         : 6 400 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 29.970 (30000/1001) fps
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.475
Time code of first frame                 : 00:00:00:00
Time code source                         : Group of pictures header
Stream size                              : 819 MiB (94%)
Language                                 : English
Default                                  : No
Forced                                   : No
Statistics Tags Issue                    : mkvpropedit v8.7.0 ('All of the above') 64bit 2016-01-01 08:49:01 / MakeMKV v1.9.8 win(x64-release) 2016-01-01 08:12:50
FromStats_BitRate                        : 5013107
FromStats_Duration                       : 00:23:16.995000000
FromStats_FrameCount                     : 41868
FromStats_StreamSize                     : 875410845

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 23mn 16s
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Stream size                              : 32.0 MiB (4%)
Title                                    : Stereo
Language                                 : English
Default                                  : Yes
Forced                                   : No
Statistics Tags Issue                    : mkvpropedit v8.7.0 ('All of the above') 64bit 2016-01-01 08:49:01 / MakeMKV v1.9.8 win(x64-release) 2016-01-01 08:12:50
FromStats_BitRate                        : 192000
FromStats_Duration                       : 00:23:16.832000000
FromStats_FrameCount                     : 43651
FromStats_StreamSize                     : 33523968

Menu
00:00:00.000                             : en:Chapter 01
00:00:36.136                             : en:Chapter 02
00:11:29.822                             : en:Chapter 03
00:11:30.322                             : en:Chapter 04
```

**Comment by mbunkus** [comment]
Hmm no, it doesn't. This is most likely a MediaInfo issue.

What mkvpropedit does is pretty much the same that mkvmerge does for each track: first it looks for the `_STATISTICS_TAGS` tag. Next it removes all tags whose names are listed in `_STATISTICS_TAGS`. Additionally it discards the following three tags: `_STATISTICS_TAGS`, `_STATISTICS_WRITING_APP`, `_STATISTICS_WRITING_DATE_UTC`. Only afterwards are new tags created.

I've just updated MakeMKV to 1.9.8 and created a file with it. Looking at the extracted tags from that file you can see that MakeMKV writes proper tags; everything's present and as it should be. `_STATISTICS_WRITING_APP` exists and contains MakeMKV itself.

Next I've updated the tags in the file with `mkvpropedit file.mkv --add-track-statistics-tags`. Now my MediaInfo shows the same output as your MediaInfo.

However, when you extract the tags from that file with mkvextract you'll see that there's only a single `_STATISTICS_WRITING_APP` entry for each track, and that entry contains mkvpropedit – as it should as mkvpropedit was the one that calculated those statistics. The string `MakeMKV` doesn't occur once in the extracted tags from the file modified by mkvpropedit.

I'm guessing MediaInfo is displaying both the content of the `_STATISTICS_WRITING_APP` and of the `writing application` segment info header field at that point, but only if they differ.

Not a bug in mkvpropedit.

**Comment by ndjamena** [comment]
???  I thought the point of  _STATISTICS_WRITING_APP was to compare it to the headers to confirm it's in the right file...

So it's just the time and date that need to be compared?

You never said that.

https://github.com/mbunkus/mkvtoolnix/wiki/Automatic-tag-generation

```
 _STATISTICS_WRITING_APP  contains mkvmerge's version information. It can be used to identify which application has created those statistics. If this differs from the segment header field  WRITING_APP  then the tags may be out of date (meaning another app A was used to remux a file that contains valid statistics but A hasn't bothered to update the statistics tags itself).
```

You've contradicted yourself.

1: it says which program wrote the tags
2: it invalidates them if it doesn't match the headers

**Comment by mbunkus** [comment]
Nothing on that page says that they're **always** invalid if those two values differ. It says that the tags **may** be out of date if they differ.

What it doesn't say but what it implies that you have to compare `_STATISTICS_WRITING_DATE_UTC` with the `date` segment info header field, too, yes.

**Comment by ndjamena** [comment]
> _STATISTICS_WRITING_DATE_UTC  contains a timestamp when the statistics tags where created in the format  YYYY-MM-DD HH:MM:SS .

And of course the date says ABSOLUTELY NOTHING about comparing it to the header AT ALL.

What the hell is wrong with you?  IMPLIES?

That's the same damn argument I read you give to someone complaining that the Matroska specs didn't mention skipping unknown elements.

1: YOU'RE NOT ALLOWED TO IMPLY THINGS

2: MAYBE YOU SHOULD READ UP ON WHAT "IMPLY" MEANS, BECAUSE YOU HAVEN'T IMPLIED ANYTHNG HERE, IF ANYTHING YOU'VE IMPLIED TO COMPARE THE APP TAG TO THE HEADERS AND NOT THE DATE.

**Comment by mbunkus** [comment]
Calm down, please.

**Comment by ndjamena** [comment]
It's not even the encoded date?

So happened to checking to see if the tags are valid?

What happened to programs blindly copying tags into files they don't belong in?

That was the entire point wasn't it?

I have no idea what the hell is going on now.  As usual.

**Comment by mbunkus** [comment]
Here's what my intention was (I'm also going to update the wiki page to include this information more clearly):

- The application that creates the statistics tags must set `_STATISTICS_WRITING_APP` to its own name & version, `_STATISTICS_WRITING_DATE_UTC` to the date & time when those statistics tags were created.
- A muxer that is aware of those tags must strip existing ones before writing its own tags. The ones to strip are the ones listed in `_STATISTICS_TAGS` and the the following three: `_STATISTICS_TAGS`, `_STATISTICS_WRITING_APP`, `_STATISTICS_WRITING_DATE_UTC`.
- A reader (either a program or a human) that is aware of those tags can compare the `_STATISTICS_WRITING_APP` and  `_STATISTICS_WRITING_DATE_UTC` values with the segment info header values `writing application` respectively `date`. The timestamp comparison is especially useful in order to determine whether or not the tags are up to date: if the tag's date is newer than the segment info date then they should be OK.

An application that isn't aware of those tags and simply copies them over will also copy that old timestamp. The resulting file will then have a newer segment info date field than the timestamp in the tags, and on top of that the writing application will differ giving you a range of information where to lay the blame if something is wrong:

- If the tag's timestamp is older than the segment info's `date` field then you can blame the application named by the segment info field `writing application` for not supporting those tags.
- If the statistics themselv are wrong you can also assign blame to the right application: if the tag's date is newer then blame the `_STATISTICS_WRITING_APP` instead of the segment info `writiung application`. This might be the case if mkvpropedit has bugs in its statistics calculation routines.

The combination of those two fields and the comparison against their counterparts in the segment info header give you those possibilities.

**Comment by ndjamena** [comment]
What happened to tags beginning with underscores aren't for user viewing?

I was going to write that into MediaInfo as well, it's a bit hard to compare things they can't see.

And it does kind of assume the PC that added the tags has the correct date programmed in.

What you're saying now bares no resemblance to anything you've ever said before.

**Comment by mbunkus** [comment]
If the user uses a specialized application for viewing the tags then the application should itself evaluate the information and present the user with an appropriate message if they're out of date. However, the user may still look at the raw output (e.g. with mkvinfo of by extracting the tags to an XML file); and in that case she must be able to make that determination herself.

The argument about clocks is a strawman.

**Comment by ndjamena** [comment]
```
A straw man is a common form of argument and is an informal fallacy based on giving the impression of refuting an opponent's argument, while actually refuting an argument which was not advanced by that opponent.
```
So what you're saying is that there is no way of determining whether or not statistics tags are valid or not?

**Comment by mbunkus** [comment]
No, I'm not; please don't put words in my mouth.

It is possible: by comparing the date fields. Of course that implies that the computer's clock is somewhat current, but that's a moot point as most computer systems require the clock to be somewhat current, otherwise things like domain authentication or certificate validation breaks down.

I've updated [the wiki entry](/mbunkus/mkvtoolnix/wiki/Automatic-tag-generation) with more information how an application can make this determination and how to react.

Adding the statistics date has been about determining whether or not the tags are up to date/valid. The statistics writing app information has been about which applicaiton to blame if they're wrong. Both pieces of information are important, albeit for different reasons. I'm sorry if this sounds different from our earlier conversation; my intention is not to confuse you, and I've obviously failed at that.

**Comment by ndjamena** [comment]
Setting the date back on a PC in order to extend trials and such is actually quite common practice, I've done it myself.

I've also had the date go wrong all by itself.
