### ISSUE TITLE
mkvtoolnix GUI should have option to select languages which are preferred (to be on top of the list)

### ISSUE THREAD

**Issue by miniworm** [mbunkus/mkvtoolnix#1562]
In new GUI there should be an option to to select languages which are preferred (most used ones) and they should be on top of the language list. Such option was on old GUI but right now on top there is fixed list of "top languages" and no option to add new ones or deselect actual ones.

**Comment by mbunkus** [comment]
That is and always has been possible. Go to the preferences, look at the "often used selections" section. Those selected there are on the top but also in the full list (in order not to confuse users who're looking in the full list).

**Comment by miniworm** [comment]
That's how i've done it in the past. But maybe it's only me but i cannot see preferences from few versions. From a long time i use mkvtoolnix from your repository in Ubuntu 14.04.

**Comment by mbunkus** [comment]
It's the first entry in the "MKVToolNix GUI" menu.

**Comment by miniworm** [comment]
That's the main problem - in last few releases there is no menu. Take look a main window (Ubuntu 14.04 64bit).
![zrzut ekranu z 2016-01-09 21 06 05](https://cloud.githubusercontent.com/assets/1372625/12218084/0139cdbc-b715-11e5-8b99-08367eae5960.png)

**Comment by mbunkus** [comment]
Well, I haven't added any code that hides the menu bar or toggles its visibility. This is most likely due to your desktop environment. I don't think I can help you with that. Sorry.

On KDE and LxQT with OpenBox the menu bar is shown just fine. Those are the two environments I use and test with. I know that other environments like Ubuntu's Unity tend to move the menu bar somewhere else, but that's not something I support (meaning I won't investigate issues related to such environments).

**Comment by mbunkus** [comment]
Maybe you're experiencing [this bug in Ubuntu](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619).

**Comment by mbunkus** [comment]
Well, I just gave it a try. It's like stated in that bug report I've linked. Remove the `appmenu-qt5` package and the menu will show up again.

**Comment by miniworm** [comment]
Thanks! It was the case. I've thought that i removed all appmenu packages, but somehow appmenu-qt5 was installed. Thanks one more time :-)
