### ISSUE TITLE
Handling existing Language Country information incomplete

### ISSUE THREAD

**Issue by robatok** [mbunkus/mkvtoolnix#1565]
Hi,
if I use MKVPropEdit to modify/set audio language of a mkv-file to 'deu' (which is a valid ISO 639-2 short code for German/"Deutsch") MKVPropEdit throws an error "Invalid change spec...".

This behaviour might be a problem for 21 other languages which (like German) have two short codes in ISO 639-2, too. More details can be found here: http://www.loc.gov/standards/iso639-2/faq.html#3

This "bug" appeared with the last release (v8.7.0).

By the way: Thanks for the great tools!

**Comment by mbunkus** [comment]
Matroska uses the [bibliographic variants of ISO 639-2](http://www.matroska.org/technical/specs/index.html), not the terminology ones. Therefore you should use "ger" instead of "deu". In earlier releases mkvpropedit simply didn't verify those values. This means that any player that doesn't know about the terminology variants would not know what "deu" was supposed to mean.

I consider this not to be a bug but actually correct behavior now. Sorry.

**Comment by mbunkus** [comment]
But what I can and will do is make mkvpropedit convert the terminology forms into bibliographic ones. That way when you enter "deu" it'll write "ger".

**Comment by robatok** [comment]
OK,
Thank you for the quick response and action.

**Comment by mbunkus** [comment]
You're welcome.
