### ISSUE TITLE
"Executing programs after certain events" needs documentation

### ISSUE THREAD

**Issue by FCrane** [mbunkus/mkvtoolnix#1570]
Hi!

I was searching for a workaround for one of the most annoying shortcummings of MKVToolNix: the lack of any audible notification when a job has finished! Anything, a beep, a wave file, whatever. 

So I was happy to see the new feature to execute programs when a job is finished, but I was extremely disappointed to see that this seems to be the buggiest implementation of anything I've ever seen!

Nothing works: 

1) you can not simply enter the path to a media file! Doesn't play it. Simply using "ShellExecute" API would support that.

2) When entering a fully qualified path, the program simply deletes all "\", so it's impossible to enter a complete path! WTF???

3) Even downloading a small exe to play wav files and entering a command line like "Sounder.exe tada.wav" - both files are in the installation directory of MKVToolNix - does not work!

4) There is no error message, no log entry, etc. if the execution fails. No way to find out what the problem was!

5) There is no "Test" button to test the execution. I have to start a merge job just to test the execution? WTF?

So nothing works actually! The feature would be great, but clearly nobody has even tested it once, because no aspect of it seems to be close to working...

Please fix that and make it play sound files - which would be the most important action after a job completes...

Thanks!

**Comment by mbunkus** [comment]
It does work, but the whole thing could definitely use some documentation. I'll write up a couple of points here and include them in the very same dialog including a couple of examples:

1. No, I'm not using ShellExecute() for technical reasons. You can emulate that by going through `cmd.exe`; e.g. `c:/windows/system32/cmd.exe /c c:/temp/yourfile.wav`.
2. The escaping mechanism used in this dialog is the Unix escaping mechanism because that's one that can actually be produced by a human being – unlike cmd.exe's escaping mechanism. This means that backslashes are used for escaping the next character. If you want an actual backslash you either have to include the whole thing in single quotes `'c:\windows\…'` or use double backslashes `c:\\windows\\…`. Note that Windows can use and understand forward slashes, too, so you could also use `c:/windows/…` and it would just work.
3. Always use full paths, both for the program to execute as well as any arguments. Why? Because the GUI changes its current working directory to the user's profile/home directory upon start in order not to block the installation directory (this was done due to a user request). So if you put `sounder.exe` in the same directory as the GUI then it will only find it if you use the full path. In fact, just use the browse button to the right of it in order to locate the executable.
4. I may add a "test" button, though such a test would naturally not have any of its variables set to anything useful. Therefore it would be of limited use. It'd be OK for your case but not for other use cases.

Here are two examples for you that play a WAV. I've verified that both work just fine; they're both copy & pasted directly from the GUI:

```
'c:\windows\system32\cmd.exe' /c 'c:\0temp\test.wav'
'C:\0temp\sounder.exe' 'c:\0temp\test.wav'
```

Adjust for the location of your 

Contrary to your belief playing a sound is not the most important action after a job completes for a lot of users. I know of several for whom playing any sound at all is something they loath. Your priorities are not everyone else's.

I can understand that you're frustrated, but venting your anger only makes me angry at you in turn because a) you could also have asked for help instead of simply ranting and b) I've spend countless hours creating a program that you use without any cost, and your words really show no discernible appreciation of that at all. So please: tone it down a notch. Thanks.
