### ISSUE TITLE
Optionally append CRC to the filename

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1580]
The function to start processes is useful for various things.

On Linux you can use ```mv``` and  ```cksfv``` to append the CRC to the filename.
```for file *.mk*; do mv "$file" ${file%.*} $(cksfv -b "$file" ???```
(is incomplete because I can't handle it. Maybe it is even easier.)

Unfortunately Windows does not include a tool that can calculate checksums of files. While I had the idea to invoke a third-party tool, instead; I thought it might be so useful that it can be a feature that can be included in mkvmerge. CRC32 will be supported anyway, so it isn't something that would have to be added just for that.

I think I saw CRCs in filenames for Matroska releases first. Supposing that this is still done, it might make their lives easier.

For what I have seen it was the case that the CRC was always at the end of the filename and in brackets:
```filename [CRC].mkv```

Having it that way would be fine for me. Configurable options, like prepending (instead of appending and what kind of delimiter (like space, yes or no; ```[]``` or ```()```, would not be something I would reject.

Even typing ```filename [$CRC].mkv``` and mkvmerge just replaces $CRC, would be very nice.

(BTW: I do understand that the CRC32 elements aren't about the whole file.)

**Comment by mbunkus** [comment]
Due to the libraries that are used for writing the Matroska file and the way that mkvmerge re-writes portions of it during muxing it is impossible to calculate the CRC (or any other cheksum) during the muxing process. mkvmerge would have to re-read the whole file after it's been written and calculate the checksum from it.

That's obviously time-consuming and nothing most users would need or use. Such a use case is also one of the reasons that I've made the "run jobs after…" feature as flexible as it is: you can write your own shell/Perl/Python/$favLanguage script that does whatever you want with the file. If you ever want to use SHA1 instead of CRC then you're able to do that. You wouldn't have to rely on me implementing support for SHA1.

If you need external tools just install Cygwin, Git bash or use the corresponding checksum modules for Python/Perl/Ruby/$favLanguage.

For those reasons I won't implement such a feature.
