### ISSUE TITLE
Wrong dirty

### ISSUE THREAD

**Issue by adem0x** [mbunkus/mkvtoolnix#1582]
MkvToolNix GUI (v8.8.0) 

Here are the steps:

1) Open any MKV file with MkvToolNix GUI.
2) Do nothing.
3) Try to close MkvToolNix GUI.

It will display a dialog warning that the file has been modified and whether you want to really close it risking losing all changes..

This is annoying. It should not display this dialog.

**Comment by mbunkus** [comment]
This is working as intended. A merge configuration is unmodified when empty. As soon as you add a file it has been changed since its pristine state. It becomes unmodified again if you save those settings. The next modification after saving (e.g. adding another file) will mark the configuration modified again.

If you don't like those checks then you can turn them off in the preferences.
