### ISSUE TITLE
2GB file size error when dragging successive files into the header editor

### ISSUE THREAD

**Issue by AndrewR79** [mbunkus/mkvtoolnix#1585]
First noticed with 8.8.0
If you open an MKV file by dragging it to the header editor it will open fine as normal.
If you then drag another one, without closing the first with the menu command, it will give you this error message!
If you close the first file, the 2nd one will then open without the file size error.
![mkvmerge bug](https://cloud.githubusercontent.com/assets/16125868/12729601/8883a448-c91f-11e5-8f25-c277eae7f46a.png)

**Comment by mbunkus** [comment]
When you drag & drop a file onto a header editor tab that's already open then that file will be added as a new attachment to the already open file. This is intentional.

Due to several limitations in the libraries used for reading and writing Matroska files each attachment can only be at most 2 GiB big. Hence the error message.

I acknowledge that there's a usability issue here. I'll probably modify the behavior to ask the user what she wants to do: add a new attachment or open the file in a new header editor tab.
