### ISSUE TITLE
After mkvpropedit unable to play files on LGTV

### ISSUE THREAD

**Issue by majuansari** [mbunkus/mkvtoolnix#1587]
hi, 

I added audio tag using following command

 mkvpropedit /Volumes/MEMORY\ CARD/downloads/show.mkv --edit track:a1 --set language=eng --edit track:v1 --set language=eng

After that I am not able to play the video on lg tv . Can any one help ?

Thanks

**Comment by mbunkus** [comment]
mkvpropedit as well as the GUI's header and chapter editors may relocate certain structures to almost anywhere in the file. They always reference the relocated structures from MetaSeek elements so that players may still find them. See [this FAQ entry](/mbunkus/mkvtoolnix/wiki/All-tracks-vanished-after-mkvpropedit,-the-header-or-chapter-editors).

If your TV doesn't then that's a limitation/bug in your TV. You'll have to re-mux your file in such a case. Simply re-muxing should be enough; no need to change any settings.

**Comment by majuansari** [comment]
Is there any way to fix this using mkvmerge or mkvpropedit ?

**Comment by mbunkus** [comment]
No, there is not.
