### ISSUE TITLE
Localization bug on MKVToolnix GUI

### ISSUE THREAD

**Issue by fioda** [mbunkus/mkvtoolnix#1590]
When I set the language to "Português do Brasil (Brazilian portuguese)" it still uses the "Português (Portuguese)".

Deleting the "pt" folder from the localization "solves" this bug, but leaves the program half in english and half in portuguese, the old good gui doesn't have this issue.

I was using the portable version (x64).

**Comment by mbunkus** [comment]
Thanks for the report. I can reproduce it and will look into it.

About the missing entries: the Brazillian Portuguese translation is simply pretty lacking due to the translator not being active. Nothing I can do about it myself as I don't speak Portuguese, but I'd welcome any help with the translation.

**Comment by mbunkus** [comment]
There's no bug here. Like I said the Brazilian Portuguese translation is pretty incomplete. For those strings that haven't been translated into Brazilian Portuguese the (normal) Portuguese translation is used instead. This is the intended behavior.
