### ISSUE TITLE
Add keyboard shortcuts for removing successfully completed jobs

### ISSUE THREAD

**Issue by igor2x** [mbunkus/mkvtoolnix#1599]
In issue https://github.com/mbunkus/mkvtoolnix/issues/1598 I suggested adding a "remove completed option" to right menu, but ticket was closed. Never might, I understand your position and I even agree with it.

But now I have I come in with most probably even much better suggestion (enhancement request). What about adding a keyboard shortcut like CTRL+R for example for "remove completed jobs" and CTRL+SHIFT+R for "remove successfully completed jobs". But for the "remove all jobs" I would not add any keyboard shortcut, because from end-user perspective you probably almost never need to clear all jobs, specially those that are running.

What do you think about keyboard shortcuts?

**Comment by mbunkus** [comment]
I'm not really in favor of adding keyboard shortcuts for all kinds of situations, especially as the menu entries are only two key presses away: `Alt+j` followed by `c` for clearing successfully competed jobs (you don't even have to release `Alt`: `Alt+j` followed by `Alt+c` works just fine, too).

I'll think about this instead of outright rejecting it, though.

**Comment by mbunkus** [comment]
Ctrl+R was already in use in that screen for starting the queue. I've decided to use `Ctrl+L` for the safer option (removing only the successfully completed ones) and `Ctrl+Shift+L` for removing all completed jobs.
