### ISSUE TITLE
--cropping not working

### ISSUE THREAD

**Issue by vibrasphere** [mbunkus/mkvtoolnix#1604]
In wiki https://github.com/mbunkus/mkvtoolnix/wiki/Cropping-ignored it says "This is a bug in your player."

Does it mean a standalone player or a software player? Because the --cropping I apply to any 1080p .mp4 muxed to .mkv file it doesn't show in cropping applied in MPC-HC nor VLC.

On what software does it work at all?

Also, what's with the 'left, top, right, down' cropping method instead of 'top, right, down, left' which is used by other tools, e.g. using MeGUI/Avisynth to get the values (that also include -negative for left, down) and then on mkvmerge you need to remove the -negative symbol and move left from the back to the front.

Anyway, doesn't work.

**Comment by mbunkus** [comment]
Like I've said in the FAQ entry. Cropping parameters are solely stored in the headers. It's up to the player to actually make use of them. So far I was under the impression that VLC has support for those parameters, but I may be mistaken about that.

**Comment by vibrasphere** [comment]
So what's it working on? How I can test it?

**Comment by mbunkus** [comment]
I don't know, I'm sorry; I don't use that feature myself. You should ask the VLC community or file a bug with them. I'm not in the business of writing playback software.

**Comment by optimiz** [comment]
On Fedora 20, VLC (v2.1.6) uses the specified cropping parameters when playing MKV files, using either software or hardware decoding; however, neither MPV (v0.3.11) nor xine (v0.99.9) do. See [MPV issue #79](https://github.com/mpv-player/mpv/issues/79) for its current cropping support status and "wontfix" reasoning (since 2013).

The following screenshot shows VLC's display window on the left juxtaposed with the in-player snapshot from the same frame on the right...

![vlc_example](https://cloud.githubusercontent.com/assets/8029862/13231425/b67152ca-d95e-11e5-98ac-ef2fb688dbb3.jpg)

mkvmerge verbose reports the following...
container: Matroska Track ID 0: video (MPEG-1/2) pixel_dimensions:720x480 display_dimensions:853x480 **cropping:0,9,0,9**
