### ISSUE TITLE
feature request: mkvtoolnix-gui session management

### ISSUE THREAD

**Issue by AlexFolland** [mbunkus/mkvtoolnix#1613]
It would be nice if the user could close mkvtoolnix-gui and mkvtoolnix-gui would restore the previous session automatically next time, with all current fields, enabled/disabled tracks, etc set identically to how they were before the user closed it or it crashed.  This would work in a similar way to the Firefox option "When Firefox starts: Show my windows and tabs from last time" or the sublime-text default behavior, or Winamp, or Chrome, or uTorrent.

This would be a great convenience for me when I am constructing a video using tracks from several different files and applying precise timecode alterations to various tracks.  Without session management, the entire process is rather frail and I have to keep variables I'm working with in another program.  It's workable, but less convenient than it could be.

Thanks!  :)

**Comment by mbunkus** [comment]
I'm sorry, but I won't implement anything like that. I don't deny it would be useful to you, but I have zero interest in implementing it, and there are most certainly others who would prefer no session management. Therefore I would have to make it configurable, too.

You can try playing around with saving the settings and using those files as a kind of session. Note that when using the installer the `.mtxcfg` files are associated with the GUI so that when you double-click on a saved `.mtxcfg` file the GUI will open with those settings loaded. You can do that manually with the portable version, too, of course.

**Comment by AlexFolland** [comment]
I didn't know about the .mtxcfg files.  Thanks a lot!  That really helps.  :)

**Comment by mbunkus** [comment]
Great :) You're welcome.
