### ISSUE TITLE
MKV with 24 bits per sample flac is reported as 32bits per sample

### ISSUE THREAD

**Issue by dxhelios** [mbunkus/mkvtoolnix#1622]
MKV with 24 bits per sample flac is reported as 32bits per sample
![snip_20160312132733](https://cloud.githubusercontent.com/assets/12989024/13722680/409edbb0-e856-11e5-8cc0-b28b652bf8d5.png)

**Comment by mbunkus** [comment]
Can you upload a sample file to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server), please? I'd like to take a look at it.

**Comment by mbunkus** [comment]
I guess it was you who uploaded `sample.zip` a couple of minutes ago. The files show that ffmpeg is the culprit here. It writes the `bit depth` track header parameter with the value 32, and that's what mkvmerge (and by extension the GUI) shows as the number of bits per sample. Both mkvmerge and the GUI are working as intended; the bug is in ffmpeg.

**Comment by mbunkus** [comment]
That commit should have been attributed to #1662. Sorry for the noise.
