### ISSUE TITLE
problem with audio-stream after muxing

### ISSUE THREAD

**Issue by Klaus1189** [mbunkus/mkvtoolnix#1633]
I encountered a problem with an Audio-Stream of a videofile after muxing with 8.9.0.
The Audio is PCM Stereo but after muxing the audio is reported by MediaInfo as 3 channel. 
I tried several Videoplayers like VLC media player, MPC-HC, MPC-BE, ... but no one can decode the audio stream after muxing.
The 151 MB sample is already sent to you via Mail on 22.03.2016
The file is hosted on Maildrop, so you can reach the file the next days.

**Comment by mbunkus** [comment]
The file you've uploaded (IMG_0586.MOV) and linked to contains a 2-channel AAC track, not PCM. MediaInfo reports AAC, mvkmerge detects AAC. Also remuxing that file results in a Matroska file for which MediaInfo also reports 2 channels.

Have you uploaded the wrong file?

**Comment by Klaus1189** [comment]
Yes, sorry, my fault. I sent you new Mail.

**Comment by mbunkus** [comment]
Thanks. The problem is that the file contains inconsistent data. An MP4 or QuickTime audio track contains version-dependent configuration data (basically the data structure's size and fields vary on a version number field contained the same data structure). The basic version 0 includes the channel count, bit depth, sampling frequency as 16 bit fields, and those are the values mkvmerge currently uses. Later versions (1 and 2) contain the same basic fields that version 0 already includes.

However, version 2 of the data structure includes wider versions of the same fields (channel count, bit depth, sampling frequency) in a separate location. The values stored in the version 2 fields are the correct ones (2 channels, 48000 Hz sampling frequency) while the values stored in the version 0 fields are bogus (3 channels, 1 Hz sampling frequency).

I'll change mkvmerge to prefer the version 2 fields if present. That's what other players/frameworks like ffmpeg do, too.
