### ISSUE TITLE
Build 9.0.0 crashes MKVExtractGUI2

### ISSUE THREAD

**Issue by thejester77** [mbunkus/mkvtoolnix#1636]
Build 9.0.0 crashes MKVExtractGUI2.

Doesn't seem to crash when using MKV Cleaver...

**Comment by elsy04** [comment]
It isn't exactly crashing here, but it hangs on opening the files, and stays forever at: "Executing mkvinfo...".

With gMKVExtractGUI it works, but it opens up the "mkvinfo" module two times: the first time, showing the information right away; the second, taking too long with "parsing file" process. It extracts rightly after that.

And effectively, it keeps working fine with MKVcleaver's last version.

**Comment by mbunkus** [comment]
This is most likely due to [this change](/mbunkus/mkvtoolnix/commit/71a0a5a2c3236f0a19fa545dfbdeb7e5828b44a8).

Additionally both programs are doing it wrong! Using and parsing mkvinfo's output for such tasks is not supported by me. Instead they should use mkvmerge's JSON identification output (`mkvmerge -F json --identify the-file.mkv`) for retrieving all relevant information just as both [mkvmerge's documentation](https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.track_ids) states. The identification output is designed to be easily parseable by a machine (and by extension with programming languages), it is the only supported way for determining things like track IDs/attachment IDs properly and it is guaranteed to include all the relevant information whereas mkvinfo's output doesn't include elements that aren't located at the beginning by default (e.g. attachments or tags if they're stored at the back of the file).

So please file bug reports with those two projects. Thanks.

**Comment by elsy04** [comment]
Thanks for the clarification.

**Comment by Gpower2** [comment]
@elsy04
In gMKVExtractGUI v1.7.0 the problem with mkvinfo was solved.

@mbunkus 
gMKVExtractGUI uses mkvinfo in order to detect the relative delay between video and audio tracks.
Unfortunately this isn't possible with mkvmerge's --identify option, so running mkvinfo is required, unless you could add the necessary info in --identify output.

**Comment by elsy04** [comment]
@Gpower2 
Thanks, it works fine now. :)
