### ISSUE TITLE
File mysteriously smaller than expected

### ISSUE THREAD

**Issue by Patneu** [mbunkus/mkvtoolnix#1646]
Hi,

I edited an .mkv file with the MKVToolnix gui/mkvmerge version 9.0.1 for Ubuntu. The file had 1 video, 1 audio and 1 subtitle track and I selected the subtitle track to not be muxed. Now the resulting file's size somehow is only approximately half of the size of the original file. Since I didn't expect (and didn't see before) a single subtitle track to have this much weight when it comes to the overall file size and I understood that MKVToolnix doesn't change the other tracks (at least when not told to do so) by muxing/demuxing the file and I haven't seen this behaviour with over files edited the same day in the same way using the same version of the application I found that rather odd.

At first glance, except for the file size, the resulting file doesn't seem to have anything unusual to it. The video track seems intact as far as I can tell and has no (visible) decrease in quality. A second try didn't change the result.

I don't think I'm allowed to upload the files for you since I don't own their copyright, however I attached a MediaInfo export for both. If I can provide any further info on this subject, I will.

Thanks for any hints on what's going on. ;-)

[Input.txt](https://github.com/mbunkus/mkvtoolnix/files/200074/Input.txt)
[Output.txt](https://github.com/mbunkus/mkvtoolnix/files/200078/Output.txt)

**Comment by mbunkus** [comment]
mkvmerge removes filler data from several video formats including MPEG-2, AVC/h.264 and HEVC/h.265. This data is often used on DVDs and Blu-rays as those disc formats actually specify a minimum bitrate a stream must achieve (most likely so that DVD and Blu-ray players can keep rotating the disc and don't spin down and up all the time).

This is most likely the reason, especially seeing that the source file was produced by MakeMKV.

**Comment by Patneu** [comment]
Thanks for the quick reply. =)

So I understand that data was removed by mkvmerge, which is essentially not useful for me, then that's a good thing (half the file size though, wow). Is this a new feature (since I can't remember to see it on any other file before) and could it therefore be useful to give some older files a new run with mkvmerge to save a little disc space for example? Or was it always there and is simply not needed very often?

**Comment by mbunkus** [comment]
That data (filler bytes for MPEG-2 and complete filler NALUs for the other formats) are indeed only useful for keeping the stream's bitrate above that minimum. They're not used in the decoding process and don't carry any relevant data. So yes, leaving them out is a good thing.

This is not a new feature. mkvmerge has been doing this for quite some time (since 2012-08-02 for MPEG-1/2 video, since 2007-01-04 for AVC/h.264 video and for HEVC/h.265 since general support for HEVC was implemented). Whether or not filler data is used depends on the discs and their content in question. If the content's bitrate is high enough already then there's no need to bolster the bitrate artificially. So it's not really surprising you haven't stumbled across it yet.

**Comment by Patneu** [comment]
Ok, thanks, I think that answers the question for me.
