### ISSUE TITLE
Windows binary packages are the wrong versions, direct from Fosshub

### ISSUE THREAD

**Issue by jungletek** [mbunkus/mkvtoolnix#1652]
Since I can't find a link on the Fosshub page to report it, here I am. Apologies if it's the wrong place because it's not an application bug per se.

The 64-bit portable package from the main Fosshub MKVT download page has version 8.8.0 packaged inside, despite the link and package saying it's the newest. If you follow the link to 'older versions' and pick 9.0.1 portable, you get a package with 9.0.0 inside.

The 64-bit installer I finally tried gave me the correct version, so I'm satisfied in that regard, but obviously you need to sort out that packaging process, especially if it's automated, as it appears it's slightly broken.

On a related note, I've been using this software for a number of years now, and it's great, so thanks for that. The redesign is nice and the UI is much improved. The regular updates are welcome, so don't get me wrong when I say this; one thing that gets a bit tired though, is having to manually update. Any chance you'll implement some sort of updater functionality? Would that be compatible with Fosshub, or do they need their pageviews that badly that they'd not let you do that?

Please consider it. Thanks again for your hard work on this incredibly useful tool.

**Comment by mbunkus** [comment]
Thanks for the report. For both versions this is likely due to me having had to pull already-released versions once and replacing them with new builds (in the case of 9.0.1 vs. 9.0.0 the Windows build simply hadn't used the new version number albeit containing the new code – due to a SNAFU in my build system). I'll remove those wrong older versions and replace them with proper binaries.

The old versions on FossHub are automatically archived from the versions I upload as far as I understand (I'm not a FossHub admin, so this is guesswork). It seems that if I re-upload with the same version then the already existing old release won't be updated. I'll keep it in mind for the future.

About an automatic updater: I won't spend time on this. Not because I desperately need the revenue (I don't make a living from MKVToolNix and never could), but simply because I have no interest whatsoever in working on something like that and fixing all the issues that'll surely stem from such code. Sorry.

**Comment by jungletek** [comment]
Fair enough, I understand. Thanks for the response, and take care.

**Comment by mbunkus** [comment]
The binaries on OldFoss have been replaced.
