### ISSUE TITLE
mkvmerge aborts reading file broken at the beginning

### ISSUE THREAD

**Issue by CornyC** [mbunkus/mkvtoolnix#1654]
I'm trying to merge an h265 video stream and audio/subtitles. The output only contains the audio/subs and there's no warning or error message. The h265 file is playable in vlc....

**Comment by mbunkus** [comment]
Thanks for the report. Please upload the file you're trying to mux to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can take a look at it.

**Comment by CornyC** [comment]
Thanks for the fast reply! Files are up.

2016-04-09 12:45 GMT+02:00 Moritz Bunkus <notifications@github.com>:

**Comment by mbunkus** [comment]
Thank you. I'll look into it.

**Comment by mbunkus** [comment]
Turns out the problem has nothing to do with the video codec in question but with the fact that there's an error in the file structure before the first cluster. mkvmerge simply aborts reading the file at that point. It is way more resilient to errors somewhere in the middle, and it should be as resilient to errors right before the first cluster. I'll fix it.

**Comment by mbunkus** [comment]
If you're running Windows then you'll be able to get [new pre-builds](https://mkvtoolnix.download/windows/pre/) in a couple of mintues; they're currently being compiled. Build numbers 01179 and higher will contain the fix.

**Comment by CornyC** [comment]
That's awesome! Thx for the great support!

2016-04-09 15:52 GMT+02:00 Moritz Bunkus <notifications@github.com>:
