### ISSUE TITLE
MPEG2-TS: Teletext-subtitles with type 5 are not detected

### ISSUE THREAD

**Issue by hurda** [mbunkus/mkvtoolnix#1662]
I wondered my mkvtoolnix wouldn't detect the subtitles in any of my recordings.
My guess:
https://github.com/mbunkus/mkvtoolnix/blob/851485b20f50244f6cbecfe8b5aa6c554d55f6d2/src/input/r_mpeg_ts.cpp#L515

Apparently the broadcasts I'm receiving have the Teletext-subtitles set as type 5 ("teletext subtitles: hearing impaired") and not type 2 ("teletext subtitles"). (ETSI EN 300 468 6.2.43, table 94).

![teletext_subs_type_5](https://cloud.githubusercontent.com/assets/3539609/14668488/e004c4a6-06e4-11e6-95ff-b07e0a0339b2.png)

Would adding type 5 to the conditional have any sideeffects?

**Comment by mbunkus** [comment]
Thanks for the report. I cannot say whether or not this would just work, more work would be required or if such a change might have a negative impact, too. Do you have a sample file that I can test things with? If so please upload it to [to my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by hurda** [comment]
Sample test3.ts is on the server in folder 1662.

**Comment by mbunkus** [comment]
Thanks. I'll look into it.

**Comment by mbunkus** [comment]
Adding 5 to the test seems to work fine with your sample file. It also doesn't have any negative effects for my existing test files.

However, the next problem is that the encoding used in those entries is strange. The signaled national character set is 0 = English, but there are tons of German Umlauts which mkvmerge cannot handle. Even if the signaled national character set was German the encoding would still be wrong. I'm not sure how to fix that. A separate issue would have to be opened for it. It is nothing that I'm very keen on spending time on, to be honest – support for teletext subtitles has already taken up immense amounts of time due to the braindead way they're transmitted and structured.

**Comment by mbunkus** [comment]
I've pushed fixes for the two problems I've mentioned.

The next problem with that file is the timestamps for the tracks. The tracks present in the file use widely different PTS values. For example, the first PTS for the first audio packet is raw value 2657283420 ( = 08:12:05.371) whereas the first subtitle packet's PTS is raw 7005791850 ( = 21:37:22.131) – and those two packets occur right at the start of the file. mkvmerge already normalizes timestamps down to 0, but this means that the subtitle's timestamps will start at 13:25:18.360. Obviously not really correct.

I don't want to spend time on this at the moment, though. Sorry.

**Comment by hurda** [comment]
> but this means that the subtitle's timestamps will start at 13:25:18.360. Obviously not really correct.
No, the timestamps in the SRT created by mkvtoolnix are actually correct, if that's what you mean.
The duration of the whole file is wrong due to the handling of the channel's teletext-PTS-madness, and this causes all kinds of problems in players.

> I don't want to spend time on this at the moment, though. Sorry.
I wanted to filed a bug, as the handling of the PTS-discrepancy is unfortunately also affecting muxing when using an external SRT instead of the internal conversion.

I've uploaded the SRT for the test-file and the test-file without the Teletext-stream, in case you'll ever need them.
