### ISSUE TITLE
Muxed files come out corrupted(only in 1x playback)

### ISSUE THREAD

**Issue by KevinTruest** [mbunkus/mkvtoolnix#1666]
I did about 300gb's of muxing. Fixing the audio labels, adding subtitles, etc..
Of the files i finished, about 1/3rd had significant corruption(where the file stops in playback, and 1+ minute of the video is just broken) and 1/2 had issues like the video occasionally falling out of sync with the audio, or 1 or 2 frames with artifacts. Only got the chance to review the files i had made a few days ago.

Really irritated with this, as i had assumed something like this couldn't happen after so many updates were put out, and thus cleared the source files as i worked on the files. Now i'll need to re-acquire the source files which might not even be possible.

**Comment by mbunkus** [comment]
I've had similar reports in the past, and each time it turned out to be due to specific hardware (especially if USB hardware was involved) and/or Windows' settings regarding write caching. I've invested countless hours in trying to reproduce such problems on various computers and various operating systems (Windows, Linux, even a BSD) in the past, and such corruption has never occurred on my end. I will therefore not investing time here and close this issue. Sorry.

Please see the following old issues about similar problems: #651, #830, #1045.
