### ISSUE TITLE
Colon is removed from a file path pasted to output file field

### ISSUE THREAD

**Issue by OlegPliss** [mbunkus/mkvtoolnix#1672]
When a file path is pasted to the output file field, the colon is removed. It is especially annoying under Windows where colon is a natural part of every full file path.

The issue is not reproducible in v 8.8.0.

**Comment by mbunkus** [comment]
This is likely due to #1647. What's the actual path you're pasting? I've just tried `J:\mbunkus\mkv\h264\some_file.mkv` and it works just fine with 9.1.0.

**Comment by bastik-tor** [comment]
Not my report, but if I paste ```"C:\Users\$username\Desktop\test.mkv"``` into the Output file text box, the colon gets removed.

It does not matter if it is drive C:\ (Windows installation) or drive F:\ (actually a different drive, not just a partition). The colon gets removed every time. (My insides/guts stay intact ;) )

I just open 9.1.0 on Windows and paste the above path into the text box for the Output file; I can reproduce it.

**Comment by mbunkus** [comment]
Hmm I see what you mean… Quotation marks aren't valid file name characters either; therefore the GUI thinks the colon is not part of the drive letter (it only keeps a colon if it's the second character). Removing colons should probably be done after all the other characters have been removed so that the check for "keep the colon after the drive letter" actually succeeds.

**Comment by bastik-tor** [comment]
The quotation marks are added by Windows. To try and reproduce I went to a folder, pressed Shift, right-clicked on a file, then selected ```Copy path``` (```Als Pfad kopieren``` in German) to paste that into the field.

If I copy the path to the editor and copy only the path without the quotation marks the colon stays.
