### ISSUE TITLE
Not merging files...

### ISSUE THREAD

**Issue by IndyJoe1977** [mbunkus/mkvtoolnix#1682]
Tried to do a series of TV episodes as one file, and I select all the episodes, tell it to merge, and when it is done, the file size is what it should be, but the length is only as long as the longest episode, and there is only one episode there, not eight. Seems strange.

**Comment by mkver** [comment]
You apparently added all eight files to mkvmerge and told it to merge. The result is that your file will have eight video streams and eight audio streams, but this is not what you want: What you want is one video and one audio stream with a length equal to the sum of the lengths of the individual files. At least that's what I presume you want. Then you should add the first episode to mkvmerge and append the other seven files to this file. (To do this, right click on the entry for the first episode and click on "Append files"; I presume that each of these files has a full set of headers. Otherwise, you need to use "Append files as additional parts". See [this wiki entry](https://github.com/mbunkus/mkvtoolnix/wiki/Appending-files-vs.-adding-as-additional-parts) for more on this.) In this case the first timestamp of the second episode will come directly after the first episode is finished; similarly for the other episodes. What you did was different: Your file contained all the eight episodes and every one of them started at timestamp 00:00:00. Mkvmerge declares by default the tracks of the episode that you added first to be the default track and these will probably be the tracks that players play if you open the file. (At least that's what they should do.) 
Tip: Mkvmerge can automatically generate chapters so that you can easily navigate to the episodes. Click on "Output" (I presume you use the GUI). In the chapters section, there is an option called "Generating chapters" where you can select "One chapter for each appended file".

**Comment by mbunkus** [comment]
What mkver said ;) Thanks for answering so extensively.

**Comment by IndyJoe1977** [comment]
This worked. Sorry for late reply. Work third shift and sleep...just now
getting up. Thank you for explaining my error and informing me of the
proper way. Much appreciated!
