### ISSUE TITLE
feature request: drag and drop mtxcfg files into the Job queue

### ISSUE THREAD

**Issue by sibustior** [mbunkus/mkvtoolnix#1714]
Add the ability to drag and drop mtxcfg files directly into the Job queue. Currently, config files can be dropped into the Merge tab, but then they have to be added to the queue one by one, which can be time consuming when dealing with many files.

**Comment by mbunkus** [comment]
Thanks for posting it here, too.

**Comment by remuxer32** [comment]
This is a great idea. I fully support it. It will be useful for me, too.

**Comment by remuxer32** [comment]
**@Mosu**

I have two hints for you regarding this feature. I think that they are worth to consider them on your part. I consider them as very useful for users. I'm interested in your opinion.

**1.** My first idea is to add a new tooltip in the job queue tool in order to inform users that they can drag & drop **.mtxcfg** files directly into the job queue. Here are some arguments:

**a)** the three sections: **merge tool, header & chapter editor** contain information about dragging and dropping files. Therefore the job queue tool should **not** be an exception; it should contain such advice as well

**b)** as we know most users do **not** read the **ChangeLog** at all. It simply means that most of them will **not** know about this feature. Yes, their loss, but most of them will be wasting their time for adding configuration files to the merge tool instead of to the job queue tool directly. A new tooltip should help them to avoid such situations

I know that the job queue tool — in contrast to the first three sections — doesn't contain a special card with tips and buttons, but you can add a tooltip in a balloon (a balloon tooltip) which already exists in that section → currently there is only one tooltip: **»Right-click for actions for jobs«**. You could place a new tooltip next to these words or create a second balloon for the new tooltip only. It's your choice of course.

**2.** There are some (or many?)  users who keep the **MKVToolNix GUI** icon on the desktop. Most of them, also, like opening many files via dropping them directly **onto** the icon. What if they want to add configuration files to the job queue tool via dropping them onto the icon on the desktop? The answer is simple: currently such files will be open (default behaviour) in the merge tool, not in the job queue. 
My proposition is to implement a way that will let users to choose their favourite behaviour after dropping configuration files onto the icon. The way is a new dialog that will always offer them two options with one simple question, for example:

**»What do you want to do with the configuration files you've dragged & dropped onto the icon?«**
**• Open in the merge tool
• Add to the job queue**

Thanks to that users will always have a choice and will **not** have to add their jobs one by one from the merge tool to the job queue anymore. But for those, who don't like such dialogs, you can add a checkbox in the preferences that will let them to deactive the dialog, of course.

Thank you for considering these two hints.

**Comment by mbunkus** [comment]
About your suggestions:

1. Unlike the other tools where you can close all tabs the job queue is always open. I won't add text there, mostly because I'm entirely sure that dragging existing .mtxcfg files is something few users will actually do. Not each and every possible action in a GUI deserves a dedicated text explaining it.
2. The same reasoning is why I won't add a dialog asking the user what she wants to do with a .mtxcfg file listed on the executable's command line (e.g. when she drops it onto the icon on the desktop). Such dialogs to slow things down, and they're only of real help if the all of the actions offered therein have roughly the same chance of being the one the user actually wants. I don't see this with adding job queue files. Additionally adding multiple files to the job queue is now trivial: the GUI must simply be running, then select the job queue and drop the files there.

Always having a choice is not always a good thing. Some users like it, some are indifferent and some hat it because it gets in the way. And no, making everything configurable isn't the solution either — any code present in the program must also be tested, and I won't add features just because they can be added.

So no, sorry, I won't implement either suggestion.
