### ISSUE TITLE
Some DTS soundtracks are no longer detected

### ISSUE THREAD

**Issue by Fakk2** [mbunkus/mkvtoolnix#1727]
Strangely, when adding the Police Academy mkv films to the app (9.2.0) I cannot see the DTS soundtracks, therefore I cannot remake the mkv file with only the English DTS soundtracks and remove all the foreign languages that are AC-3.

I am not sure if older versions of MKVtoolnix were able to see the DTS tracks for these set of movies, but I have never had this problem before using MKVtoolnix, and I have been using it for a long time. Sorry if I cannot be more specific with the problem, this is my first time reporting an issue.

**Comment by mkver** [comment]
As I understand your post, your input file already is a matroska file and not a bluray-disc. If so, what do mkvinfo and mediainfo have to say about it? Does there really exist a DTS soundtrack at all any more in this file?

**Comment by Fakk2** [comment]
Actually, sorry the movie file I am trying to turn into an MKV is an MP4 file. When I input the file into the app mkvtoolnix to turn it into an MKV file, what I wish to do is to keep the English DTS Mono language audio file, and get rid of all the non needed AC-3 foreign language audio tracks.

When watching the video using MPC-HC or VLC, they both detect the English audio files as a Mono DTS file, and yet the mkvtoolnix cannot seem to detect the English DTS audio file in the multiple Police Academy's 1-7 mp4 files.

When I use mediainfo on the first Police Academy mp4 file for example, it tells me that the first audio stream is (English, 768Kbps, 0 Hz, 28 bits, channel0, DTS)

Yet, when I open up mkvtoolnix and add the movie file, all the audio files it detects are the foreign AC-3 files, and the one English file it detects is the AC-3 Directors Commentary.

**Comment by Fakk2** [comment]
Actually, sorry the movie file I am trying to turn into an MKV is an MP4 
file, and the app says it's container is a Quicktime/MP4. When I input 
the file into the app mkvtoolnix to turn it into an MKV file, what I 
wish to do is to keep the English DTS Mono language audio file, and get 
rid of all the non needed AC-3 foreign language audio tracks.

When watching the video using MPC-HC or VLC, they both detect the 
English audio file as a Mono DTS file, and when playing this on my 
Stereo 7.1 Receiver it also tells me that the audio being played is 
indeed a Mono DTS track, yet the mkvtoolnix cannot seem to detect the 
English DTS audio file in the multiple Police Academy's 1-7 mp4 files.

When I use mediainfo on the first Police Academy mp4 file for example, 
it tells me that the first audio stream is (English, 768Kbps, 0 Hz, 28 
bits, channel0, DTS)

Yet, when I open up mkvtoolnix and add the movie file, all the audio 
files it detects are the foreign AC-3 files, and the one English file it 
detects is the AC-3 Directors Commentary. This is a big problem, because 
the only English audio track for all 7 movies is the DTS track.

**Comment by mkver** [comment]
Maybe mkvmerge has problems to detect mono DTS-tracks. Or maybe your file is just a bit broken (mediainfo reports a sampling frequency of 0 Hz which makes absolutely no sense). You should probably upload a sample to Moritz' [ftp-server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server).

**Comment by Fakk2** [comment]
I have no idea how to make samples from the original files, but if you like I can upload the entire movie. I have all 7 movies from the Police Academy series that have the same issue here. All 7 movies play properly, and all 7 of them are MP4 files that have only 1 DTS track in English. All 7 of them seem to display the same kind of info in Mediainfo, and all 7 of them cannot detect the DTS track in mkctooknix.

Would you like me to just upload one of the videos? I have the fastest DL and UL speed in Cali, and can get this done fast. :) As for making samples, I have never done that before, nor have I ever made a BluRay disc to MKV file before either. I don't know how it's done.

**Comment by mkver** [comment]
I indeed meant one of the files when I said sample. But now on second thought I have a different idea: Your files probably contain errors and in this case there is nothing mkvtoolnix can do about it (mkvtoolnix does not repair mp4 files) and it would be a waste of Moritz' precious time. Therefore you might test two other programs before: ffmpeg and mp4box. Maybe they can read your DTS stream. (Both MPC-HC and VLC are based on ffmpeg so it is not unlikely that ffmpeg can.) If ffmpeg does not report errors, then this might indeed be an error in mkvtoolnix (and in mediainfo) and then you should upload one of the mp4 files even though you already have your mkv files so that the error in mkvtoolnix can be found and fixed. You would be doing the communitiy a service by this. If ffmpeg reports errors then there is no real reason for Moritz to take a look into this. If ffmpeg fails then maybe mp4box can still demux the DTS stream.

**Comment by Fakk2** [comment]
Well, I am guessing that the DTS file is somehow corrupt as YAMB with MP4box cannot rip the audio file from the movie either. It can detect it, but it refuses to rip it. I don't know how to use FFMPEG and have not used DOS apps in over 2 decades. So, even though the movie plays fine in DTS from start to finish, somehow it is corrupt? Thanks anyways. :)

**Comment by mkver** [comment]
It's a command-line programm, not a DOS app. Visit [this site](https://ffmpeg.zeranoe.com/builds/) and either download a static or shared build. Then extract it. Run a command prompt and open a explorer windows and navigate to the where the executable files from ffmpeg are (that's then \bin subfolder of the ffmpeg folder). Drag and drop the ffmpeg.exe onto your command prompt. Now you should have the full path of your ffmpeg.exe in quotation marks. Then type " -i " (without quotation marks) and drag and drop one of your mp4 files onto the command prompt. Then press enter. ffmpeg should now give you some information about its build and some information about the file and an error that you haven't picked any output files. Then you should use [map](https://trac.ffmpeg.org/wiki/Map) to include your video and your dts stream in the output file. Don't forget to tell ffmpeg to copy the dts stream, otherwise it will be automatically processed to aac. If this doesn't work then you might at least get a helpful error message.

**Comment by mbunkus** [comment]
Again thanks for triaging this, @mkver. @Fakk2: mkvmerge contains a couple of checks to see whether a track is valid or not. A sample rate of 0 Hz may indeed be responsible for mkvmerge skipping that track.

However, as DTS data contains that information in their frame headers mkvmerge could re-create that information. Can you please upload the (full) MP4 source file to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server)? I'd like to take a look at the file. Thanks.

**Comment by Fakk2** [comment]
Sure, I would much more like to upload the movie file to your server 
instead of messing about with the other application that requires me to 
use Command Prompt. It's been too long using Windows for me to go back 
to using Command Prompt apps with no GUI. :D

I will start the FTP up in a bit once a movie is over that I am 
watching. The file that I am uploading is about 10GB in size, so it 
might take a bit to upload, but I have a very good speed for uploading, 
so it should not take too long. Thanks for looking at this for me, 
because I really don't want to download a group of other movies just to 
get that one DTS Audio from the video to mux with the video file from 
these files that I already have. :D

**Comment by remuxer32** [comment]
Alright, guys. It's time to take stock:

1. Due to the fact that this issue was "invisible" for a few hours (GitHub deleted it for a short time?), it was necessary to create a separate issue for it → #1728.

2. It also means that the bug has been fixed in a39623e. 

3. For this issue (#1727) a wrong label (**app:mkvextract**) has been added → because the problem applies to **mkvmerge**, not mkvextract.

4. The issue (#1727) can be closed now :)

Thank you.

**Comment by Fakk2** [comment]
Thanks for fixing the problem, and getting back to me on this. They deleted my stuff thinking that I was a bot or something and I had to get everything fixed on that, but I am back so I can report more issues in the future. :)
