### ISSUE TITLE
Some DTS soundtracks are no longer detected

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1728]
(I'm re-creating this issue as the originally reported issue has been deleted – along with the account that created it, @fakk2, it seems. The problem is real, though. I'm not re-creating the conversation itself, only the first post.)

Strangely, when adding the Police Academy mkv films to the app (9.2.0) I cannot see the DTS soundtracks, therefore I cannot remake the mkv file with only the English DTS soundtracks and remove all the foreign languages that are AC-3.

I am not sure if older versions of MKVtoolnix were able to see the DTS tracks for these set of movies, but I have never had this problem before using MKVtoolnix, and I have been using it for a long time. Sorry if I cannot be more specific with the problem, this is my first time reporting an issue.

**Comment by mkver** [comment]
Good to know that I am not the only one who suddenly couldn't find the discussion any more. If he hasn't deleted his account on his own, then he might have used a trash-mail-account for registration. github doesn't like them, deactivates them and demands a proof that they are human, but only after some time. Somehow they are allowed to register with such an email in the first place and can open issues which disappear as soon as the user is deactivated. Strange.

**Comment by remuxer32** [comment]
[The issue is related with #1727]

**Comment by Fakk2** [comment]
Yes, they deleted me, and my post, thinking that I was a bot or something for some reason, (even though I used my normal email that I have been using for years at Time Warner Cable to sign up), and without warning I was muted. I had to prove that I was not a bot to get un-muted. 

However, things are fixed now, and I can now make posts again, and my original post is not only fixed, but it seems that the problem that I was talking about is now fixed and ready for the next release of MKVToolsNix!

I am glad that I reported this problem, and will continue to report future issues if I find more, and I am glad that I used that FTP to send the file to, because that was how they were able to see the problem first hand and fix it. :) So, hooray for a great team!

**Comment by mbunkus** [comment]
I see :)

I've uploaded [new pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) which include the fix in case you want to test them.

**Comment by remuxer32** [comment]
**@Mosu**

He knows about it :) I mentioned about pre-builds (and not only) earlier. See, please: https://github.com/mbunkus/mkvtoolnix/issues/1727#issuecomment-229197505.

**Comment by Fakk2** [comment]
Yup, the pre-build fixed the issue completely, and I was able to use it on all 7 of the Police Academy films, and all of them were able to see the DTS track and I was able to make an MKV of all of them with only that DTS Audio track. I'm very glad to see it's fixed. :)
