### ISSUE TITLE
Missing Program Icon in Fedora 24 x64

### ISSUE THREAD

**Issue by fedorahead** [mbunkus/mkvtoolnix#1739]
I have installed MKVToolNIX on two installations of Fedora 24 x64. I have followed the commandline download and installation procedure. There is no 'MKVToolNIX' available in the 'Installed' view of 'Software" section. I searched for 'mkvtoolnix' and found 'mkvtoolnix-9.1.0-1.fc23.x86_64.rpm' in var/cache/PackageKit/metadata/updates/packages/ but based upon the repo in the 'Downloads' section of bunkus.org, it appears the *.rpm should be 'mkvtoolnix-9.2.0-1.x86_64.rpm'. I uninstalled MKVTool and 'mkvtoolnix-9.1.0-1.fc23.x86_64.rpm' was not removed. I have never run into a problem such as this so I'm not sure what additional information to provide.

**Comment by mbunkus** [comment]
I'm sorry, but I cannot really help you with this. This "software" tool you're talking about seems to be something specific to either GNOME or Fedora, neither of which I use myself. Note that even in a basic Fedora 24 installation with MKVToolNix installed from the original Fedora archive it doesn't show up in that "software" tool.

This may (or may not) be due to the fact that Fedora's `mkvtoolnix` package doesn't contain `.desktop` files — the package from my repository does. After installing the package from my repository both `mkvinfo` as well as `MKVToolNix GUI` are listed in GNOME's "show applications" menu thingy at least.

If MKVToolNix is installed (either from Fedora's repository or from mine) then you can always run it by starting the mkvtoolnix-gui` executable.

**Comment by fedorahead** [comment]
Hello Moritz: I guess I did not make it clear that I used the installation instructions provided on bunkus.org to install, specifically:

In order to add the repository all you have to do is to execute the following two commands:
sudo rpm -Uhv https://mkvtoolnix.download/fedora/bunkus-org-repo-2-3.noarch.rpm
Afterwards you can install MKVToolNix with the following command:
sudo dnf install mkvtoolnix

I was able to install on Fedora 23 without this issue ever presenting.

**Comment by mbunkus** [comment]
I did understand you correctly. My point, which I probably wasn't making that well, was that my applications showing up in the general application menu is what's important. I don't really care about that "software" tool but don't know what that "software" tool is (seems to be a GNOME-specific tool?), what it's supposed to do and how it's supposed to work. And, to be honest, I don't particularly care, especially as even Fedora's official MKVToolNix package doesn't show up in the "software" tool when it's installed.

Like I said above what I do care about is that both mkvinfo and MKVToolNix GUI show up in the general application menu. This is the case with my packages; they can both be found in GNOME's "Show applications" screen if you install my package. Such an application menu and how MKVToolNix registers in it is a distribution-agnostic and desktop environment agnostic method of providing such entries; therefore it will work if you use GNOME or KDE or Unity or one of the million other desktop environments that follow the FreeDesktop.org specifications.
