### ISSUE TITLE
.SRT files return error... again.

### ISSUE THREAD

**Issue by plastikat** [mbunkus/mkvtoolnix#1749]
I've just upgraded to v9.3.1 (from v9.1.0) and now have got the issue similar to issue #1677: when I add a .srt file to mkvtoolnix GUI (merge tab) I get an error message box saying:
_The ﬁle was not recognized as a supported format (exit code: 0)._

But in my case I am sure it **is** a valid .srt file. I've even tried to provide it using various encodings, including UTF-8, UTF-16 (both with and without BOM) and ANSI (CP1252). I'll email you the file in a moment.

**Comment by plastikat** [comment]
I'm terribly sorry: I had mangled the file and occasionally replaced timecode divider '-->' with '—>'. My fault, didn't notice it at a glance. The issue may be considered closed.

**Comment by mbunkus** [comment]
No problem at all :) Happens to everyone once in a while.

**Comment by tk-xp** [comment]
hello sir,i have the same problem here

**Comment by tk-xp** [comment]
same error showing

**Comment by tk-xp** [comment]
[www.TamilRockers.ac - Kodi (2016)[HDRip - x264 - 400MB - ESubs - Tamil]-ESubs.pdf](https://github.com/mbunkus/mkvtoolnix/files/674179/www.TamilRockers.ac.-.Kodi.2016.HDRip.-.x264.-.400MB.-.ESubs.-.Tamil.-ESubs.pdf)

**Comment by tk-xp** [comment]
have sent above the srt file in pdf format..kindly help me

**Comment by mbunkus** [comment]
First of all, please don't just post stuff in old, closed bug reports. Your issue is completely different from the original submitter's, and the original submitter is generally not interested in your particular problem. Open new issues instead.

An SRT file is a plain text file that can be opened with any capable text editor (don't use Windows' Notepad). It consists of groups of at least four lines each:

1. the line with the running number,
2. the line with the start and end timecode,
3. one or more lines of text and
4. one blank line as a separator.

Here's an example of how a valid file could look:

```
1
00:00:04,700 --> 00:00:06,736
where are you going so early?

2
00:00:06,900 --> 00:00:09,494
Don't record any more messages
on my alarm clock.
```

In your file the lines with the running numbers are missing. Add such lines manually, and you should be good to go.

**Comment by aaaxx** [comment]
@tk-xp, your file is not a valid SRT. It lacks subtitle numbers and uses dot instead of comma in timecodes. This is what SRT is supposed to look like:
<pre>
1
00:00:00<b>,</b>000 --> 00:00:00<b>,</b>000
Text
</pre>

**Comment by mbunkus** [comment]
mkvmerge can handle both commas and dots as decimal points. The missing running numbers is why mkvmerge doesn't recognize this.

@tk-xp please never just post in an existing, closed bug report. For several reasons: Your problem might be different from the original submitter's problem. The original sumitter is most likely not interested in your particular problem. Communication gets confusing if there is more than one issue in a single bug report. And your additionally posted stuff might get overlooked, just as it was in this particular case.
