### ISSUE TITLE
Audio/Video out of sync after muxing .vob file

### ISSUE THREAD

**Issue by HessiJames** [mbunkus/mkvtoolnix#1750]
My problem is pretty much the same as #337.

I have a couple of .vob files that I ripped from a DVD and when I mux them to a .mkv file the video and audio tracks are out of sync. I tried playback with vlc and mpv.

I'm using mkvtoolnix 9.3.1, libmatroska 1.4.5 and libebml 1.3.4 on openSUSE Tumbleweed.

I have uploaded the first 20 MB of one of the .vob files to your server ("audio, video out of sync after muxing.20mb.vob"), the original file is about 600 MB. If you need the complete file just say it.

**Comment by mbunkus** [comment]
Thanks for the report, but I won't spend time on this and will close this as wontfix. The reason is that the MPEG program reader code (the code that parses VOBs) was contributed by a third party a long time ago, and that person never kept it updated. I've tried numerous times to fix several of its shortcomings, but it contains too many problems and would likely require a complete rewrite. As this is outdated technology and as I have too many things to do and not enough time to implement them all I have to chose my battles, and MPEG program streams is one field I've chosen to abandon some time ago.

**Comment by HessiJames** [comment]
Sorry to hear that, but I can understand.

**Comment by remuxer32** [comment]
**@HessiJames**

Let me advise you something.

The best tool (_de facto_: the only one) for ripping/converting DVDs (**.vobs**) into a Matroska file is **MakeMKV**. **MakeMKV** fully supports the DVD structure which is one of the most complicated structures to handle. The DVD structure, besides **.vobs**, contains such elements like **.IFO** files, complex multiplexes etc., which must be scanned in order to detect items correctly.

Unfortunately **mkvmerge** doesn't support, for example, scanning **.IFO** files, so it's not a proper tool for handling DVDs (**.vobs**). Only **MakeMKV** is able to mux your DVDs (**.vobs**) into Matroska files without any major problems (bugs). **MakeMKV** will show you all titles available on your disc; you will be able to choose your favourite tracks: audios, subtitles, etc. It will also show you chapters that are assigned to the title. And the most important: functionality to open DVDs is 100% free.
 
The only situation, in which you really should use **mkvmerge**, is the need to merge two Matroska files into a single file. For example: there is the extended edition of **_The Lord of the Rings_** trilogy which was split (each part) into two discs (on DVD, as well as on Blu-ray). Due to the fact that **MakeMKV** doesn't support merging Matroska files into a single one, using **mkvmerge** is necessary for that (unless you want to keep your movie divided in two Matroska files). 

Thank you for attention.
