### ISSUE TITLE
DVD subtitles

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1768]
Hello,

you [once mentioned](https://github.com/mbunkus/mkvtoolnix/issues/1734#issuecomment-230348065) that the flexible probe-range would make it possible to find subtitles in vob-files. But even if I set the probe-range to 99.99 MKVMerge doesn't find any subtitles in any of my DVDs which certainly contain subtitles. I looked a bit around and found that your comment was probably a bit premature: [Here](https://github.com/mbunkus/mkvtoolnix/blob/master/src/input/r_mpeg_ps.h#L239) are packetizers for lots of formats, but none for subtitles. Moreover, if I am not mistaken, the ifo-files contain information about the colors used for the subtitles so that MKVMerge needs to parse them (which it can't) for a correct extraction of the subtitles. So to cut a long story short, the extraction of DVD-subtitles is something that probably will never work with MKVToolNix and one should use other tools for this task. Is that right?

Andi

**Comment by mbunkus** [comment]
mkvmerge doesn't support reading VobSubs from DVDs because it doesn't contain an IFO parser. I have no intention of adding support for that either. So yes, you should use other tools for that.

Additionally I didn't talk about VobSubs specifically in #1734 but about all types of tracks for MPEG program streams.

**Comment by optimiz** [comment]
Hello, @mbunkus, strictly speaking, an IFO parser would not be necessary.  The bitmap stream in the VOB itself contains the only _necessary_ subtitle data.  When either size or palette are "missing," media players auto-scale embedded subtitle bitmaps in conjunction with video and use a built-in colormap.  

Since an IFO parser is not actually necessary,  and mkvmerge readily accepts VOBSUB without size or palette defined, does that change your thoughts?  Put more directly, would you add **direct** mux support for subtitle streams directly from VOB without conversion to IDX/SUB?  (Ignoring the IFO completely, of course!)

If it helps, here's a sample frame from of an MKV converted from VOB where the IFO was ignored and the IDX/SUB was edited to remove both size and palette.  The media player's default display choices provide legible results, even after excluding the size and colormap choices that the converter itself inserted during the PS to IDX/SUB conversion...

![noifosample](https://cloud.githubusercontent.com/assets/8029862/17953097/48cff76e-6a25-11e6-8cc5-a2c53e888713.jpg)

Compare to the same frame played directly from DVD; the subtitle position is exactly the same, but the color palette is different...

![fromdvdsample](https://cloud.githubusercontent.com/assets/8029862/17955888/3e0a9f22-6a3a-11e6-8302-43efde24c5bb.jpg)

The workflow that produced the first sample frame is...

_# Get subtitle program stream (ignoring the IFO entirely)..._
`tcextract -i "$title.vob" -x ps1 -t vob -a 0x20 > "$title.ps0"`

_# Convert PS to IDX/SUB, ignore warning of missing IFO size/pallete..._
`subtitle2vobsub -p "$title.ps0" -o "$title"`

_# Ignore converter's size and palette -- media players will use default colormap and auto-size bitmaps with video SAR/DAR..._
`sed -i '/size/,/palette/s/^/#/' "$title.idx"`

_# mkvmerge accepts the edited IDX without any difficulty..._
`mkvmerge -o "$title.mkv" -a 1 --default-language zh "$title.vob" --language 0:en "$title.idx" --chapters "$title.chapters" --title "$title"`

`$ ffprobe $title.mkv `
>ffprobe version 2.8.7 Copyright (c) 2007-2016 the FFmpeg developers
 Input #0, matroska,webm, from 'sample.mkv':
    encoder         : libebml v1.3.0 + libmatroska v1.4.1
    creation_time   : 2015-11-20 23:51:22
  Duration: 01:40:25.39, start: 0.000000, bitrate: 6853 kb/s
    Stream #0:0(chi): Video: mpeg2video (Main), yuv420p(tv), 720x480 [SAR 32:27 DAR 16:9], max. 9800 kb/s, SAR 186:157 DAR 279:157, 59.94 fps, 59.94 tbr, 1k tbn, 59.94 tbc (default)
    Stream #0:1(chi): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Stream #0:2(eng): Subtitle: dvd_subtitle (default)

**Comment by mbunkus** [comment]
I am aware of that. But I'd consider using the SPU packets without the accompanying information from the IFO to be a bug, similar to supporting only the DTS core for DTS-HD MA tracks.

Look, this is an Open Source project. This means that people are totally free to chose what they want to work on, and I simply don't want to work on this. Open Source also means that I'd be really, really happy to accept patches that implement such functionality. What Open Source doesn't mean is that I'm a wishing well that'll make all your wishes come true. Please accept that I will not spend time on this.

**Comment by optimiz** [comment]
I understand and accept your decision completely.  No insult or expectation was intended, sorry if I came across that way.  Knowing the reason behind a roadmap decision has value.  Thanks.
