### ISSUE TITLE
Duration of VOB-subtitles

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1771]
Hello,

the duration of VOB-subtitles is not included in the idx file, but only encoded in the sub-file. So if one stretches a VOB-track (a process which streches not only timecodes, but also durations), the Matroska-duration and the duration in the bitstream do no longer match. Both MPC-HC and VLC (and probably most of the other players, too) apparently ignore the duration entry for VOB-subtitles and use the bitstream value. This is a bug in these players. But there is definitely also a bug in MKVToolNix: If one extracts the subtitles with mkvextract, the timecodes in the idx-file are correct; but the information about the matroska-durations are no longer there.
This is reproducible with any VOB-subtitle. 
I don't know if you intend to fix this (most of the time the stretch-option is only used for conversion from 23.976 to 25fps and vice versa and the differences are neglibile in this case). If you do [this](http://dvd.sourceforge.net/spu_notes) and [this](http://dvd.sourceforge.net/dvdinfo/spu.html) might be useful: The duration element is at the end of the control header.

Andi

PS: Actually the sub-file also contains the start time codes; but mkvextract writes the start time codes to the idx file and the timecodes contain therein take precedence before the timecodes in the bitstream so that a mismatch between these two is irrelevant.

**Comment by mbunkus** [comment]
Thanks for the report. I'll look into it.

It's correct that the .IDX files written by mkvextract don't contain a duration because the .IDX files never do — at least I've never seen a single one with a duration in it. The duration is determined solely from the SPU bitstream.

Therefore I'll likely modify at least mkvmerge to modify the SPU's duration field when the duration's modified. I may modify mkvextract, too, but I'll have to think about that some more before I do.

**Comment by mbunkus** [comment]
mkvextract hasn't been updated yet.

**Comment by mbunkus** [comment]
And now it has.
