### ISSUE TITLE
Weird issue of missing seconds from previous scene

### ISSUE THREAD

**Issue by alexmonroe87** [mbunkus/mkvtoolnix#1778]
Windows 7.

I have had the exact same problem with VLC record, i'm not sure what causes this.

MKV 10bit h264 1080p anime file, I specified: 00:20:16-00:21:24 "by parts based on timecodes" however the result is only 00:20:22-00:21:24.

I suspect the missing seconds are because a scene change occurs, which probably means it's a different encoding section for the h264 codec. But surely that's a crippling restriction and I never see it mentioned anywhere.

Any solution?

**Comment by mkver** [comment]
The explanation for this can be found [here](https://github.com/mbunkus/mkvtoolnix/wiki/Splitting-imprecise).

**Comment by alexmonroe87** [comment]
I expected as much, guess I just lacked the keywords to google this properly.
Does anyone know of any software that would allow you to trim non-keyframe seconds from the start and end of videos?

**Comment by mkver** [comment]
If you mean by "trim" simply discarding, then it seems that you haven't understood the link I posted: Without these frames at the beginning the frames that you are actually interested in can't be properly decoded. (Most of the video frames do not contain the complete information of the picture, but rather something like: "The 16x16 block whose upper left pixel is (16,0) looks mostly like the same block from the preceding frame, but with these differences". If the preceding frame (or another reference frame) is missing, how shall one decode the frame even if the block corresponding to this frame is present?)
As already mentioned in the link: You actually need to reencode a part of the video. [Here](http://forum.selur.de/topic220-mkv-cutter-tool-to-cut-h264-mkv-files-frame-accurate.html) is a tool that might suit your needs. I haven't tested it and therefore can't guarantee anything.
PS: Because the decoding order (the order in which the frames are decoded) and presentation order (the order in which the frames are displayed) of the frames are usually different, you even can't simply trim the end of the video.

**Comment by mbunkus** [comment]
mkver has already answered this properly; thanks.

**Comment by alexmonroe87** [comment]
@mkver I understood it fully, which is why I was asking for a tool that would preferably intelligently rencode only the first and last parts with new reference frames. Failing that, just a decent opensource video editing tool that can deal with these file formats and codecs.
Thanks anyway.
