### ISSUE TITLE
Test files that cause mkvmerge to segfault

### ISSUE THREAD

**Issue by nexxai** [mbunkus/mkvtoolnix#1780]
I spent some time fuzzing mkvmerge with afl-fuzz this weekend and found a number of test cases that cause mkvmerge to segfault.  I also used the gdb plugin [exploitable](https://github.com/jfoote/exploitable) to categorize them, of which most came back either "EXPLOITABLE" or "PROBABLY EXPLOITABLE"

The command line used for the fuzzing was:

`./mkvmerge -o /tmp/test.mkv @@`

Where "@@" is the input file test case.

As github would not let me upload the test cases individually, I've .zipped them here for your convenience, along with the gdb script that, when combined with exploitable, will show the criticality of each instance.

[mkvexplorer.zip](https://github.com/mbunkus/mkvtoolnix/files/457425/mkvexplorer.zip)

**Comment by mbunkus** [comment]
All of the test cases safe for the following three have been fixed:

* `explorer:id:000355,sig:11,src:000738,op:havoc,rep:4`
* `explorer:id:000497,sig:11,src:001249,op:flip1,pos:101`
* `explorer:id:000776,sig:06,src:002706,op:havoc,rep:4`

I haven't gotten to those due to lack of concentration. Need sleep :)

**Comment by mbunkus** [comment]
All done.

**Comment by mbunkus** [comment]
I'll probably create a new release this weekend.
