### ISSUE TITLE
Mkvtoolnix automatically remux on pc shutdown

### ISSUE THREAD

**Issue by TehBotolSosro** [mbunkus/mkvtoolnix#1787]
MKVToolNix 9.4.2
Windows 10 64bit
I sometime open a mkv file by dragging it to the mkvtoolnix gui to remove / added subtitle from the mkv file. and sometime i only want to check the content of the mkv (audio/subs)

and my pc occasionally shutdown because the electricity here are unreliable, i usually left mkvtoolnix gui left open when this shutdown occurred but it's just idling not doing any remuxing and when i turned on my pc again and i try to remux other mkv file, mkvtoolnix also tried to remux all the mkv that i have open that day even when i only checking the content (without doing any remuxing to the previous mkv file)

sadly i didn't check the job queue before remuxing the other mkv file, so i don't know whether there is a job queue there or not but mkvtoolnix shouldn't remux them when i never even use mkvtoolnix to remux that particular mkv (only open the mkv in mkvtoolnix to check the content) or even remux again mkv that already remuxed before

i seem to also notice this when couple weeks ago when i still using previous mkvtoolnix version but i disregard it as i didn't really check the output log, but today i check the log because there is 2 error because mkvtoolnix tried to remux file that already renamed so it complain it cannot find the file .

here is the output log after i tried to remux ringu 0 mkv but mkvtoolnix also remux 3 other mkv file (opened only mkv and previously remuxed mkv)

```
--- Output of job 'merging to file "Barney Thomson (2015) (1).mkv" in directory "I:\Movie\Barney Thomson (2015)"' started on 2016-09-21 22:21:36 ---
mkvmerge v9.4.2 ('So High') 64bit
'I:\Movie\Barney Thomson (2015)\Barney Thomson (2015).mkv': Using the demultiplexer for the format 'Matroska'.
'I:\Movie\Barney Thomson (2015)\Barney Thomson (2015).mkv' track 0: Using the output module for the format 'AVC/h.264'.
'I:\Movie\Barney Thomson (2015)\Barney Thomson (2015).mkv' track 1: Using the output module for the format 'DTS'.
The file 'I:\Movie\Barney Thomson (2015)\Barney Thomson (2015) (1).mkv' has been opened for writing.
The cue entries (the index) are being written...
Muxing took 15 minutes 14 seconds.
--- Output of job 'merging to file "Mike and Dave (1).mkv" in directory "I:\Movie\Mike and Dave (2016)"' started on 2016-09-21 22:36:52 ---
mkvmerge v9.4.2 ('So High') 64bit
--- Output of job 'merging to file "Jane Got a Gun (2016) (1).mkv" in directory "I:\Movie\Jane Got a Gun (2016)"' started on 2016-09-21 22:36:52 ---
mkvmerge v9.4.2 ('So High') 64bit
--- Output of job 'merging to file "Ringu 0 2000 (1).mkv" in directory "I:\Movie\Ring 0 (2000) aka Ringu 0"' started on 2016-09-21 22:36:52 ---
mkvmerge v9.4.2 ('So High') 64bit
'I:\Movie\Ring 0 (2000) aka Ringu 0\Ringu 0 2000.mkv': Using the demultiplexer for the format 'Matroska'.
'I:\Movie\Ring 0 (2000) aka Ringu 0\Ringu 0 2000.mkv' track 0: Using the output module for the format 'AVC/h.264'.
'I:\Movie\Ring 0 (2000) aka Ringu 0\Ringu 0 2000.mkv' track 4: Using the output module for the format 'DTS'.
'I:\Movie\Ring 0 (2000) aka Ringu 0\Ringu 0 2000.mkv' track 6: Using the output module for the format 'text subtitles'.
The file 'I:\Movie\Ring 0 (2000) aka Ringu 0\Ringu 0 2000 (1).mkv' has been opened for writing.
The cue entries (the index) are being written...
Muxing took 8 minutes 43 seconds.
```

```
--- Errors emitted by job 'merging to file "Mike and Dave (1).mkv" in directory "I:\Movie\Mike and Dave Need Wedding Dates (2016)"' started on 2016-09-21 22:36:52 ---
The file 'I:\Movie\Mike and Dave Need Wedding Dates (2016)\Mike and Dave.mkv' could not be opened for reading: open file error.
--- Errors emitted by job 'merging to file "Jane Got a Gun (2016) (1).mkv" in directory "I:\Movie\Jane Got a Gun (2016) -sub indo-"' started on 2016-09-21 22:36:52 ---
The file 'I:\Movie\Jane Got a Gun (2016)\Jane Got a Gun.srt' could not be opened for reading: open file error.
```

thanks and sorry for my bad english

**Comment by TehBotolSosro** [comment]
just had another shutdown, turn out just opening the mkvtoolnix gui app will automatically remux the old mkv file.

**Comment by mbunkus** [comment]
What MKVToolNix GUI does when it starts up is to automatically start working on all jobs whose status is either "waiting for automatic execution" or "running". This is intentional.

As soon as a job finishes its status is updated to "finished", and the corresponding job file is saved to disk. However, most OSes don't write such actions to disk immediately; instead they cache write accesses for improved performance. Therefore it's highly likely that due to those unexpected shutdowns the new status is not actually written to disk by the OS, and therefore the changes are lost. Re-starting the GUI after the crash will therefore see an old status.

This is nothing that can really do anything about, though. I have to assume that the files on disk are OK and that changes that the GUI tells the OS to write are actually written.

> mkvtoolnix shouldn't remux them when i never even use mkvtoolnix to remux that particular mkv (only open the mkv in mkvtoolnix to check the content)

I'm not trying to disrespect you, but I'm pretty sure you remember this wrong. MKVToolNix GUI will only try to mux files if a job has been added to the job queue for that file, and a job is only added to the job queue if the user presses either the "start muxing" or the "add to job queue" button. As long as you do not press those buttons no job is created, no job file is written to disk, and consequently the GUI won't try to access the file when it restarts after a crash.

I'm therefore going to close this issue as nothing I can do anything about.

What you can do as a workaround is to remove all the job queue files manually after a crash. See [this article](https://github.com/mbunkus/mkvtoolnix/wiki/Location-of-settings-and-the-job-queue) for the storage location.
