### ISSUE TITLE
Font and icon scaling making MKVToolnix hardly to use on high DPI screens

### ISSUE THREAD

**Issue by bigcookie** [mbunkus/mkvtoolnix#1790]
Using verison 9.4.2 on windows Surface with high res screen, makes it very hard to use. Preferences are not readable. See screenshots:
![mkvtoolnix_dpi_problem](https://cloud.githubusercontent.com/assets/2866102/18850839/93a3e042-8439-11e6-8382-095828fc9a08.png)
![mkvtoolnix_dpi_problem2](https://cloud.githubusercontent.com/assets/2866102/18850838/93a3189c-8439-11e6-91f4-aa1400c27251.png)

If more information is needed, lete me know. MS Surface Book runs on latest Win10. Java was just updated to the latest version from Oracle.

Screenshot includes full desktop for font size comparison.

**Comment by mbunkus** [comment]
I'm sorry, but I won't spend time on this. I don't have High DPI devices to test with at the moment (and won't in the foreseeable future); and the GUI is already doing the right thing according to Qt's documentation.

You can adjust the font size in the preferences dialog. Just dial it down enough, and it should be OK. That won't change the icon sizes, true, but in order to properly fix this I'd need High DPI devices to test with. That leads us back to the original point: I don't have any.

See also #1602.

**Comment by bigcookie** [comment]
Ok, just wanted to report. I will try the workaround. Let me know if you need high DPI device testing...
