### ISSUE TITLE
mkvtoolnix-gui errors on Wayland

### ISSUE THREAD

**Issue by simonbcn** [mbunkus/mkvtoolnix#1806]
Arch Linux 64 bits
GNOME Shell 3.22.1 (**Wayland**)
mkvtoolnix-gui v9.5.0 ('Quiet Fire') 64bit

When I press `Add files` button mkvtoolnix-gui crashes:
```
(mkvtoolnix-gui:15287): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
[1]    15287 segmentation fault (core dumped)  mkvtoolnix-gui
```

**Comment by mbunkus** [comment]
I'm sorry, but I cannot help you with that. I don't use GNOME, I don't use Wayland.

**Comment by mbunkus** [comment]
To be more precise. When you click on that button the GUI executes Qt's built-in file selector dialog. If you don't see that dialog then this means the crash happens in Qt, and that's simply something I cannot really do anything about anyway.

You can build MKVToolNix with debugging instructions (run `configure --enable-debug`) and get a `gdb` backtrace. Maybe that'll shed some light on where the crash is happening.

**Comment by mbunkus** [comment]
Some more information. I've just given running the GUI under Weston+Wayland a try, and it works just fine for me, no crashes at all. I've tried both the Arch Linux's own `mkvtoolnix-gui` package as well as my own compiled version. Like I said, both are fine, adding files works just fine, no crashes. I've got `qt5-wayland` installed, but it makes no difference whether or not I set `QT_QPA_PLATFORM=wayland-egl` — it works just fine in both cases.

What I haven't tried is running it inside `gnome-shell`, mostly because I simply couldn't figure out how to run it (running `gnome-session` from a console as suggested in the Arch wiki segfaults immediately).

However, the Arch wiki has a [note](https://wiki.archlinux.org/index.php/Wayland#Slow_motion.2C_graphical_glitches.2C_and_crashes) about programs crashing for `gnome-shell` users. You may give that a try.
