### ISSUE TITLE
SubRIP Srt Stretch By simply doesn't work

### ISSUE THREAD

**Issue by Vendrel** [mbunkus/mkvtoolnix#1807]
At last, I wrote '2' into this field to half subtitles' speed, mux finished, and then: subtitles appeared exactly at the same time.

OnPlay setting of Subtitles speed and the another one (I don't what is it in English) are also ignored by the application.
![screenshot 2016-11-13 00 31 04](https://cloud.githubusercontent.com/assets/5756032/20242712/0c874692-a939-11e6-93c7-179f0fd33513.png)

**Comment by mbunkus** [comment]
That screenshot does not show any part of MKVToolNix. Your first paragraph does sound like you're doing _something_ with MKVToolNix, though. So — please show me the exact command line you've used. For that re-create the settings you had before, then select "Merge" → "Show command line" and paste that here.

**Comment by Vendrel** [comment]
:D I am sorry, I might be so sleepy that late hour (3 A.M.) that I mixed two different applications' issues just because they are used in one process (remuxing videos)…

This is the MKVToolNix screenshot showing the affected function: 
![screenshot 2016-11-13 13 08 39](https://cloud.githubusercontent.com/assets/5756032/20245481/dd140318-a9a2-11e6-810f-15d1372308a2.jpg)

Brief: No matter what value I enter, subtitles appear at the same time. 

Thanks for this great tool, by the way! :)

**Comment by mkver** [comment]
This is not my experience. The timecodes and the durations of the subtitles of the srt are stretched by the factor that you enter in the "Stretch by"-field. Afterwards the delay is applied.
Possible reasons for what you experience are:
1. Your file has two subtitle tracks; you stretched only one of them and your player plays the other one.
2. You stretch everything and by "at the same time" you actually mean "the subtitles are shown alongside the same part of the video" which is expected because in this case there is no relative stretching (but the delay should still apply).
3. The settings for the player you used counteracts the stretching.
4. Players often autoload subtitle files if they are in the same folder (in a subfolder of the folder where the file is if said subfolder is named "Sub" or "Subs" or so) and the names are similar enough to the names of the file that you want to play. You have to rule this possibility out when checking which subtitles your player actually plays.
There is no bug in MKVToolNix in any of these cases.

**Comment by mbunkus** [comment]
@mkver has made some excellent suggestions of what might actually be wrong here. Let me offer a fifth: you might have tried to play the wrong file: the unmodified source file.

**Comment by Vendrel** [comment]
Your extra-fast response is frenetic, and thank you for testing it this
fast. :)

I now tested it in every aspects and I am sorry, it really works fine. I
have to do trouble-shooting better.

Point 4. was the problem, VLC loaded the external SRT file, this deceived
me.

Keep up the good work, thanks!! :)

**Comment by Vendrel** [comment]
By the way, there's another issue. If VLC loads the external SRT file, character encoding is OK. But after I mux it into the MKV file, it goes wrong. May it be an issue at the MKVToolNis-side?
![screenshot 2016-11-13 14 12 54](https://cloud.githubusercontent.com/assets/5756032/20245935/4540d502-a9ac-11e6-838a-e52f53d9d0a5.png)

**Comment by mbunkus** [comment]
Text subtitle files can have arbitrary encodings. As they cannot be detected reliably you'll have to set the character set of the if it isn't the same that your system uses. Click on the subtitle track, then change the "character set" option on the right (the button next to it gives you a preview).
