### ISSUE TITLE
Add executed commands in message window

### ISSUE THREAD

**Issue by tapiau** [mbunkus/mkvtoolnix#1828]
This may be with "verbose output" checkbox in options.

**Comment by mbunkus** [comment]
What for?

**Comment by mbunkus** [comment]
After thinking about it I've decided not to implement such a feature.

MKVToolNix executes mkvmerge by writing almost all of its command-line options into temporary option files. The actual command line executed looks something like this: `C:\path\to\mkvmerge.exe @c:\path\to\temporary\optionfile.txt`. After execution completes the temporary option file is removed automatically. Therefore the command line executed wouldn't give you much information.

The next problem is Windows' rather limited maximum command line length. Even if the GUI were to list the full command line with all options chances are that simply copying & pasting them into `cmd.exe` wouldn't work due to said limitation. That limitation is the reason why the GUI uses an option file in the first place (and in order to avoid problems with Unicode characters and Windows' abysmal command line handling).

You can let the GUI create an option file for manual use, and you can let the GUI give you the full command line. Both options are available in the multiplexer's menu ("create option file" and "show command line" respectively).

If you need the command line options for a job in the job queue, you can right-click on that job in the "jobs" tool and select "edit in corresponding tool and remove from queue". Afterwards use one of the options mentioned above. This can be done even after a job's already been run.

**Comment by tapiau** [comment]
Cool.

Thanks for very helpful answer. That solves my problem.
