### ISSUE TITLE
Mkmerge --identify-verbose Should Indicate If a Track Is Subset of Other Track

### ISSUE THREAD

**Issue by CarlEdman** [mbunkus/mkvtoolnix#1835]
This may sound like an esoteric complaint, but please hear me out.  

Some currently popular audio codecs, like DTS-HD Master Audio, contain both a lossless version of the track and a lossy version of the track in an older codec.  The MKV tools reasonably represent this single track as two separate tracks--a lossless one for those devices which can handle it and a lossy one for the rest.

For example, mkvmerge --identify-verbose would contain these lines:
```
Track ID 1: audio (DTS-HD Master Audio) [audio_bits_per_sample:24 audio_channels:6 audio_sampling_frequency:48000 codec_id:A_DTS codec_private_length:0 default_duration:10666666 default_track:1 enabled_track:1 forced_track:0 language:eng minimum_timestamp:0 number:2 track_name:Surround\s5.1 uid:2]

Track ID 2: audio (DTS) [audio_channels:6 audio_sampling_frequency:48000 codec_id:A_DTS codec_private_length:0 default_duration:10666666 default_track:0 enabled_track:1 forced_track:0 language:eng minimum_timestamp:0 number:3 track_name:Surround\s5.1 uid:3]
```

So far so good.

My problem is that my tools interpret the output of mkvmerge --identify-verbose, can handle the lossless formats, but have no way of knowing that certain lossy tracks are redundant (apart from guessing that any DTS track following a DTS-HD Master Audio track must be redundant).  So I end up with a lot of redundant tracks I have to delete manually.  (And mkvinfo does not contain this information either.)

So what I am asking for is some hint in the output that would indicate something along the lines of "if you can deal with this track, don't bother dealing with this one."  There is probably a small audience for this, but I suspect it is also small effort.

Thanks!

**Comment by mbunkus** [comment]
Thanks for the suggestion. I'll add such a property.

Note that I've just [deprecated the `--identify-verbose` option](https://github.com/mbunkus/mkvtoolnix/commit/f35ba20dc33140daba218945a389acf2e23556e9). It'll be removed in 2018. If you're using that option please change your tooling to use `--identification-format json --identify …` instead which outputs the same information, just as a JSON document.

**Comment by mbunkus** [comment]
Just a side note. DTS HD-MA and DTS tracks are usually not multiplexed within the same source track. Therefore mkvmerge will not add any indication that they might contain the same source material, simply because mkvmerge doesn't know whether or not that is the case.

There are currently only two situations in which mkvmerge presents tracks multiplexed into a single source track as separate tracks:

1. TrueHD with embedded AC-3 cores (e.g. in MPEG transport streams)
2. Teletext subtitles in MPEG transport streams

What mkvmerge can do for DTS HD-MA is to remove the HD-MA part and only keep the core. However, that's only available as a switch for that DTS HD-MA track. The core-only DTS data is not exposed as a separate track by mkvmerge. Therefore the new identification properties I'll be adding won't be shown for DTS (HD-MA) tracks. They simply wouldn't apply there.

**Comment by CarlEdman** [comment]
Thanks for the clarification!  

I thought they were always multiplexed because every single time I see a HD-MA track, I see a DTS track with identical content next.  I believed this happened because the DTS track had been embedded in the HD-MA track.

Do I understand you correctly that when this happened there really are two completely separate tracks, one HD-MA and one DTS?  That seems like a waste of bandwidth, considering that it is technically possible to embed the DTS in the HD-MA.

**Comment by mbunkus** [comment]
> Do I understand you correctly that when this happened there really are two completely separate tracks, one HD-MA and one DTS? That seems like a waste of bandwidth, considering that it is technically possible to embed the DTS in the HD-MA.

That's exactly what happens, yes. I guess Blu-rays simply have the space to spare, and it's likely done for the best possible compatibility with devices out there.
