### ISSUE TITLE
.srt file error...same as 1749

### ISSUE THREAD

**Issue by tk-xp** [mbunkus/mkvtoolnix#1837]
same error occured as 1749 was....i am sending the srt file in pdf format..kindly solve this...
[www.TamilRockers.ac - Kodi (2016)[HDRip - x264 - 400MB - ESubs - Tamil]-ESubs.pdf](https://github.com/mbunkus/mkvtoolnix/files/674187/www.TamilRockers.ac.-.Kodi.2016.HDRip.-.x264.-.400MB.-.ESubs.-.Tamil.-ESubs.pdf)

'The ﬁle was not recognized as a supported format (exit code: 0)"- this error is showing

**Comment by mbunkus** [comment]
First of all, please don't just post stuff in old, closed bug reports. Your issue is completely different from the original submitter's, and the original submitter is generally not interested in your particular problem. Open new issues instead.

An SRT file is a plain text file that can be opened with any capable text editor (don't use Windows' Notepad). It consists of groups of at least four lines each:

1. the line with the running number,
2. the line with the start and end timecode,
3. one or more lines of text and
4. one blank line as a separator.

Here's an example of how a valid file could look:

```
1
00:00:04,700 --> 00:00:06,736
where are you going so early?

2
00:00:06,900 --> 00:00:09,494
Don't record any more messages
on my alarm clock.
```

In your file the lines with the running numbers are missing. Add such lines manually, and you should be good to go.

**Comment by tk-xp** [comment]
running number means?

**Comment by tk-xp** [comment]
ok...thank u....
