### ISSUE TITLE
Attachments not showing up in GUI

### ISSUE THREAD

**Issue by dragoncb234** [mbunkus/mkvtoolnix#1870]
So I drag an attachment or a group of attachments say CANDARA.TTF into the attachments section on the GUI. But nothing shows up in the section. However if I drag the attachment over again it says that the attachment is there and asks if you want to add it a second time. Not sure why mkvtoolnix is doing this. But it won't show extra attachments in the GUI added by the user. Only the ones muxed onto files show up in the attachments section.

**Comment by mbunkus** [comment]
The "Attachments" tab shows two list view: the upper one contains the attachments from existing source files, the lower one attachments the user wants to add. Dragged & dropped files show up in the lower list view.

If your "Attachments" currently shows only one list, then you've dragged the slider between the two list views all the way to the bottom so that the lower list view is currently hidden. Just hunt for the slider with the mouse; it should currently be located right above the "Setings" group box, and drag it upwards.

**Comment by dragoncb234** [comment]
oh wow I feel dumb now. Thanks
