### ISSUE TITLE
Warnings about garbage in AC-3, MP3 no longer working

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1872]
Hello,

MKVToolNix once output warnings about A/V sync for AC-3 and MP2/MP3 tracks when garbage data in such tracks was omitted. As has been requested in #1420 it even output the last timecode before the garbage data for troubleshooting purposes. But since version 8.7 (probably [this committ](https://github.com/mbunkus/mkvtoolnix/commit/f4fbf0c59198311b46b72628158960329d72f380) in response to #1553) this isn't working anymore. Could this useful feature be fixed? Thanks in advance.

Greetings
Andi

**Comment by mbunkus** [comment]
No, sorry, at least not if the problem is really due to incomplete PES packets in the source TS file. Throwing those away before their data is even sent to the packetizer is the right thing to do.

You can verify whether or not that warning still works by taking a raw `.ac3` file, concatenating some non-AC-3 data and again the original `.ac3` into a big file, and feeding that file into mkvmerge. E.g. with bash:

```
cat file.ac3 other_file.mp3 file.ac3 > with_garbage.ac3
mkvmerge -o out.mka with_garbage.ac3
```

**Comment by mkver** [comment]
I did your check and the message appeared. Would it be possible to output warnings for incomplete PES packets in the middle of a transport stream?

**Comment by mbunkus** [comment]
Technically possible? Yes. Useful? Less so. There are tons of TS files that have a lot of those errors, especially with DVB recordings. The user would be flooded with such warnings and would quickly learn simply to ignore them.

Warnings are useful for stuff that doesn't happen too often, but pretty much useless for stuff happening often.

Therefore: won't do it.
