### ISSUE TITLE
h.264: option to treat all I frames as key frames

### ISSUE THREAD

**Issue by lukjak** [mbunkus/mkvtoolnix#1876]
Hello,

I mux an MTS file from my Canon HF100 camera (default settings) - just a single file to mkv with default settings.
When skipping on timeline in player for the resulting file, playing hangs for some time, as it would need to play internally whole file up to the clicked moment.
Tried with MPC-HC and VLC stable and MPC-HC latest nightly.
Uploaded sample file to FTP.

**Comment by mkver** [comment]
What's the video codec of the file? Does it have keyframes? Is the MTS-file seekable? (If the answer to the latter question is yes, then mkvmerge probably doesn't recognize the keyframes in your file and therefore creates a suboptimal index.)

**Comment by lukjak** [comment]
Sample available here: https://www.dropbox.com/s/ea5thqih2t6zeuy/Ogrodzenie-17.MTS?dl=0 (if you still prefer to have text answers, just let me know).

**Comment by mkver** [comment]
Your video stream contains lots of I-frames, but only one IDR frame. These I frames haven't been flagged as recovery points, so mkvmerge (and ffmpeg by the way) don't treat them as keyframes (that I frames can be don't need reference frames to decode them does not automatically make them random access points (only these are really seekable keyframes), because it does not ensure that frames which follow the I frame in presentation order are properly decodable (they may depend on stuff before the I frame)). But in your instance the I frames seem to be seekable. I have tested it with [eac3to](https://forum.doom9.org/showthread.php?t=125966) which has an option to declare every I frame to be a keyframe (-seektoIFrame). It depends on the presence of [Haali's matroska muxer](https://haali.su/mkv/). That way you can create a matroska file where the I frames are keyframes; unfortunately the cues (the index) of the resulting file was rather garbage (and the file was strange in more than one way: it contained multiple "segment information" elements and there was more than one track element (with subelements) for the video stream; it used a wrong default duration for the video stream (all timecodes are ok, just the header element is wrong)); moreover it didn't contain the audio. But luckily MKVToolNix came to the rescue: If you remux this file, it's ok (seeking works well). mkvmerge seems to ignore the second segment information.
There would be a way to do this without eac3to: Replicate the "seektoIFrames" option of eac3to in mkvmerge. As already been mentioned, I frames are in general not random access points and therefore not necessarily keyframes, so this should not be the default; I'm thinking of an --engage-switch.

**Comment by lukjak** [comment]
It looks like Canon engineers had their own view on things.
--engage would be perfect - could it be added to mkvtoolnix at some time?

**Comment by mkver** [comment]
I cannot promise anything (only Moritz can do this), but he actually had done something like this in response to #1671 (not with an user selectable switch, but as default). He reverted it (see the discussion yourself). Maybe such a switch would be an acceptable solution to both issues.

**Comment by mbunkus** [comment]
MP4Box agrees with what @mkver has written, none of those I frames are key frames or valid random access points. Therefore this is not a bug in mkvmerge.

**Comment by remuxer32** [comment]
**@lukjak**

New pre-builds for Windows that contain the new option (`--engage all_i_slices_are_key_frames`) have been uploaded here: https://mkvtoolnix.download/windows/pre/

**Comment by lukjak** [comment]
Confirmed OK with build20170129-01422-12bd3022a.
Thanks to all involved.
