### ISSUE TITLE
Video track gets duplicated when added to the GUI

### ISSUE THREAD

**Issue by stevek123** [mbunkus/mkvtoolnix#1877]
When adding an MP4 file in the GUI (the same type as my previous issue), something goes wrong when it's parsed, and it thinks that there are 2 video tracks in the file, and results a corrupt, duplicated output. I'm using the 64bit 9.8.0-build20170127-01420-f75a9c88c version on Win10. I have uploaded the MP4 to your FTP server.

**Comment by mbunkus** [comment]
Thanks. This is a regression introduced in the fix for #1867.

**Comment by remuxer32** [comment]
New pre-builds that contain the fix have been already uploaded: https://mkvtoolnix.download/windows/pre/

**Comment by stevek123** [comment]
The bug was there in the latest stable too, so I don't think that the issue was introduced by the fix. I have tried with the latest stable, and with the latest pre-build (build20170129-01422-12bd3022a), and the issue is still present with the provided sample file.

**Comment by mbunkus** [comment]
The issue was definitely present in the latest release, and the entry in NEWS.md says as much. The fix for #1867 just makes it much more likely to occur; that's where my initial assumption that it was caused by that fix came from.

However, I cannot reproduce the problem with pre-build build20170129-01422-12bd3022a anymore and still consider it fixed.

**Comment by stevek123** [comment]
Oh, I see. It is indeed fixed, sorry about that. I forgot to delete the user data folder. Thank you for your help!
