### ISSUE TITLE
Extend Append Function to Chapter Files from Command Line

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#1879]
Hello, as always, great work, **mkvtoolnix** is wonderful.  Can the append function be extended to include chapter files appended from the command line?  To clarify, chapters embedded in containers append appropriately, but separate chapter files do not append as expected.

For example, this fails...

`$ mkvmerge -o example.mkv disc_1.vob +disc_2.vob --chapters disc_1.chapters +disc_2.chapters`

>Error: The file 'disc_2.chapters' has unknown type. Please have a look at the supported file types ('mkvmerge --list-types') and contact the author Moritz Bunkus <moritz@bunkus.org> if your file type is supported but not recognized properly.

Both of these fail too...

`$ mkvmerge -o example.mkv disc_1.vob +disc_2.vob --chapters disc_1.chapters --chapters +disc_2.chapters`
`$ mkvmerge -o example.mkv disc_1.vob +disc_2.vob --chapters disc_1.chapters --chapters disc_2.chapters`
>Error: Only one chapter file allowed in '--chapters disc_2.chapters'.

A workaround is to add the chapter files into containers (with accompanying audio/video), then process those interim files; **mkvmerge** correctly appends the chapters in order with correct duration/time...

`$ mkvmerge -o disc_1.mkv disc_1.vob --chapters disc_1.chapters`
`$ mkvmerge -o disc_2.mkv disc_2.vob --chapters disc_2.chapters`
`$ mkvmerge -o example.mkv disc_1.mkv +disc_2.mkv`
`$ mkvmerge -i example.mkv`
> File 'example.mkv': container: Matroska
Track ID 0: video (MPEG-1/2)
Track ID 1: audio (AC-3/E-AC-3)
Track ID 2: audio (AC-3/E-AC-3)
Track ID 3: audio (AC-3/E-AC-3)
Track ID 4: audio (AC-3/E-AC-3)
Track ID 5: audio (AC-3/E-AC-3)
Track ID 6: audio (AC-3/E-AC-3)
Track ID 7: audio (DTS-ES)
Chapters: 50 entries

Of course, the workaround doubles processing time and space requirements.  Please advise, thank you.

**Comment by mbunkus** [comment]
The big problem with allowing chapter-only files as source files is that mkvmerge needs to know a file's duration in order to be able to shift the timestamps of appended files properly. In general this property isn't known for files containing only chapters. One exception is XML chapter files that use `ChapterTimeEnd` elements for each entry, but that's the minority of chapter files people actually use.

Therefore you'd also need a way of telling mkvmerge how much to offset the timestamps of the appended files requiring new options, new documentation, new GUI controls etc. A lot of work for little practical gain. And nothing I want to implement. Sorry.
