### ISSUE TITLE
Muxing with mkvmergeGUI = audio delay

### ISSUE THREAD

**Issue by heffnurr** [mbunkus/mkvtoolnix#1892]
Hello there!

So I'm trying to make a remux from a Blu-ray disc. I extracted the video, audio and sub tracks with eac3to and then I added them to mkvmergeGUI. Muxing finished successfully (no errors/warnings), but when I played the fresh .mkv I noticed there's a slight delay in the audio. When I play it from the BD source it's perfect. The movie's using VC-1/DTS-HD MA.

The only settings I've changed in mkvmergeGUI are the FPS on the video track = 23.976, and the compression = none. Nothing else.

Can anyone help me out? Thanks in advance! I'm sorry if this has been answered somewhere.

**Comment by mkver** [comment]
1. You should not change the FPS; changing it makes the video play with a different speed than before (except in the case where you set it to the value it already had) and so audio and video gradually change their sync.
2. Just mux the BluRay m2ts-file (or even better: the relevant playlist which also contains the chapter information) direct with MKVToolNix. If this results in a file with A/V asynchronity, then you have probably hit a bug in MKVToolNix (but chances are that this won't happen).

**Comment by heffnurr** [comment]
@mkver - Hey, I just tried with mkvmergeGUI again, without touching any settings. Simply inserted the tracks and the delay is there. So it wasn't the FPS.
Well, I've extracted the video track as a RAW file (.vc1). Are you suggesting that this time I extract the m2ts/playlist with eac3to, and then mux them with MKVToolNix?

**Comment by mkver** [comment]
No, you can directly add the playlist as a source file to MKVToolNix.

**Comment by heffnurr** [comment]
Oh, okay. It's just that I've been told by certain individuals that demuxing with eac3to is the best way, because it checks for all kinds of errors and fixes them in the process. That's why I've read -
demux = eac3to, then mux the parts with mkvmergeGUI. Do you have any comment on that?

 I'll take your advice and respond back in a few. Thank you!

**Comment by heffnurr** [comment]
@mkver - Thank you so much. It worked. It's appreciated!

**Comment by mbunkus** [comment]
First of all: are you really using mkvmergeGUI? That program has been removed from the MKVToolNix package almost two years ago. If you're still using it, please upgrade to the latest MKVToolNix version first (v9.8.0 at the time of writing). MKVToolNix GUI is the actively-maintained GUI for mkvmerge.

Second: extracting tracks into individual files always loses information, first and foremost the timestamps and thereby the mapping between them (which frame from track 1 to show/play together with which frame from track 2 etc.). Therefore A/V sync problems are to be expected. Extraction into single files is only advisable if you know what you're doing or if you need to process such tracks (e.g. edit audio with an audio editor).

The preferred way of multiplexing Blu-rays is by using the playlist files (`PLAYLIST\*.mpls`) as input files. MKVToolNix GUI will even offer to scan all existing playlists and present you with an analysis of each allowing you to chose which to use.

**Comment by remuxer32** [comment]
Hello **@heffnurr**.

Like **@mbunkus** has said: mkvmerge GUI was removed from the MKVToolNix package a long time ago and it's not supported anymore. If you want to know why, you can read more details here: 

- https://github.com/mbunkus/mkvtoolnix/wiki/MKVToolNix-GUI 

You can always download the latest version of MKVToolNix from this site: 
- https://www.fosshub.com/MKVToolNix.html 

Nowadays you really should use MKVToolNix GUI which is much better and more advanced than the old GUI. But if, for some reasons, you still prefer using the old GUI, then be prepared for many bugs, as the old interface has them a lot. Beside mkvmerge GUI, the old versions of mkvmerge have tons of bugs, too, so I strongly recommend you to use (always!) the latest MKVToolNix version which always contains fresh bug fixes and also new features. I know that there are users who don't like the new interface (MKVToolNix GUI) because they argue that it's more difficult to use than the old one, but you should give it a try and create your own, independent opinion abot the new GUI. I hope you will be satisfied.

And now some more tips for you:

1. This place is a bug tracker where the users create bug reports and/or feature requests to the project. This is **not** a forum to ask general questions like yours. As you can easily see, your issue is not a bug report nor a feature request; therefore it has been closed as invalid. If you want to get help from people who have great knowledge about such things, you shoud visit the following forums: 

- https://forum.doom9.org/ 
or
- http://forum.videohelp.com/

2. As **@mkver** has said: you shouldn't have changed the FPS; it should be always untouched, unless you are an expert and you know exactly what to do. The same applies to extracting tracks via eac3to: never do that, as you can lose very important information and may encounter problems with A/V synchronization. But if, for the future, you really need to extract some tracks from an `.m2ts` file, you can use **tsMuxeR** instead of eac3to. tsMuxeR is a simple tool with a nice interface that allows you to extract any tracks from your Blu-ray Disc (`.m2ts` files), and even is able to extract the DTS core from DTS-HD audio tracks, as well as the AC-3 core from Dolby TrueHD audio tracks. But you should be careful because tsMuxeR is, unfortunately, not supported anymore (the latest release comes from 2014) and has many bugs. Anyway, if you want, you can download that nice app from here: 
- http://www.videohelp.com/software/tsMuxeR

3. I have created many Blu-ray remuxes in my life and — from my own experience — I can tell you that MKVToolNix is a fantastic app for doing that. All you have to do is add a playlist (an `.mpls` file) from the PLAYLIST folder to the GUI. Afterwards the GUI will ask you what to do with a file; you can choose, for example, scanning the whole directory. After that you should be able to see many playlists to add. Question is: how should I know which one to add, as there are tons of them? The answer is simple: the one that contains the longest duration (the main movie). But sometimes you can meet several playlists that contain the same longest duration. And then what to do? Then you can use the next nice app; its name is **BDInfo**. BDInfo is a tool that allows you to scan your whole Blu-ray Disc and then to show you all of the playlists which are located in the PLAYLIST folder. You will see the proper playlist (usually the first one) you should add to the GUI. BDInfo can be downloaded from this site:
- http://www.videohelp.com/software/BDInfo

4. But if you don't want to analyze which playlist should be added, you can use the next wonderful app for creating Blu-ray copies. I mean **MakeMKV**, of course. MakeMKV is a well known brand for handling Blu-rays and DVDs, which will do everything instead of you (no need to add a playlist). All you have to do is to insert your disc into your drive or, if you have your BD on your hard drive, add a `movieobject` file, for example. Afterwards MakeMKV will start opening your Blu-ray Disc and then it will show you suitable titles. Again: which one to choose? This time the one that has the largest size (usually more than 30 or 40 GB). Obviously MakeMKV allows you to select or deselect your favourite audio/subtitle tracks. Personally I use MKVToolNix and MakeMKV interchangeably. You can easily download MakeMKV from the official site: 
- http://www.makemkv.com/download/

5. Usually the main movie on a Blu-ray Disc is located in one `.m2ts` file, but sometimes it's divied into several (or even over a dozen!) smaller or bigger `.m2ts` files (e.g. if you have a release with two versions of a movie; theatrical and director's cut). In such situations the only right way is to add a playlist to the MKVToolNix GUI and allow to scan the whole directory. But if you have a release where the main movie is located in one file only, you can add such a file directly. But you need to know that using that way you won't get any chapters, as chapters are located in another place (`.m2ts` files never contain chapters). So, where are they located? In a playlist, of course. Anyway, I always recommed to add a playlist to scan.

This would be enough, I think :) BTW: what is the name of your Blu-ray Disc (the movie title)? Thanks.

**Comment by heffnurr** [comment]
Wow, thanks a lot for all the information. I will read up on it. The movie in question is Scarface (1983). :)

**Comment by remuxer32** [comment]
Yes, »Scarface« is a great movie :) I've just found out that this BD release contains two VC-1 streams: 1080p & 480p in one `.m2ts` file, right? Did you choose the first one to mux or both of them? I personally prefer 1080p only. And the proper `.mpls` file is 00800, yes? If so, then the proper` .m2ts` file is 50201, right? :) I mean the CEE release. Probably you have the same.

**Comment by heffnurr** [comment]
@remuxer32 - I have the US one. But they're all the same. :) The correct file is 00800.mpls, yes. Sometimes I think I'm being paranoid you know, trying to find a problem where there isn't one. I think it's all good. :)

**Comment by remuxer32** [comment]
Not a problem :) I'm glad I could help you. As a curiosity I can tell you that VC-1 is not used on Blu-rays anymore. Instead, MPEG-4 AVC is used in every BD release at the moment. And I'm happy, as MPEG-4 is better than VC-1. VC-1 releases had lower video bitrates and sometimes worse video quality. This is a very good example where a BD release with VC-1 is worse and MPEG-4 AVC is better:
- http://caps-a-holic.com/c.php?d1=488&d2=487&c=55

Apart from video quality, the BD release with MPEG-4 AVC has better sound: DTS-HD Master Audio 5.1 instead of plain AC-3.

**Comment by remuxer32** [comment]
**@heffnurr**

>  Is there a way to contact you? e-mail?

Yes, you can contact with me if you want. This is my e-mail address: janmazurczyk@gmail.com
