### ISSUE TITLE
no "add attachment" button in MKVToolNix GUI 

### ISSUE THREAD

**Issue by DuctTapeSoftware** [mbunkus/mkvtoolnix#1906]
Before (in version 6.3.0) in the attachment tab there was a button to add attachment from my files, now (version 9.9.0) this button is gone. Is it a bug? How could I add attachment now?

**Comment by remuxer32** [comment]
Hello.

In the new GUI (MKVToolNix GUI) you can add attachments via the context menu. In order to invoke such a menu, you have to right-click on the pane. See, please:

![attachments](https://cloud.githubusercontent.com/assets/10992208/23913404/32692d44-08e3-11e7-9220-08ecaeef69d1.png)

You can also drag & drop attachmenta into the pane.

**Comment by DuctTapeSoftware** [comment]
** remuxer32**, thank you! Well, I am changing my topic to "is it possible to get back add button" as before it was much more usable and intuitive.

**Comment by remuxer32** [comment]
> "is it possible to get back add button"

Well, I'm not an author of MKVToolNix, just a collaborator, so I'm not able to answer this question; only the author can. But the philosophy of the new GUI is **the fewer buttons, the better**, therefore I suspect that it is rather impossible.

**Comment by mbunkus** [comment]
As @remuxer32 has said, I won't add such buttons.
