### ISSUE TITLE
Audio Issue

### ISSUE THREAD

**Issue by WarioLand** [mbunkus/mkvtoolnix#1931]
I have a .mkv file with more than a language and subtitles.
I edit it with mkvtools removing any junk language/subtitle.
After that the output file (.mkv) has audio that blink, but not the video.
Source mkv file instead is ok.

Why I have this problem? How to avoid it?

**Comment by mbunkus** [comment]
Your description doesn't tell me enough to say anything about the why or how to avoid it. Can you please upload the source file to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can take a look, please?

I'll also need the exact settings you've used. For that re-create the settings in MKVToolNix GUI, select "Show command line" from the "Multiplexer" menu and copy & paste the command line here.

Thanks.

**Comment by WarioLand** [comment]
The source file weight is 12gb.

I opened "Show line form" and it gives me this
`"C:/Program Files/MKVToolNix\mkvmerge.exe" --ui-language it --output ^"^"`

**Comment by mbunkus** [comment]
Like I said, I'll need access to the source file. Without it I won't be able to do anything about this. If the file is too big for you to upload, then that is perfectly understandable, but in that case I won't be able to help you.

**Comment by mbunkus** [comment]
Closing due to lack of material to test with.
