### ISSUE TITLE
Greek subtitles problem

### ISSUE THREAD

**Issue by MakisKarousos** [mbunkus/mkvtoolnix#1933]
when adding any of the greek subtitles with an .srt file is cutting the last word when sentence is long

**Comment by mkver** [comment]
Are you sure that it is MKVToolNix doing this and not your video player? (Just extract the subtitles with e.g. mkvextract and see for yourself whether the last word is in there.)

**Comment by MakisKarousos** [comment]
Dear sir

When I do not declare the language ( ie Greek ) and subtitles are not declared  (ie. und) then is not doing it.

Regards

Makis

**Comment by mkver** [comment]
So you say it only happens when you declare the language of the track? I highly doubt that. Can you provide a sample file?

**Comment by MakisKarousos** [comment]
Yes and as well the quality of the letters is no good (when you declare)  not all letters but som of then like Ξ And ζ.

**Comment by mbunkus** [comment]
Please upload a sample SRT file somewhere, e.g. [to my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server), so that we can take a look at the problem. Thanks.

**Comment by MakisKarousos** [comment]
This is a srt file

**Comment by mbunkus** [comment]
You're replying via email, and I'm guessing that you've attached a file to that email. That won't work. Your replies are stripped of all attachments before they're entered into the bug tracking system; therefore I don't have access to the attachments.

Like I said: please upload such a file somewhere. Don't try to send it via email.

**Comment by MakisKarousos** [comment]
I do not know how to do this. Sorry

**Comment by mbunkus** [comment]
Please read the following page which explains which program to use and where to connect: https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server

It's really not difficult.

**Comment by MakisKarousos** [comment]
Permission denied.
Error code: 3
Error message from server (en-US): Permission denied

**Comment by mkver** [comment]
You can also upload small files directly to GitHub (you just have to rename it to a txt-file:
[example.txt](https://github.com/mbunkus/mkvtoolnix/files/896376/example.txt)

**Comment by MakisKarousos** [comment]
[sample1.txt](https://github.com/mbunkus/mkvtoolnix/files/896421/sample1.txt)

**Comment by mbunkus** [comment]
Alright.

1. Which entries are cut off?
2. Which entries show bad characters?

**Comment by mkver** [comment]
I have just muxed it together with a video file (and set the language to (modern) Greek) and compared the muxed track to the original one: No difference. And [long lines](https://imgur.com/a/C9km2) worked, too. So I really think that this is your player, not MKVToolNix.

**Comment by MakisKarousos** [comment]
I noticed that the problem appear when there is not  a full stop in  the sentence. It disappears the last word. I noticed that comparing the hearing with the written. Is not all time ....

**Comment by mkver** [comment]
You compared what you heard to what is written? I can absolutely assure you that MKVToolNix does not analyze the speech in the audio tracks (it simply can't; it only scans the audio a bit to determine the type of codec, the sampling frequency and the number of channels, but nothing more).
And I just looked at subtitle lines 3 and 6: Both don't have a full stop and both are shown as they are in the file you uploaded. If the file you uploaded is the file that you have muxed into the matroska file, then that's just the way the subtitles were.
If these subtitles are the ones that you extracted from the matroska file you created and if they differ from the ones that you muxed into the file, then we would have a bug. But in order to analyze this situation we'd need the subtitles that you wanted to mux into the matroska file, not the subtitles that came out of it.

**Comment by mbunkus** [comment]
Like @mkver I cannot reproduce words missing. What's present in the file is presented during playback with VLC. What you're experiencing is not a bug in MKVToolNix.
