### ISSUE TITLE
Adding subtitle sometimes gives wrong time lenght

### ISSUE THREAD

**Issue by ozeloten** [mbunkus/mkvtoolnix#1940]
I often download .flv WEB-DL and the corresponding subtitles.
Then sometimes, not often, when I mux the subtitles the time lenght changes drastically.
For example from 28m40s to 10m00.00s
As I remember the time is changed to 10m00.00s whenever it goes wrong.
Making an .mkv from the .flv without adding the subtitles preserves the right time
Adding the subtitle to this .mkv again results in 10m00.00s
I can upload some files with this anomaly if necessary.

**Comment by ozeloten** [comment]
Playing the .mkv without subtitles made from .flv and choosing external subtitles (add subtitle) in VLC works perfectly.

**Comment by mbunkus** [comment]
Please upload such files (the `.flv` and the corresponding subtitle file) to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by mbunkus** [comment]
Thanks for the upload.

Your description is slightly wrong; the duration is not 00:10:00 (which would be ten minutes) but 10:00:00 (ten hours). This is due to your subtitle file. Its last entry is at timestamp 10:00:00. Therefore the last content in the file is at that position, and consequently the total file duration is 10 hours.

This is working as intended. No bug.

I highly suggest you edit the subtitle file and remove that last entry.

**Comment by ozeloten** [comment]
Thanks for your reply.
I'm sorry that I have bothered with such a trivial thing.
But I'm very glad for your answer because I never thought about controlling the time codes in the subtitle file.
