### ISSUE TITLE
Minor Header Edits Cause MediaInfo not to see DTS-HD MA

### ISSUE THREAD

**Issue by alexsisk** [mbunkus/mkvtoolnix#1947]
Hi,

I'm running the MkvToolNix GUI v 10.0.0 on macOS Sierra.

Videos that I used HandBrake to encode were, I thought, coming out the other end with incorrect audio data. (DTS-HD Master Audio is no longer seen by MediaInfo, though my receiver sees it.) I was almost ready to submit a bug report to HandBrake, when it occurred to me that I needed to do a test, as I frequently update minor header items like language, (und ---> eng) track name, and I add on a poster image.

I've always done this by remuxing, as I thought you had to in order to attach a file, and then I figured out that I could just use the Header editor.

I noticed on some files, MkvToolNix still showed DTS-HD Master Audio / as the codec, but not MediaInfo. It simply showed DTS 6 Channels (dca). I haven't done this test yet with an Atmos / TrueHD file, but I will soon, to see if it drops the Atmos. It may only be related to DTS-HD MA.

So I tested the file straight out of handbrake, and then made a copy for the 2nd and 3rd tests: 

Test 1 - Straight out of HandBrake [MediaInfo]: DTS-HD Master Audio / Core
Test 2 - Edited and saved with MkvToolNix **Header editor** [MediaInfo]: DTS (dca) only
Test 3 - **Remuxed** with MkvToolNix [MediaInfo]: DTS-HD Master Audio / Core

MediaInfo and MkvToolNix, Same File after Test 2:

![screen shot 2017-04-16 at 11 33 05 am](https://cloud.githubusercontent.com/assets/18446260/25078156/83d78fc4-22fe-11e7-885b-24a8a3bb0fa5.png)

**Comment by mkver** [comment]
This does not look like a bug in MKVToolNix; it seems to be a bug in Mediainfo. I don't see a good reason why mediainfo's output should change. After all, whether a file is only a DTS core or a core+some extension can only be determined by looking at the bitstream, because the header contains only that it is DTS.
Maybe mkvpropedit has relocated the track information to the end of the file and mediainfo know for some reason (no good reason, of course) changes its output. (There was a similar issue (#1895).) But anyway, this is not a bug in MKVToolNix and you should tell the mediainfo developers if you want this behaviour to be changed.

**Comment by alexsisk** [comment]
Thank you for getting back to me so quickly.

I understand what you're saying ("A_DTS" can mean almost any DTS variation).
![screen shot 2017-04-17 at 12 30 49 am](https://cloud.githubusercontent.com/assets/18446260/25078871/3f71da04-2305-11e7-9c04-27c447b0121d.png) 

What is the difference in _MkvToolNix output_ (remux vs header edit)?

1) Remux - MediaInfo shows DTS-HD MA
2) Edit header - MediaInfo shows Core only

Because the result is different based on which part of MkvToolNix I use, I worry that they will blame MkvToolNix and then I don't get anywhere. But I thought about it and I understand it could output different info. Do you have a suggestion on the best way to ask MediaInfo so that they actually think about it?

**Comment by mbunkus** [comment]
This is not a bug in MKVToolNix. What mkvpropedit creates is perfectly valid and follows the Matroska specification. See [this FAQ article](https://github.com/mbunkus/mkvtoolnix/wiki/All-tracks-vanished-after-mkvpropedit,-the-header-or-chapter-editors) for more information on what mkvpropedit has to do in certain situations.

**Comment by mkver** [comment]
When you use the header editor, the size of the header may change (obviously) and if there is not enough reserved space at the beginning of the file, then the header editor uses a feature of Matroska called meta-seek-element: It references the actual header in a meta-seek element, i.e. it only writes where to find the actual information regarding the tracks at the beginning and the information about the tracks at the end of the file (the filesize may thus increase). You can find out whether this happened if you analyze the file before and after the changes the header editor did with mkvinfo. FFmpeg's muxer (which is the muxer used by Handbrake) usually doesn't reserve a lot of space at the beginning. MKVToolNix reserves about 4KB, allowing for the insertion of chapters into already muxed files.
PS: If I am not mistaken FFmpeg's muxer doesn't use a Matroska feature called "lacing" (whereby several audio frames are put into one block in order to save space) so that it is advisable to remux the files anyway.

**Comment by alexsisk** [comment]
Thank you! =) I'll share the situation and info you provided with MediaInfo so that they can hopefully improve their software - but I'm going to go back to remuxing even for small changes nonetheless.
