### ISSUE TITLE
Missing African language code sets

### ISSUE THREAD

**Issue by rhazor** [mbunkus/mkvtoolnix#1950]
e.g. http://www-01.sil.org/iso639-3/documentation.asp?id=kus
https://en.wikipedia.org/wiki/Kusasi_language

all of https://en.wikipedia.org/wiki/Languages_of_Ghana has own iso 639 codes

`Error: 'kus' is neither a valid ISO639-2 nor a valid ISO639-1 code. See 'mkvmerge --list-languages' for a list of all languages and their respective ISO639-2 codes.`

what to tag language when it's not available on mkvmerge?

**Comment by mbunkus** [comment]
Currently Matroska only uses ISO 639-2 codes, not 639-3. Therefore I cannot simply add codes to MKVToolNix, and I cannot really fix this.

> what to tag language when it's not available on mkvmerge?

I don't know enough about African languages in order to answer that. Sorry.

There has been a recent development of adding support for better language tags in the Matroska specification. However, that's really, really new, therefore there are no tools (neither on the producing side nor on the playback side) that support those already. Support for those elements will come in MKVToolNix one day, but it's a major undertaking that won't be finished any time soon.

**Comment by rhazor** [comment]
that's racist

/s
