### ISSUE TITLE
missing EVR.dll  error is occurred in 11.0

### ISSUE THREAD

**Issue by shuna** [mbunkus/mkvtoolnix#1955]

**Comment by shuna** [comment]
Sorry, I have sent you an unfinished report. This error was occurred from 11.0.0 on Windows Server 2012 R2.
There are no problem on 9.9.0.

**Comment by mbunkus** [comment]
You really have to be more specific. What exactly are you trying to do (please list all the steps)? What exactly happens? What's the exact error message if any?

Note that I've just run MKVToolNix GUI 11.0.0 on Windows Server 2012 R2 successfully. So it's really not obvious from your short description what your issue is.

**Comment by mbunkus** [comment]
My guess is that your Windows Server installation is lacking a role or feature. See e.g. [here](https://thetechbase.net/tutorials/articlewmvcore-dll-is-missing-server-2012/) for a similar case. MKVToolNix v11 now requires Windows' default multimedia framework, and that framework is indeed part of Windows Server 2012 if it's installed. Therefore I'm closing this bug.
