### ISSUE TITLE
The shortcut key to move to next opened job/tab

### ISSUE THREAD

**Issue by 9O29** [mbunkus/mkvtoolnix#1972]
is there a shortcut key to do this? i mostly do remuxing a tv series and anime. that way i have to open
12 to 100+ jobs/tabs all time and when i add/demux some track it will be much faster workflow if i can move to next opened job/tab with a keyboard.

just try to find some way to make my job done faster

and sorry for my english :)

**Comment by mbunkus** [comment]
Pressing `Ctrl-Tab` will focus the next tab, `Shift-Ctrl-Tab` will focus the previous tab.

**Comment by mmdd87** [comment]
This shortcut works only if curser is in the "destination file:" textbox. Otherwise Strg + Tab focus the next Tabs "Input", "Outout" and "Attachments"

Strg + Ctrl + Tab always focus the previous tab of this 3 Tabs at the moment. My issue is to change from MKV to MKV Tab, like seen on this screenshot:
![reiter](https://user-images.githubusercontent.com/29876549/27825648-7e85d144-60b0-11e7-9d4f-8a7b3dd04855.jpg)

**Comment by mbunkus** [comment]
I wasn't aware of that. I'll reopen the issue.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include the fix have been uploaded (build number 01522 and higher).
