### ISSUE TITLE
video displays all black

### ISSUE THREAD

**Issue by JJMartin1340** [mbunkus/mkvtoolnix#1973]
I have a lot of mpg video files of recorded TV programs I made in 2009, using some cheap digital recorder. The videos look good, but they are untrimmed, and I mistakenly set the frame rate to 30 per sec instead of 29.97, and the aspect is 3:2 not 4:3. The frame rate error means the audio gets a bit out of sync after an hour, but I can live with that (but it would be nice to know of a simple fix). My video editor I use to trim commercials out is Avidemux, so I convert the mpg files to avi using Super, then trim them. The resulting avi file plays fine (I use VLC), but still at aspect 2:3. I have often used MKVToolNix just to change the aspect ratio of a video, without a problem, until now. When I use it on these files, the output mkv file is the right size, but the video is all black. Any idea what's happening and how I can fix it?

**Comment by mkver** [comment]
The syncing issues can be fixed by selecting the appropriate value (most likely 30000/1001p) from the slider on the right of the Default duration/BPS field.
I don't know why the files don't play in VLC. Have you tried other players like MPC-HC? And MPC-HC actually can read mpg's itself. What happens if you leave the conversion to avi using Super out of the equation? Can it be played then (you can also use MKVToolNix to cut commercials out).

**Comment by mbunkus** [comment]
Please upload a sample file to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). What I need is the file that you're feeding into MKVToolNix.

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
