### ISSUE TITLE
[Regression] only first video stream of dvb-t2 recording since v12.0.0 found

### ISSUE THREAD

**Issue by nicodorn** [mbunkus/mkvtoolnix#1990]
I have a dvb-t2 ts recording of an entire transponder that has 5 channels, 10 audio streams, and 10 subtitle streams. ffmpeg lists the streams as follows: 

```
Duration: 02:00:02.14, start: 39911.671467, bitrate: 20578 kb/s
Program 2001
	Metadata:
		service_name    : ?ZDF HD
		service_provider: ?ZDFmobil
	Stream #0:11[0x83e]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 50 tbc
	Stream #0:21[0x848](deu): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 256 kb/s
	Stream #0:14[0x849](mis): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
	Stream #0:8[0x852](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
	Stream #0:22[0x853](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
	Stream #0:23[0x87a]: Unknown: none ([5][0][0][0] / 0x0005)
Program 2002 
	Metadata:
		service_name    : ?ZDFinfo HD
		service_provider: ?ZDFmobil
	Stream #0:7[0x8a2]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 50 tbc
	Stream #0:25[0x8ac](deu): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 256 kb/s
	Stream #0:12[0x8ad](mis): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
	Stream #0:10[0x8b6](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
	Stream #0:26[0x8b7](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
	Stream #0:27[0x8de]: Unknown: none ([5][0][0][0] / 0x0005)
Program 2003 
	Metadata:
		service_name    : ?zdf_neo HD
		service_provider: ?ZDFmobil
	Stream #0:15[0x906]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 50 tbc
	Stream #0:16[0x910](deu): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 256 kb/s
	Stream #0:9[0x911](mis): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
	Stream #0:17[0x91a](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
	Stream #0:18[0x91b](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
	Stream #0:19[0x942]: Unknown: none ([5][0][0][0] / 0x0005)
Program 2004 
	Metadata:
		service_name    : ?3sat HD
		service_provider: ?ZDFmobil
	Stream #0:28[0x96a]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 50 tbc
	Stream #0:24[0x974](deu): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 256 kb/s
	Stream #0:13[0x975](mis): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
	Stream #0:20[0x97e](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
	Stream #0:29[0x97f](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
	Stream #0:30[0x9a6]: Unknown: none ([5][0][0][0] / 0x0005)
Program 2005 
	Metadata:
		service_name    : ?KiKA HD
		service_provider: ?ZDFmobil
	Stream #0:0[0x9ce]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 50 tbc
	Stream #0:1[0x9d8](deu): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 256 kb/s
	Stream #0:2[0x9d9](mis): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 128 kb/s
	Stream #0:3[0x9e2](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
	Stream #0:4[0x9e3](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
	Stream #0:5[0xa0a]: Unknown: none ([5][0][0][0] / 0x0005)
No Program
	Stream #0:6[0x1114]: Unknown: none
```

Until v11.0.0 I could open files like that with MKVToolNix GUI and mux the streams I want to keep in a mkv file. Since v12.0.0 MKVToolNix GUI shows only one video stream (in this case program 2005) and all 10 audio streams - at least in this case. Opening a recording of a different transponder resulted in showing only one video stream and the two corresponding audio streams. Besides subtitle streams nothing else showed up.

Please tell me if you need more info.

**Comment by nicodorn** [comment]
A picture is worth a thousand words ;)

![streams](https://cloud.githubusercontent.com/assets/14349333/26281580/838beb10-3dfb-11e7-89e3-2b18b99deccd.png)

**Comment by mbunkus** [comment]
Please upload a sample file to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can take a look. Thanks.

Note that I'll be out of town for several weeks. I will most likely not have time to look into it before I get back.

**Comment by nicodorn** [comment]
Thank you!

I did two recordings from two different transponders, each 1 min. long, and uploaded them to your server. I did two because each one behaves slightly different:

- "Bug #1990, Transponder 2.ts" gives me the exact result you can see in the picture above: 1 video stream, all audio streams listed.
- "Bug #1990, Transponder 1.ts" does only list 1 video stream, and two audio streams despite the file has 5 video an 12 audio streams.

**Comment by mbunkus** [comment]
Thanks. The issue is that your streams contain multiple programs. mkvmerge simply doesn't support selecting the program to use. It just uses the first program.

At the moment I have no plans for adding support for program presentation and selection. I'll leave this report open, though, as it would be a useful feature to have in general. Just don't expect a solution any time soon.

**Comment by mbunkus** [comment]
That mkvmerge finds certain streams from different programs (or doesn't find them) is more or less an accident. Like I said, proper support for programs is simply not present.

**Comment by nicodorn** [comment]
An accident that worked just perfectly until v11 ;)

But okay, I'll dump MKVNixTools and stick to ffmpeg from now on.

**Comment by mbunkus** [comment]
mkvmerge v11.0.0 did not really handle your source files correctly. For example, muxing the audio track with ID 12 from your uploaded file `Bug #1990, Transponder 1.ts` results in an unplayable audio track. The track is detected, yes, but its content is pure garbage. So if you used mkvmerge < 12 for such files, then please make sure that the resulting files are fully playable, that their track content isn't broken.

I'm working on fixing mkvmerge's part in all of this so that it'll detect all tracks of all programs (think of "programs" meaning "TV channel") and handles them correctly. That'll restore detection of all tracks and it wil actually fix the broken handling of tracks from a prorgram other than the first.

However, that's only half of what I plan to implement in order to properly solve this issue. The second part will be adjusting the GUI. At the moment the GUI only presents a long list of tracks without any indication which program each track belongs to. I plan to let the GUI present a list of programs along with their station names upon adding the file so that the user can make an informed decision which tracks to copy and which to skip. There's probably be a separate column in the `tracks` list view for that information, too.

For example, in your first example file there are five different programs: `Das Erste HD`, `arte HD`, `PHOENIX HD`, `tagesschau24 HD` and `ONE HD`; that's why there are five video tracks, too. At the moment there's no indication that e.g. track ID 12 (the third video track) is the `PHOENIX HD` channel.

**Comment by mbunkus** [comment]
In essence this issue contains a pre-existing bug, a kind-of-regression and an enhancement.

**Comment by mbunkus** [comment]
[Here](https://mkvtoolnix.download/windows/pre/) are new pre-builds for Windows you can try. With those all tracks should be found properly.

**Comment by nicodorn** [comment]
Thank you very much for your efforts! Unfortunately, I have no acces to a windows machine, so I cannot test your fix. But I will look into it, as soon as you release the next version. If I experience any bugs regarding this issue, I will report them.

ffmpeg also has the sound problem, especially with files from the transponder you mentioned. Recoding the sound them during the muxing process helps.
