### ISSUE TITLE
Ultra HD Blu-ray: playlists (.mpls) not recognized

### ISSUE THREAD

**Issue by C4Wiz** [mbunkus/mkvtoolnix#2010]
How do i add a bluray folder to convert to mkv?

**Comment by remuxer32** [comment]
It depends on which folder do you mean exactly. Because the BD structure contains many folders like `PLAYLIST`, `STREAM`, `META` etc. mkvmerge (the main tool which is responsible for muxing files) supports reading Blu-ray playlist files (`.mpls`), which means that you can choose your wanted movie from the list. My proposition for you is very simple. Do as the following:

1. Run MKVToolNix GUI.

2. Go to the `BDMV` folder and drag & drop the `index.bdmv` (or `MovieObject.bdmv`) file onto the multiplex tool (Multiplexer). If you do this properly, the GUI will start scanning all of the Blu-ray playlists which are located in the `PLAYLIST` folder. After scanning completion, you will see the dialog with scanned playlists. Now you can add any playlist you want.

I've made two helpful screenshots for you to show how it looks like:

- https://postimg.org/image/r7bfd22nl/

- https://postimg.org/image/3uotu1ba3/

**Comment by C4Wiz** [comment]
I tried that and it just stays on scanning forever

**Comment by remuxer32** [comment]
Hmmm, it's very strange because I have tons of Blu-rays, and I have never had such a problem; the GUI always scans Blu-ray playlists correctly. Perhaps your Blu-ray Disc structure is broken? In order to make sure, I recommend you to install a nice program — **BDInfo**. BDInfo is able to scan your whole Blu-ray Disc and shows you very detailed information about playlists, tracks, videos, subtitles etc. To download that program, go to this site:

- https://www.videohelp.com/software/BDInfo

I'm using BDInfo 0.5.8. All you have to do is to add the `BDMV` folder using the `Browse` button. BDInfo will show you tons of playlist. The playlist which has the longest duration is (generally) your main movie. Then add that playlist (you will find it in the `PLAYLIST` folder) to the GUI (Multiplexer). The GUI will ask you what to with that playlist — choose **_Don't scan, just add the file_**. That's it. 

Note: if BDInfo doesn't show you anything (an error message for example), it means that your BD structure is broken or incomplete. BTW: what is the name of the movie you are trying to add?

**Comment by mkver** [comment]
Since version 9.7 MKVToolNix can handle the playlists in the backup folder. Maybe you want to give them a try.

**Comment by C4Wiz** [comment]
if i add the playlist i get this:

![screen shot 2017-06-13 at 7 03 52 am](https://user-images.githubusercontent.com/3883521/27083661-811db03a-5006-11e7-9b79-490e495374d6.png)

and when i add the index.bdmv i get this, and it just sits there

![screen shot 2017-06-13 at 7 04 47 am](https://user-images.githubusercontent.com/3883521/27083715-aa82a41c-5006-11e7-937c-1ea958c2f1cc.png)

**Comment by hubblec4** [comment]
An UHD Bluray is not a Bluray. Maybe there are many equal things but also differens.

**Comment by C4Wiz** [comment]
i understand that, the folder structure is identical, the playlist header is different though
i had to add .txt so it would upload

[00001.mpls.txt](https://github.com/mbunkus/mkvtoolnix/files/1071785/00001.mpls.txt)

**Comment by C4Wiz** [comment]
if i change the header from mpls0300 to mpls0200 it loads right up

**Comment by remuxer32** [comment]
Ah yes, now everything is clear. It seems that mkvmerge doesn't support those playlists (at least some of them), which come from Ultra HD Blu-ray Discs, which is absolutely understandable because any support for 4K Blu-ray Discs (playlists) has **not** been implemented yet in mkvmerge — that's the reason. Probably Moritz Bunkus (the author of MKVToolNix) will be willing to add support for them sometime in the future, but the final decision belongs to him, of course. It's very likely that this issue will be an enhancement. 

@C4Wiz 

At the moment I have only one tip for you: try to add the main `.m2ts` file (the biggest one; that's the movie) directly to the GUI (Multiplexer), and just start multiplexing. Fortunately mkvmerge fully supports `.m2ts `files (MPEG Transport Streams); there shouldn't be any problems, I think. Unless there is something new in the Ultra HD Blu-rays I don't know about, but I don't think so. People on the MakeMKV forum write that muxing `.m2ts` files from UHD Blu-rays via MKVToolNix works fine, therefore I recommend the same thing. Note: currently MakeMKV doesn't support Ultra HD Blu-rays. There is lack of proper code (just for now I hope so ☺).

If you had been more precise at the beginning, we could have helped you much faster. Because, like @hubblec4 rightly said, a Blu-ray is not an Ultra HD Blu-ray. They differ somehow, even if there are some (or many) things the same. So just for the future: try to be as precise as possible, please. Thanks to that you will save your and our time. 

And could you tell us, please, what is the name of the movie (UHD Blu-ray Disc)? Maybe I could get the same one and test it myself. Thanks in advance.

**Comment by C4Wiz** [comment]
UHD bluray title is Inferno

adding the main M2TS file, results in no naming of subtitle tracks, and there is no chapters

**Comment by remuxer32** [comment]
Okay, thanks again. Inferno's size is over 50 GB, so it's really huge, but maybe I will be able to get it somehow :)

About chapters: yes, there are no chapters because chapters on Blu-rays are always stored in playlists (`.mpls` files), not in `.m2ts` files directly. `.m2ts` files never contain any chapters. That's the limitation, unfortunately. 

About subtitle tracks: hmmm, it seems that `.m2ts` files (MPEG TS) on Blu-rays and Ultra HD Blu-rays differ somehow. If so, there will be probably need to implement support for them (`.m2ts` on Ultra HD Blu-rays, of course).

**Comment by C4Wiz** [comment]
i used chapter grabber, changed the playlist header from 300 to 200, and extracted the chapter list, then added the M2TS into the gui and added the chapter file, i left all subtitles enable, when i play it back i will find the right one and re run the mkv throuth the gui and remove all the uneccesary ones

**Comment by remuxer32** [comment]
It's a clever idea. Will be helpful for people who have the same problem. Thanks.

**Comment by remuxer32** [comment]
**Important information for people who are interested in 4K Ultra HD Blu-ray Discs:**

BDInfo from this site: https://www.videohelp.com/software/BDInfo does **NOT** support scanning Ultra HD Blu-rays (only "plain" Blu-rays 1080p are supported). 

But there is another BDInfo which happily supports scanning Ultra HD Blu-rays (only unprotected for now). I mean BDInfo from DVDFab. Since version `10.0.3.9` DVDFab handles such 4K Blu-rays, as well as Blu-rays 1080p, of course. 

Here you can read detailed information about BDInfo in DVDFab:

- http://www.dvdfab.cn/bdinfo.htm

And here you can read the ChangeLog:

- http://www.dvdfab.cn/dvd-fab-new.htm

**Comment by hubblec4** [comment]
@C4Wiz 
You could use my chapterEditor for the chapters, cause you don't need to edit the mpls header. The mpls file which you shared with us works fine in my cE.

**Comment by C4Wiz** [comment]
so i used the above method with patriots day and it works flawlessly.

i used the same method with inferno, and i get nothing.

playback on a duneHD solo lite

both play on the Mac but i don't have a kaly lake processor so it's choppy

**Comment by remuxer32** [comment]
Alright. I have finally got _Inferno_ (Ultra HD Blu-ray) in my hands, and I confirm that all of the playlists (`.mpls`) are not recognized at all. Whenever I try to add any playlist from the `PLAYLIST` directory, I always get the known error: **The file was not recognized as a supported format (exit code: 0)**.

Interestingly, if I add the `index.bdmv` (or `MovieObject.bdmv`) file to the the multiplex tool, the GUI starts scanning directory (in my case scanning is running correctly), but no playlists are shown after scanning completion = they are not recognized at all (as stated above).

And now something the most interesting. mkvmerge, indeed, recognizes MPEG TS (`.m2ts` files) but doesn't recognize any track languages! See this screenshot, please:

![mkvtoolnix gui](https://user-images.githubusercontent.com/10992208/27133499-9385d344-5112-11e7-883e-f187bc6a4e2a.png)

As we can see, everywhere is "und". It means that MPEG TS on Ultra HD Blu-rays & Blu-rays differ somehow, and mkvmerge is not able to handle detecting track languages from MPEG TS yet, which come from Ultra-HD Blu-rays (at least from _Inferno_).

But that's not all. The most shocking is that tsMuxeR (which is not supported anymore!) recognizes track languages without problems (not all but most of them). Moreover, it recognizes playlists from the Ultra HD Blu-ray correctly whereas mkvmerge doesn't. It's absolutely unbelievable; especially when the last release of tsMuxeR comes from 2014! (there were no Ultra HD Blu-rays yet). See, please: 

![tsmuxer](https://user-images.githubusercontent.com/10992208/27134468-f2d6c742-5115-11e7-9352-de3e00458158.png)

Summarizing, we have two problems here:

1. Playlists (`.mpls` files) from the Ultra HD Blu-ray (_Inferno_) are not recognized.

2. Track languages in MPEG TS on the Ultra HD Blu-ray are not recognized.

Because they are two different problems, my proposition is to create a separate issue for the first one. The second one can be discussed here. 

Of course, in order to fix these two, I'm able to upload the whole Ultra HD Blu-ray (over 50 GB) to the FTP server. I'm waiting for you to give me the green light, Mosu :)

**Comment by mbunkus** [comment]
mkvmerge is very strict regarding the format of the MPLS files. At the moment it purposefully compares the version number to 0200,and if they don't match it will treat the file as an unknown type. Ideally the "fix" is to accept 0300, too, but I want to look into the differences between the two versions before I make that change.

The track languages aren't stored in the M2TS files; as soon as the MPLS files are recognized the languages will be recognized again. There's no need to open a separate issue for that.

**Comment by mbunkus** [comment]
I'd appreciate a sample file, of course.

**Comment by remuxer32** [comment]
> The track languages aren't stored in the M2TS files

Thanks for correcting me. I'll keep it in mind. I'll try to upload the Ultra HD Blu-ray to your FTP server soon.

**Comment by remuxer32** [comment]
@mbunkus 

`Inferno (2016) Ultra HD Blu-ray [Issue #2010]` has been successfully uploaded to your FTP server.

**Comment by remuxer32** [comment]
BTW: I forgot to mention that the chapter editor doesn't recognize all of the playlists (`.mpls` files) that come from _Inferno_, of course (no chapters are shown). But it's rather obvious as even mkvmerge doesn't recognize them.

**Comment by hubblec4** [comment]
The chapter syntax of Bluray is equal to UHD-Bluray, so only the MPLS version number is the issue.
My chapterEditor is able to read UHD-Bluray mpls chapters.

**Comment by mbunkus** [comment]
Unfortunately I cannot seem to find any public information about the file format differences between version `0200` and `0300`. Yes, accepting `0300` seems to work fine so far, but ideally I'd like to have some more solid information.

**Comment by hubblec4** [comment]
Yes of course, the UHD-mpls specs are not available for the moment. But it seems to work fine and I can't find differnces in the bit-and-bytes. Looks always equal.
I'm also interessted in any info to this topic.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include both changes are available.

**Comment by remuxer32** [comment]
I've already downloaded the latest pre-build, and I have to say that the issue hasn't been fully fixed yet. Almost all of the playlists are recognized correctly, but there is one playlist which is still not recognized at all: `00001.mpls` — that is the most important playlist because it is related with the main movie: `00001.m2ts` file. I still see the known error: **The file was not recognized as a supported format (exit code: 0).**

The chapter editor recognizes that playlist (as well as the other ones) correctly, though.

**Comment by remuxer32** [comment]
EDIT: I've just tried again, and this time mkvmerge recognizes that playlist correctly.....very strange.

**Comment by mbunkus** [comment]
`00001.mpls` works just fine here. Keep in mind that the GUI caches identification results, even negative ones. You'll have to clear that cache. My guess is that your second try was with a new installation/new copy of the portable version, hence with an empty cache.

**Comment by mbunkus** [comment]
[Cache folder location](https://github.com/mbunkus/mkvtoolnix/wiki/Location-of-settings,-job-queue,-cache-folder)

**Comment by remuxer32** [comment]
Yes, you're right, I totally forgot about clearing the cache. Now everything works fine. Sorry for the confusion.

**Comment by huegelc** [comment]
Still doesnt work:

```
mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
Error: The type of file '00001.mpls' could not be recognized.
```
OS: Xenial
Source: The Shallows UltraHD 4K

**Comment by remuxer32** [comment]
@huegelc 

Could you upload somewhere **all** of the playlists (`.mpls`) from your Blu-ray, please? You can pack them into an archive, for example. It would be good to investigate them deeply. Even better you can upload them to the Mosu's FTP server. See:

- https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server

Another good (but little crazy) idea is to upload the **WHOLE** Ultra HD Blu-ray (yes, I know it can be problematic as it's very big), but maybe the problem is more tricky, hence there might be necessary to investigate the whole Blu-ray structure. But for now just try to upload those playlists. Thank you.

**Comment by mbunkus** [comment]
Please don't continue in this issue and open a new one instead. If there's indeed a real bug, it will almost certainly have nothing to do with the reason discussed in this issue. Thanks.

**Comment by huegelc** [comment]
@remuxer32 @mbunkus 
Continuing here: https://github.com/mbunkus/mkvtoolnix/issues/2109

Thx
