### ISSUE TITLE
Audio stream 0x80 not recognized in VOB file (DVD: Salt)

### ISSUE THREAD

**Issue by hubblec4** [mbunkus/mkvtoolnix#2016]
DVD Salt: There is a first audio stream with 0x80, but MTX don't recognized it. 
I upload a short sample to your FTP.

**Comment by mbunkus** [comment]
Thanks.

**Comment by remuxer32** [comment]
New pre-builds for Windows that contain the fix have been uploaded here: 

- https://mkvtoolnix.download/windows/pre/

**Comment by hubblec4** [comment]
I have testes it, and the first audio stream 0x80 is recognized.

BUT, you have changed in the MTX-Identify-JSON the values for the "sub_stream_id" entry.
Old: 1. audio: 80, 2. audio 81 and so on
New: 1. audio 130, 2. audio 131 and so on.

These new values breaks my DVD2mkv-Editor. 
Why have you change it? And could I substract a value of 50 and then I have the old sub_stream_ids ?

**Comment by mbunkus** [comment]
I've changed it because the old format was a hexadecimal string. Outputting a number as a string (and as a hexadecimal one at that) is something that I had wanted to avoid in the JSON identification output. Therefore this was a bug, plain and simple.

The old value `"80"` is therefore nothing else than the hexadecimal representation of the decimal value 128.

**Comment by hubblec4** [comment]
OK, good to know. So is MTX 12.0.0 the last version with hex values?!

A short side quest. 
The entry "number" is this impotant for the identfication? What means these entry?

**Comment by mbunkus** [comment]
`number` contains a track number; how that number is calculated depends on the container format (e.g. for transport streams it's the program ID, for program streams it's a combination of the stream ID & sub-stream ID, for Matroska files it's the track number element etc). mkvmerge doesn't really use that number for anything important. It's mostly output so that correlating the information with other tools gets easier.

**Comment by mbunkus** [comment]
> OK, good to know. So is MTX 12.0.0 the last version with hex values?!

You shouldn't make that decision based on mkvmerge's version number. Instead look at the JSON schema version number output during the identification (the `identification_format_version` property). JSON schema up to and including v7 use hexadecimal numbers as strings for `stream_id` and `sub_stream_id` whereas JSON schema version v8 and higher will use normal JSON numbers instead.

**Comment by hubblec4** [comment]
Thanks for the info for the "number" entry.

identification_format_version property
I will keep that in my mind!
