### ISSUE TITLE
Tags and wiki don't match

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2022]
Hello,

according to [wiki page about tags](https://github.com/mbunkus/mkvtoolnix/wiki/Automatic-tag-generation) the ``NUMBER_OF_BYTES`` field is supposed to contain the number of bytes in the track before the Matroska track compression is applied. But this is not the way it is currently handled by mkvmerge: Using zlib or not changes the ``NUMBER_OF_BYTES`` field. This can be proven with any picture based subtitles.

Greetings
Andi

PS: That page contains some typos etc.: "present int he track": in the. "For mkvmerge this contains tag": this tag contains. "In mmg you can add that option": mmg is outdated. "disable reading tags fromt the source file": from the.

**Comment by remuxer32** [comment]
Thanks. Will be fixed soon, don't worry. Except typos, there are also missing commas; I will add them, of course.

**Comment by mkver** [comment]
This sounds as if you are sure that it is the wiki page that is wrong. Are you sure about this? Maybe it describes what Moritz had in mind, but hasn't implemented due to a bug (in mkvmerge, not the documentation).

**Comment by mbunkus** [comment]
Thanks for reporting this. The documentation is correct in this case; mkvmerge's behavior is buggy. My intention was to have `NUMBER_OF_BYTES` reflect the number of bytes as they come out of the encoder (so that the value can actually be used to calculcate the number of bits per second in a way that's useful to users and not confusing), and that number is the one before any of Matroska's content encoding schemes is applied.

**Comment by remuxer32** [comment]
My previous comment only applied to errors in the wiki page (such as typos, missing commas etc.). I didn't say anything about `NUMBER_OF_BYTES` as I wasn't sure regarding that, of course. 

I don't agree with removing the "documentation" label because the wiki page had errors, too, so the label is suitable for that (like in the previous report where errors in wiki were reported as well). In this case we have two problems: wrong mkvmerge's behaviour (which was successfully fixed) and errors in the wiki page: therefore the two labels — "mkvmerge" & "documentation" — are correct in my opinion.

Anyway, I have already fixed those errors (typos, missing commas, one missing colon etc.). See:

- https://github.com/mbunkus/mkvtoolnix/wiki/Automatic-tag-generation/_history
