### ISSUE TITLE
Simple edit of header "Default" flag rearranges tracks and enlarges file.

### ISSUE THREAD

**Issue by anon1970** [mbunkus/mkvtoolnix#2026]
I am using mkvtoolnix v13 on Windows 64-bit.

When using the header editor to make very simple changes, e.g. flip the value of a track's "Default" flag, I notice that the output file is structurally different - track headers are moved to the end of the file, even though they have not grown, and thus the output file also grows.

Afterwards mkvinfo no longer shows the new track header details.

If you change a flag from true to false, then back to true, the final file is not byte-identical to the original.

Is it possible to use the header editor such that these side effects do not occur?

If not, could such an enhancement be implemented please?
I would think that it should be easy to check the overall size of the new file headers and change behaviour accordingly, yes?

Thanks very much.

**Comment by mbunkus** [comment]
No, in general this is not possible. This is simply how it is. If you require the tracks to be in the front, then you'll have to remux.

**Comment by anon1970** [comment]
For the benefit of all, can you please explain this a little more?

Is this due to a limitation in the specs for an mkv file, or perhaps due to
the design of the mkvtool software, or perhaps some other factor?

At the moment I can open an mkv file in a regular text editor, find and
flip the target byte and then save the file. It works fine. But it is
painful.

Why then would "mkvpropedit test.mkv --edit track:s1 --set flag-default=1"
not do the same thing?

​I'm happy to dive into the source code if necessary.....​

Thanks.

**Comment by mbunkus** [comment]
There are several factors. One is that the Matroska file format is rather flexible. Several elements can have default values that apply if the element is not present in the file. Changing such an element is possible, of course, but requires adding the element with the changed value which in turn means that the headers now require more space than before.

The next problem is that the libraries MKVToolNix used (libebml and libmatroska) don't make modifications of a single value easy. They're written more with correctness in mind. This means that reading the headers from the file, changing a single value, and writing them back may make the headers larger than they were as optional elements may have been added.

Matroska doesn't have a fixed layout for header elements either. They can occur in many places within the file, the order is not fixed, and there is no guarantee that there is enough space to write updates headers.

You're welcome to look into making all of this more flexible, but it is a metric shitton of work. At the moment headers are read and written en blic, meaning that just because you want to change one flag the programs have to read all track headers, modify one element (and add it if it isn't present), and write them out en bloc. Here libmatroska makes life a bit harder due to the aforementioned safety features of always trying to add all required elements... 

For Matroska changing existing elements is much, much more involved than "find element in file, change its value".
