### ISSUE TITLE
Audio not muxed properly from old QuickTime file

### ISSUE THREAD

**Issue by magiblot** [mbunkus/mkvtoolnix#2040]
Hello. I have been shared this QuickTime file encoded in 1995, according to the metadata.
https://cdn.discordapp.com/attachments/278328972939493376/334698639387656193/johnnyq.mov

When opening in MKVToolNix for muxing the audio track, the volume is altered. It sounds very low... Try it yourselves.

Cheers.

**Comment by mbunkus** [comment]
Here the volume isn't low, but the sound is distorted. I may look into this, but with a low priority.

**Comment by magiblot** [comment]
Indeed, in my end the volume isn't low either, but I found it amusing to have this bug in mkvmerge. That's why I encouraged you to expect an almost silent clip, it was a joke. Excuse me if you didn't like it.

Yes, this is not a great problem. In fact, there are other ways of extracting the PCM track of out the file.

**Comment by mkver** [comment]
According to ffmpeg, the audio inside the mov-file is ``pcm_s8`` (signed 8 bit); there also exists unsigned 8 bit audio. 8 bit PCM audio inside Matroska seems to automatically be treated as unsigned by ffmpeg. There is unfortunately nothing that can be fixed in MKVToolNix: [Matroska](https://matroska.org/technical/specs/codecid/index.html) does not use any private data for PCM; it only stores bitdepth, sampling frequency, channel count and Endianess. One probably has the same problem with 16bit unsigned PCM data. The only thing MKVToolNix can do is throw a warning/an error.
By the way: The way ffmpeg treats audio (if its sign isn't explicitly defined) seems to be derived from the avi/wave world: According to [this stackoverflow post](https://stackoverflow.com/questions/38696198/ffmpeg-audio-conversion-encoder-pcm-u8-working-pcm-s8-not/38698926#38698926) one can only save U8, S16LE, S24LE, S32LE, F32LE and F64LE into avi and wave.

**Comment by magiblot** [comment]
Wouldn't converting to Unsigned - Little Endian before muxing be a good solution?

**Comment by mbunkus** [comment]
Yes, but mkvmerge is not an audio editor. I'm trying hard not to implement such conversions.

@mkver Thanks for the analysis.

As signed 8bit uncompressed audio is very rare, I've decided not to implement such a conversion and leave this issue as "won't fix".

**Comment by magiblot** [comment]
In that case, I think advising the user to do the conversion before muxing (for example, with a warning) would be a good behaviour.

**Comment by mbunkus** [comment]
Sure. But again, that codec is not used widely, and I have better things to do with my time. I would definitely accept patches that implement such a warning, though.

**Comment by mkver** [comment]
Yes, I have already corrected my answer. At first I thought that this part of the Matroska spec is pretty limited and therefore stupid, but that's obsolete now. But the specs should be updated so that the sign of PCM-data in Matroska is properly defined. I will probably open an issue for this later.
