### ISSUE TITLE
Notifications about BOM

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2053]
Hello,

if one adds an srt file, the default character set of this file is always set to whatever is set as the default subtitle character set. This happens even when this file contains a BOM which overrides any selection regarding the character set. Can't this be changed so that if a srt file contains a BOM, this information is conveyed to the user during file identification? (For the GUI this means setting the character set to whatever the BOM indicates and locking to the character set selecting menu for these files just like it's already done for subtitles in a Matroska container.)

Greetings
Andi

**Comment by mbunkus** [comment]
Not a bad idea. Thanks.

**Comment by mbunkus** [comment]
I guess that the BOM isn't what you're actually interested in, is it? But the fact that you don't have to worry about the encoding because mkvmerge can already determine the encoding with confidence, right? I'm leaning towards only signalling the file's encoding via the identification result but not the BOM, because the former conveys both pieces of information:

1. the actual encoding the GUI can set the drop down to
2. the fact that mkvmerge can determine the encoding on its own

On top of that there are situations in which mkvmerge can determine the encoding and doesn't allow a change even though there is no BOM: XML files that declare its encoding properly.

**Comment by mbunkus** [comment]
As a matter of fact the best method would be to mark the tracks with the encoding because there are certain situations where there is encoding information inside a container on the track level… So the BOM information is even more useless from the GUI's point of view. I think I'll go for that: only `encoding` is signaled, in the track properties.

**Comment by mkver** [comment]
Yes, I am actually only interested in encoding information, not the BOM per se. Your plan sounds good.
