### ISSUE TITLE
(Version 14.0.0 Flow) Fail to preview SRT subtitles

### ISSUE THREAD

**Issue by mkvTest** [mbunkus/mkvtoolnix#2055]
In Version 14.0.0 Flow, SRT subtitles cannot be previewed (SRT file with UTF-8 character coding). The button simply grey out as shown in screen-dump below. In previous versions, SRT subtitle text could be previewed after pressing the right-hand-side "AC" button.
 
![subtitlespreviewgreyout](https://user-images.githubusercontent.com/30397241/28506180-011905da-705c-11e7-9a38-134b6e398de8.JPG)

**Comment by mkver** [comment]
This is an intential change in version 14.0. See #2053: Because your file contains a byte order mark indicating its encoding, it is not necessary for the user to manually select an encoding. In order to signal this to the user, the list and the button are greyed out.
Note that in previous versions of MKVToolNix the selected encoding is ignored for a file using a BOM and the encoding indicated by the BOM is used instead.

**Comment by mbunkus** [comment]
This is indeed not a bug but intentional behavior as @mkver has explained.

**Comment by mkvTest** [comment]
Is it possible to grey out only the character set selection but allow the "AC" button for preview? This might help to identify problem earlier in odd cases like wrong BOM in the original srt file (i.e. BOM not match the actual text of the file).

**Comment by mbunkus** [comment]
Technically anything is possible, it's only software after all. But that doesn't mean it would be good design or that it wouldn't confuse users. I won't change this.
