### ISSUE TITLE
Fail to build with GCC 7.1.0

### ISSUE THREAD

**Issue by marillat** [mbunkus/mkvtoolnix#2067]
Hi,

GCC 7 is now the default compiler in unstable and thus mkvtoolnix fail to build.
See https://bugs.debian.org/853553

**Comment by mbunkus** [comment]
This looks like you'll have to re-compile libEBML and libMatroska with that compiler version, too. In general MKVToolNix compiles just fine with gcc 7..10; I've been using that combination for development since it came out (primary development platform is Arch, at the moment I'm even using 7.1.1).

See #1987 which shows the same issues, and where re-building libEBML & libMatroska fixed the issue.

**Comment by marillat** [comment]
Ok this fix the build. Sorry for the noise.
For the record I'll fill bug report against libebml and libmatroska packages.

**Comment by mbunkus** [comment]
Great, and no problem.

**Comment by marillat** [comment]
For the record only a libebml rebuild is needed.

**Comment by mbunkus** [comment]
Interesting. Thanks for letting me know.
