### ISSUE TITLE
Assembler errors with --enable-ubsan

### ISSUE THREAD

**Issue by darealshinji** [mbunkus/mkvtoolnix#2077]
Building with `--enable-ubsan` results in error messages like these:
```
         CXX src/merge/mkvmerge.cpp
/tmp/ccsVmI6s.s: Assembler messages:
/tmp/ccsVmI6s.s:1052104: Error: symbol `.Lubsan_type3' is already defined
/tmp/ccsVmI6s.s:1052112: Error: symbol `.Lubsan_type2' is already defined
```
OS: Ubuntu 16.04
GCC: 5.4.0
GNU assembler: 2.26.1

**Comment by mbunkus** [comment]
I've just verified that the whole of MKVToolNix builds fine for me on Arch with `gcc` 7.1.1, `as` 2.28.0. As those symbols are from the UBSAN code and not from the MKVToolNix code, there's nothing I can realistically do about it, nor do I think it's a bug in MKVToolNix in the first place since all that's done differently is adding `-fsanitize=undefined` to both compiler and linker calls; everything else is up to `gcc`.

You might file a bug report with gcc, but as it works with 7.1.1 I doubt that'll lead to anything.

**Comment by darealshinji** [comment]
Using GCC 6.4 works too by the way.
