### ISSUE TITLE
Duration of the extracted track with mkvextract is different of the source

### ISSUE THREAD

**Issue by AmazighChahid** [mbunkus/mkvtoolnix#2089]
Hi,

When I extract a track of a movie with a duration of 120 minutes for example, with mkvtoolnix (15.0) the track duration is 120 minutes so it's ok. But if I use with command shell the "mkvextract tracks source-filename [options] TID1:dest-filename1 " the duration got is very different. Do you know why ?

The movie used is the following : http://uptobox.com/4hqxcu9ka8ii
The command shell used is : mkvextract tracks MO-rTBHcCbFzr-Salt-EN.FR.mkv  1:audio_salt.mka

![duration different](https://user-images.githubusercontent.com/18754021/30002967-1488d598-90b7-11e7-879a-7e173660bb2a.png)

**Comment by mkver** [comment]
a) The output of mkvextract isn't a Matroska file (as "audio_salt.mka" indicates), but an elementary stream. An elementary stream with aac-data in it usually has the extension .aac.
b) I'm still downloading, but my guess is that your aac-track has a variable bitrate and your tool estimates its length from the total filesize and the bitrate at the beginning of the file (which is probably lower because most movies have a bit of silence at the beginning, so the length gets overestimated). This is an inherently inaccurate guess and no bug in mkvextract. If you just want one of the audio tracks without the video, you should use mkvmerge to create a Matroska file with only the desired audio track in it. The Matroska file contains a duration attribute and an index for easy seeking.
c) Of course it could also be that your tool has a bug.

**Comment by mkver** [comment]
ffmpeg estimates this file as having a length of 3:14:01.53 -- based upon an analysis of the first 65696 bytes. (Somehow setting `-probesize` and `-analyzeduration` doesn't change this, but that would be a topic for a forum for ffmpeg users.) But if I decode the file or copy it, ffmpeg agrees with the length of 1h 44m. So this is not a bug in MKVToolNix.

**Comment by mbunkus** [comment]
Thanks for the analysis, @mkver.
