### ISSUE TITLE
mkvextract extracts strange relative position

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2091]
Hello,

as you know, the relative position should be counted from the position in the referenced cluster immediately following the cluster EBML-element (id+length) so that the position 0 is usually occupied by the EBML-id for the cluster timestamp.* That's how mkvmerge writes the cues in the file. But when one extracts them with mkvextract, it seems that mkvextract uses the position of the cluster as its reference point. Consequently the extracted numbers are bigger than the ones stored in the file. Is this intentional? (It might well be, after all the cluster position is relative to the segment start in the file and relative to the beginning of the file in the extracted cues.)

Grüße
Andi

*: Except if there are CRC-32 elements. I actually don't know what the zero point is in this case.

**Comment by mbunkus** [comment]
Yes, this is intentional. The reason is simple: in order to calculate the absolute position of a block group/simple block pointed to by a cue the start of the data portion of the cluster must be known. That value is basically the cluster's position + its EBML ID size + the size of its "length" field. These pieces of information are known to a parser when it parses the Matroska file, but the size of the "length" field is unknown if all one has is the file created by mkvextract's "cues" extraction mode.

Here's an example: a cluster in a file I've just created starts at 58269. Its EBML ID is four bytes long, and its total length is encoded in three bytes. Therefore the data portion starts at 58276.

Now if mkvextract wrote the relative position as-is, e.g.

```
timecode=00:00:03.587000000 duration=- cluster_position=58269 relative_position=4
```

…then how would a reader supposed to be able to calculate the absolute file position 58280 from that? It couldn't, as those "three bytes" are simply not known. A different cluster in the same file only has a two byte long "length" field, for example.

Therefore `relative_position` is indeed relative to `cluster_position` in the output.
