### ISSUE TITLE
Header editor Freezes

### ISSUE THREAD

**Issue by Cyberavater** [mbunkus/mkvtoolnix#2101]
Some time it Freezes for good while using header editor to add attachments. [Just to let you know.]

**Comment by mkver** [comment]
You should upload a sample (a file that has not been modified yet that freezes when you add an attachment which you should upload, too). If you don't have the unmodified file any more, then the second best option is to upload the modified file. Uploads should be made to [the ftp server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server).

**Comment by mbunkus** [comment]
Can you reproduce the issue (meaning do you have a combination of a Matroska file you're editing and a certain attachment you're trying to add that freezes the program)? If so, please upload them to my FTP server as @mkver has said. Otherwise I won't be able to do anything about this as I cannot reproduce such an issue here myself.

**Comment by mbunkus** [comment]
Additional questions:

1. Which operating system & version are you using?
2. Which version of MKVToolNix are you using?
3. Does it happen with different file types or only with one specific file type?

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
