### ISSUE TITLE
4K Ultra HD Blu-ray: playlists (.mpls) not recognized

### ISSUE THREAD

**Issue by huegelc** [mbunkus/mkvtoolnix#2109]
OS: Xenial
Source: The Shallows UltraHD 4K
```
mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
Error: The type of file '00001.mpls' could not be recognized.
```
Uploading `mpls`files

**Comment by remuxer32** [comment]
I have decided to slightly modify the issue's title in order to differentiate. I'm not a fan of keeping two (or more) issues, which have exactly the same name — it might be problematic/misleading when searching closed issues. I think that it is always better to have a perfect arrangement where each issue has a unique title. Of course we can always distinguish each issue via its unique number, but in my opinion searching issues using words (titles) is easier.

**Comment by huegelc** [comment]
`*.mpls` files uploaded to `/upload/2109/The_Shallows/`

The sum of the other files are around 50GB which means it takes 12h to upload. If its mandatory to investigate this issue I´ll upload them as well.

**Comment by mbunkus** [comment]
Just to make sure: is the Blu-ray you're trying to read unencrypted or still encrypted? 'cause mkvmerge can only read unencrypted content.

**Comment by mbunkus** [comment]
mkvmerge parses the MPLS files just fine. I cannot test further without having the M2TS files.

**Comment by huegelc** [comment]
The files are unencrypted.

**Comment by mbunkus** [comment]
No, I don't.

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
