### ISSUE TITLE
Can't select languages in preferences

### ISSUE THREAD

**Issue by kxxc** [mbunkus/mkvtoolnix#2110]
MKVToolNix-16.0.0

Mac 10.13

**Comment by mbunkus** [comment]
Translations aren't supported in macOS due to the OS including a rather outdated version of `gettext`. I have no intention of working on this. See the [supported OSed page](https://github.com/mbunkus/mkvtoolnix/wiki/Officially-supported-operating-systems-and-versions).

Patches are welcome, of course!
