### ISSUE TITLE
Reduce to Core EAC3->AC3

### ISSUE THREAD

**Issue by B00ze64** [mbunkus/mkvtoolnix#2134]
Good day.

Is it possible to add Reduce to Core for EAC3 tracks? Specifically, those that contain a Legacy Substream? According to Wikipedia, the Legacy Substream is a plain AC3 stream, so there is no need to transcode. If possible, that Reduce to Core checkbox should be greyed-out when it's not possible to do this; right now it is always available (I think).

Thank you.
Best Regards,

**Comment by mbunkus** [comment]
E-AC-3 to AC-3: no.

If you mean that you want to keep the AC-3 part of a TrueHD+AC-3 track (that's what "legacy substream" usually means): see [this FAQ entry](../wiki/TrueHD-and-AC-3).

**Comment by mkver** [comment]
The author's question has nothing to do with TrueHD+AC-3 and it's definitely not implemented: Some Bluray-discs contain E-AC-3 with an AC-3-core just like DTS-HD often contains a core. You should actually already have a sample of such a disc: #2102 is about such tracks. Given that the author has already uploaded a sample [elsewhere](https://forum.videohelp.com/attachments/43277-1506985180/The%20Great%20Wall.7z) I could take a look at it. If one demuxes the E-AC-3 tracks, one gets a file divided into packets of size 2304 B; every second of them is an E-AC-3 extension. If one deletes these packets, the resulting file will be accepted as a normal AC-3 file by all programs.

**Comment by mbunkus** [comment]
I don't need samples; I know how E-AC-3 works. My "no" was solely meant in the context of mkvmerge being able to do that (because this is the MKVToolNix bug tracker and not a general audio/video forum; therefore I always answer from the POV of MKVToolNix, not general feasability). The tangent about TrueHD+AC-3 was mostly for the benefit of users who often do not know how all of that works.

I don't have any plans on extending the core reduction functionality to AC-3 myself. Patches that implement it (including updating the documentation) would be very welcome, but judging from the past, no one else won't implement it either. Therefore it's not possible (at the moment).

There are other players out there that aren't free (e.g. anything hardware-based, and a lot of software-based ones, too); so saying that it's a "waste of space" is a rather limited POV.

**Comment by mkver** [comment]
Ok. I just thought that you might have misunderstood the author because of the "res:fixed/implemented"-label. I would have expected a "type:enhancement" and a "res:wontfix". Sorry for that.

**Comment by mbunkus** [comment]
Well, he clearly asked a question. Therefore I labeled it as such. I use "res:fixed/implemented" to signal that the question was answered.

**Comment by B00ze64** [comment]
Good day.

I don't understand why MkvToolnix should support reducing to core for DTS but not for EAC3. Why the distinction? There are lots of hardware decoders out there (i.e. Home Theater Systems) that do not understand EAC3, including my own. But if you will accept patches, then why close this bug as resolved? Leave it open so contributors know this is a feature that should be implemented?

Thank you.
Best Regards,
