### ISSUE TITLE
Error Message mkvmerge Version

### ISSUE THREAD

**Issue by JogyB** [mbunkus/mkvtoolnix#2148]
Hi.

When starting MKVToolNix GUI 17.0.0, I get the following error message (in German):
"Es wurde ein Problem mit der MKVToolNix-Installation festgestellt:
Die von mkvmerge gemeldete Versions-Zeile ('') konnte nicht erkannt werden.
Gewisse Funktionen werden in dieser Situation nicht korrekt arbeiten. Bitte installieren Sie MKVToolNix erneut, oder beheben Sie das Problem manuell."

If I start the program repeatedly, the message sometimes doesn't appear (approx. 1 of 4 cases). I resinstalled the program several times, I tried it as well with a reboot between deinstallation and installation, didn't change anything.

I want to add that I forgot to close the GUI v7.8.0 before installing v17.0.0, this might have something to do with the problem. However, I have no idea what I could do to fix that problem manually.

Thank you.

**Comment by mbunkus** [comment]
This is usually a problem with your setup, e.g. your anti-virus solution. See #2061.

**Comment by JogyB** [comment]
Thank you, fixed it.
However, (temporarily) deactivating Kaspersky didn't work, defining an exception for the mkvtoolnix folder did.

**Comment by mbunkus** [comment]
I have no idea, because I've never had that situation on any of my machines.

**Comment by mbunkus** [comment]
In order to find out more, I've built a debug build that emits some more information. Please download and start Microsoft's [DebugView utility](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) (no installation required). Then download the latest portable [debug build](https://mkvtoolnix.download/windows/debug/64-bit/) of MKVToolNix for Windows and extract it somewhere.

Now start the GUI from the just-extracted debug build. The DebugView utility should now show a couple of entries from MKVToolNix. In DebugView, save the content to a text file and send me that file [via email](https://mkvtoolnix.download/contact.html). Thanks.

**Comment by mbunkus** [comment]
Use build 01591, please.
