### ISSUE TITLE
In header editor allow to set a MIME type manually

### ISSUE THREAD

**Issue by dali99** [mbunkus/mkvtoolnix#2154]
Instead of strictly keeping mime types to the list in [src/common/extern_data.cpp](https://github.com/mbunkus/mkvtoolnix/blob/master/src/common/extern_data.cpp) /etc/mime.types allow users to set the mime type to any string

This would allow people to use application/x-truetype-font, or application/x-font-ttf if their media players behave badly with the new mime types (doubtful) or still specify new mime types if their distribution has not updated the mime.types file (probable)

Specify mime types with extentions such as the layout in truetype fonts or outlines in open font format fonts

And importantly open up for uncommon combinations such as "font/sfnt; layout=sil" that do not have a shorter type

From [RFC8081](https://tools.ietf.org/html/rfc8081)

**Comment by mbunkus** [comment]
Uhm, I'm not sure what you actually want me to implement. The GUI already allows you to enter any kind of text for the MIME type, both in the multiplexer as well as in the header editor. mkvmerge itself allows that, too, as does mkvpropedit. I've actually just verified that all four places work as expected.

Therefore I'll close this as "invalid" because it's already there.
