### ISSUE TITLE
Size of Track

### ISSUE THREAD

**Issue by drsassafras** [mbunkus/mkvtoolnix#2158]
It would be really helpful if the space taken up by a specific track was given. Not sure how easy this would be to implement, but if it's somewhat easy, it could make a big difference in my life.

I often use mkvnix as a diagnostic tool, just to see what a file has in it. I also process files a lot as well, but just getting a good idea of what is what is really important for me in terms of making decisions of where to cut and where not to.

And thanks for the great tool. Love it to death :)

**Comment by mkver** [comment]
MKVToolNix already adds tags that contain the information you are looking for by default. See [here](https://github.com/mbunkus/mkvtoolnix/wiki/Automatic-tag-generation). But MKVToolNix only does this with files it created, of course.
If you also work with Matroska files without said tags, you can let mkvpropedit create them (commandline-switch `--add-track-statistics-tags`). For this mkvpropedit needs to parse the whole file which can be time-consuming.
You can use e.g. Mediainfo to easily read the tags.
Also be aware that mkvmerge is not really a diagnostic tool. It does not really tell you what is in the file, but just what it can handle. If a file contains a track that mkvmerge can't handle, mkvmerge won't tell you about the existence of said track at all. (Older versions of MKVToolNix would e.g. ignore DVB-subtitles in transport streams; or DVD-subtitles in VOB-files which can't be handled by mkvmerge; or teletext streams in transport streams (for which no encapsulation in Matroska is defined at all).)

**Comment by mbunkus** [comment]
What @mkver has said is all correct but only applies to Matroska files as source files. In general such functionality is not really possible to implement due to the nature of most other container format. They simply don't provide that kind of information up-front. My programs would have to read the whole file just to determine the length and size of each track. For certain formats such as MPEG transport stream it gets even worse as timestamps can and regularly do wrap around requiring fancy analysis for determining what mkvmerge will actually make of them.
