### ISSUE TITLE
Feature request: Batch mode

### ISSUE THREAD

**Issue by StriderAJR** [mbunkus/mkvtoolnix#2162]
Hello.

First of all, thank you for this great tool. I use it all the time in my anime publication needs. 

Every day I need to remove 25-100+ files that contain original, english and may be several other audio/subtitle tracks. And I need only original one, for example. So I open all those files in separate tabs and click, click, click, click and click.

It would be so-so great to have some kind of batch mode when you open separate tabs, choose which tracks (by language or by language) should remain and voila!

I know that there are some workarounds from terminal or batch file but using GUI is so nice,,, I don't dream about implementing this feature in near future but may be someday. 

Thanks in advance anyway.

**Comment by mbunkus** [comment]
Batch processing in the GUI won't be implemented. See [this FAQ entry](../wiki/Batch-muxing-with-the-GUI). However, as the FAQ entry states there is the command-line tool "mkvmerge" which can be automated to do everything you could ever desire.

**Comment by remuxer32** [comment]
@StriderAJR 
> when you open separate tabs, choose which tracks (by language or by language) should remain and voila!

The GUI has a feature that allows to select (enable) automatically only those tracks that contain a strictly specified language. See here:
- https://s33.postimg.org/tnqwyrqwv/image.png

All you have to do is to choose your wanted language(-s) from the list on the left side and move them on the list on the right side. I chose only English & Polish (I always need only those two) + Undetermined (und) because many video tracks don't have any language at all. Whenever I open many files (which have tons of tracks with many languages) in separate tabs, only those tracks that contain English & Polish are automatically enabled (selected). Rest of tracks I don't need at all are disabled. 

Also, the GUI allows you to start multiplexing, add job to the queue, save settings, etc. for **all tabs** at the same time (simultaneously). Like here:
- https://s33.postimg.org/m7rnczin3/image.png

**Comment by StriderAJR** [comment]
Wow! Many thanks! I didn't know about all this gorgeous features. You saved ton of my days! Thank you very much.

**Comment by remuxer32** [comment]
You're welcome. I'm glad I could help you :)
