### ISSUE TITLE
No audio when creating MKV from DVD

### ISSUE THREAD

**Issue by bhall7** [mbunkus/mkvtoolnix#2171]
Hello,

I've used mkvtoolnix to create MKVs for a handful of home video DVDs, and I'm finding a handful of them are coming out with no audio. I've tried multiple times, and can't seem to find any reason why the audio is not there. I've used Handbrake to create MP4s without any issues, and I've also used MakeMKV and the audio is there as well.

Any suggestions would be greatly appreciated.

**Comment by mkver** [comment]
First of all: mkvmerge's support for DVDs is not that great. It lacks the ability to remux the subtitles contained in DVDs and it can't handle chapters. This won't matter for your home video DVDs probably.
When you say they come out with no audio do you mean that no audio track is found at all or that an audio track is found, but that the resulting audio track is empty? If it's the first case, then you can go to the preferences, then to the submenu multiplexer and increase the probe range percentage there.

**Comment by gabriellluz** [comment]
I think that's not the purpose of MKVToolnix. I guess MakeMKV should work great for you because it actually focuses on creating MKV files from DVD iso.

**Comment by remuxer32** [comment]
@bhall7

`mkvmerge` (the main tool in the MKVToolNix package which is responsible for creating MKV files from other formats) is not a suitable tool for creating MKV files from DVDs. Why? Like @mkver said: lacks the ability to handle subtitles, chapters which are present on DVDs. 

The DVD structure is very complicated: each movie on DVD is always split into many parts (`VOB` files), hence there is always need to merge all of those parts into a single Matroska file — the whole process must be done perfectly (if we don't want to meet any problems, of course) which is not easy. Due to the fact that `mkvmerge` doesn't support handling `IFO` files which are very important because they contain information for chapters, subtitles and audio tracks, then any using `mkvmerge` with DVDs makes no sense in my opinion (unless you don't need subtitles or chapters, obviously).

Unfortunately, any improvements in `mkvmerge` regarding DVDs won't be added because DVD is an obsolete format nowadays (this is the developer's decision, not mine).

As I have a big collection of DVDs at home, I always recommend using MakeMKV for creating MKV from DVDs. MakeMKV does everything perfectly; I have never met any problems so far, therefore I strongly urge everyone to use MakeMKV for making a DVD copy in MKV every time when needed.

You wrote that there is no audio in your MKV files after using `mkvmerge`, but you haven't specified yet what kind of lack you mean. If you mean "I don't hear any sound after choosing an AC-3 track", then there might be a bug. It would be helpful if you wrote what type of a track you mean (e.g. AC-3, DTS or maybe PCM?).

**Comment by hubblec4** [comment]
I think @bhall7 means there is no audio track inside the mkv. 
This could be a simple issue in the VOB-Parser of mkvmerge.
For starting, Mosu needs a sample, you should upload a peace of the first VOB file. (Use DGSplit for this task)
mkvmerge needs the IFO for Chapters and Subs only, Video and Audio info will be parsed from the VOBs.
I had some DVDs where mkvmerge not recognized all audio streams. I uploaded a sample to Mosu's FTP and he fixed it.

Makemkv is indeed a very good choice, but it has also limitations.

My chapterEditor helps mkvmerge to mux DVDs easy to mkv.

**Comment by bhall7** [comment]
I'm not sure how to say it other than the resulting MKV file simply has no audio at all. When I create an MKV using MakeMKV, it works fine. What's strange is that I successfully used mkvmerge on some different home video DVDs, but I'm totally puzzled as to why one DVD had audio in the resulting MKV and another did not.

Rather than spend too much time on this issue, I'll simply use MakeMKV, as it has accomplished the task without any problems.
